function contract = camera41ExportContract()
%CAMERA41EXPORTCONTRACT Canonical spectral exchange contract for Camera-41.
%   Every SpectraLab artifact explicitly intended for Camera-41 must contain
%   the complete inclusive visible-light interval. Exporters must not expose a
%   caller-selectable wavelength range for this interchange boundary.
visibleLight = spectralab.core.visibleLightContract();
contract = struct( ...
    "Schema", "spectralab.camera41-export-contract", ...
    "SchemaVersion", "1.1", ...
    "Consumer", "Camera-41", ...
    "WavelengthRangeNm", visibleLight.WavelengthRangeNm, ...
    "DomainContract", visibleLight, ...
    "Bounds", "inclusive", ...
    "Requirement", "complete_interval");
end
