function analyses = listAnalyses()
%LISTANALYSES List analyses available to spectralab.report.generate.
%
%   analyses = spectralab.report.listAnalyses()
%
% Returns public, data-only summaries. Execution function handles remain
% internal to the canonical RP-020 analysis registry.

registry = spectralab.report.internal.createAnalysisRegistry();

analyses = repmat(struct( ...
    "AnalysisId", "", ...
    "Name", "", ...
    "Description", "", ...
    "InputRoles", strings(1,0), ...
    "HasFigure", false), ...
    numel(registry), 1);

for k = 1:numel(registry)
    definition = registry(k).AnalysisDefinition;

    analyses(k) = struct( ...
        "AnalysisId", definition.AnalysisId, ...
        "Name", definition.Name, ...
        "Description", definition.Description, ...
        "InputRoles", registry(k).InputRoles, ...
        "HasFigure", definition.HasFigure);
end
end
