function filter = photopic()
%PHOTOPIC Return the CIE spectral luminous efficiency V(lambda).
%
%   filter = spectralab.filters.photopic()
%
%   This is exposed separately from CIE 1931 yBar because its scientific
%   meaning is photometric even though the tabulated values are identical.

    packageFolder = fileparts(mfilename("fullpath"));
    filename = fullfile( ...
        packageFolder, ...
        "data", ...
        "CIE_sle_photopic.csv");

    if ~isfile(filename)
        error( ...
            "spectralab:filters:photopic:MissingData", ...
            "Required CIE photopic dataset was not found: %s", ...
            filename);
    end

    data = readmatrix(filename);

    if size(data,2) ~= 2 || size(data,1) < 2
        error( ...
            "spectralab:filters:photopic:InvalidData", ...
            "The photopic dataset must contain wavelength and V(lambda).");
    end

    filter = spectralab.core.SpectralFilter.fromTable( ...
        data(:,1), ...
        data(:,2), ...
        Name="CIE photopic luminous efficiency V(lambda)", ...
        Unit="relative", ...
        Source="CIE 2019, DOI 10.25039/CIE.DS.dktna2s3", ...
        Description="CIE spectral luminous efficiency function for photopic vision.");
end
