function filter = photopic()
%PHOTOPIC Return the CIE spectral luminous efficiency V(lambda).
%
%   filter = spectralab.filters.photopic()
%
%   This is exposed separately from CIE 1931 yBar because its scientific
%   meaning is photometric even though the tabulated values are identical.

    filter = spectralab.filters.internal.loadStandardFilter( ...
        "CIE_sle_photopic.csv", ...
        Name="CIE photopic luminous efficiency V(lambda)", ...
        Unit="relative", ...
        Source="CIE 2019, DOI 10.25039/CIE.DS.dktna2s3", ...
        Description="CIE spectral luminous efficiency function for photopic vision.", ...
        Normalize=false);

end