function filter = blue()
%BLUE Return the ISO Status M blue transmission weighting.
%
%   filter = spectralab.filters.statusM.blue()
%
%   Values are normalized linear spectral products derived from the
%   logarithmic documentary values in ANSI/ISO 5-3:1995, Table 4.

    [wavelengthNm, value] = statusMData("blue");

    filter = spectralab.core.SpectralFilter.fromTable( ...
        wavelengthNm, ...
        value, ...
        Name="ISO Status M Blue transmission", ...
        Unit="relative spectral product", ...
        Source="ANSI/ISO 5-3:1995, Table 4", ...
        Description="Normalized Status M blue transmission spectral product.");
end
