function filter = green()
%GREEN Return the ISO Status M green transmission weighting.
%
%   filter = spectralab.filters.statusM.green()
%
%   Values are normalized linear spectral products derived from the
%   logarithmic documentary values in ANSI/ISO 5-3:1995, Table 4.

    [wavelengthNm, value] = statusMData("green");

    filter = spectralab.core.SpectralFilter.fromTable( ...
        wavelengthNm, ...
        value, ...
        Name="ISO Status M Green transmission", ...
        Unit="relative spectral product", ...
        Source="ANSI/ISO 5-3:1995, Table 4", ...
        Description="Normalized Status M green transmission spectral product.");
end
