function filter = red()
%RED Return the ISO Status M red transmission weighting.
%
%   filter = spectralab.filters.statusM.red()
%
%   Values are normalized linear spectral products derived from the
%   logarithmic documentary values in ANSI/ISO 5-3:1995, Table 4.

    [wavelengthNm, value] = statusMData("red");

    filter = spectralab.core.SpectralFilter.fromTable( ...
        wavelengthNm, ...
        value, ...
        Name="ISO Status M Red transmission", ...
        Unit="relative spectral product", ...
        Source="ANSI/ISO 5-3:1995, Table 4", ...
        Description="Normalized Status M red transmission spectral product.");
end
