function inst = createInstrument(instrumentId, varargin)
%CREATEINSTRUMENT Create a SpectraLab instrument.
%
% Public callers identify the physical instrument, not its measurement
% backend. SpectraLab selects the required backend internally.
%
% Canonical examples:
%   spectralab.drivers.createInstrument("i1Pro2")
%   spectralab.drivers.createInstrument("mock")

if nargin < 1 || strlength(string(instrumentId)) == 0
    error( ...
        "SpectraLab:Drivers:MissingKind", ...
        "ERROR [SPL-008]\n\n" + ...
        "Instrument identifier is required.\n\n" + ...
        "What to do:\n" + ...
        "Use for example:\n" + ...
        "    spectralab.drivers.createInstrument(""i1Pro2"")");
end

requestedId = string(instrumentId);
normalizedId = lower(strtrim(requestedId));

switch normalizedId
    case {"mock", "simulated", "simulation"}
        inst = spectralab.drivers.MockInstrument(varargin{:});

    case "i1pro2"
        inst = spectralab.drivers.SpotreadInstrument( ...
            "InstrumentId", ...
            "i1Pro2", ...
            varargin{:});

    case "i1pro"
        inst = spectralab.drivers.SpotreadInstrument( ...
            "InstrumentId", ...
            "i1Pro", ...
            varargin{:});

    case {"spotread", "argyll"}
        warning( ...
            "SpectraLab:Drivers:LegacyBackendName", ...
            "The identifier '%s' names a measurement backend, not a " + ...
            "physical instrument. It remains accepted for v0.7.0 " + ...
            "compatibility and currently resolves to i1Pro2. " + ...
            "Use spectralab.drivers.createInstrument(""i1Pro2"") " + ...
            "in new code.", ...
            requestedId);

        inst = spectralab.drivers.SpotreadInstrument( ...
            "InstrumentId", ...
            "i1Pro2", ...
            varargin{:});

    otherwise
        error( ...
            "SpectraLab:Drivers:UnknownInstrument", ...
            "ERROR [SPL-009]\n\n" + ...
            "Unknown instrument identifier: %s\n\n" + ...
            "What to do:\n" + ...
            "Use one of:\n" + ...
            "    i1Pro2\n" + ...
            "    i1Pro\n" + ...
            "    mock", ...
            requestedId);
end

end
