classdef SpotreadInstrument < spectralab.core.Instrument
    %SPOTREADINSTRUMENT  ArgyllCMS spotread-based instrument driver.
    %
    % ArgyllCMS spotread keeps calibration inside its own process.
    % Therefore calibration and measurement are performed together in one
    % manual-safe spotread session.

    properties
        InstrumentId (1,1) string = "i1Pro2"
        Executable (1,1) string = ""
        MeasurementKind (1,1) string = "emissive"
        MeasurementOptions (1,1) string = "-e -s"
        CalibrationOptions (1,1) string = "-e -s"
        TimeoutSeconds (1,1) double = 300
        PythonExecutable (1,1) string = ""
        AutomaticTrigger (1,1) string = "dialog"
        InstrumentSwitchSettleSeconds (1,1) double = 2
        HighResolution (1,1) logical = false
    end

    properties (Access = private)
        Runner
        OneShotRunner
        PlacementConfirmation = []
        OperationStartFeedback = []
        SerialNumber (1,1) string = ""
    end

    methods
        function obj = SpotreadInstrument(varargin)
            p = inputParser;

            addParameter( ...
                p, ...
                "InstrumentId", ...
                "i1Pro2", ...
                @(x) ischar(x) || isstring(x));

            addParameter( ...
                p, ...
                "Executable", ...
                "", ...
                @(x) ischar(x) || isstring(x));

            addParameter( ...
                p, ...
                "MeasurementOptions", ...
                "", ...
                @(x) ischar(x) || isstring(x));

            addParameter( ...
                p, ...
                "CalibrationOptions", ...
                "", ...
                @(x) ischar(x) || isstring(x));

            addParameter( ...
                p, ...
                "MeasurementKind", ...
                "emissive", ...
                @(x) any(lower(strtrim(string(x))) == ["emissive", "reflectance"]));

            addParameter( ...
                p, ...
                "TimeoutSeconds", ...
                300, ...
                @(x) isnumeric(x) && isscalar(x) && x > 0);

            addParameter( ...
                p, ...
                "PythonExecutable", ...
                "", ...
                @(x) ischar(x) || isstring(x));

            addParameter( ...
                p, ...
                "OneShotRunner", ...
                [], ...
                @(x) isempty(x) || isobject(x));

            addParameter( ...
                p, ...
                "PlacementConfirmation", ...
                [], ...
                @(x) isempty(x) || isa(x, "function_handle"));

            addParameter( ...
                p, ...
                "AutomaticTrigger", ...
                "dialog", ...
                @(x) any(lower(string(x)) == ["instrument", "dialog"]));

            addParameter( ...
                p, ...
                "InstrumentSwitchSettleSeconds", ...
                2, ...
                @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);

            addParameter( ...
                p, ...
                "HighResolution", ...
                false, ...
                @(x) islogical(x) && isscalar(x));

            parse(p, varargin{:});

            obj.InstrumentId = string(p.Results.InstrumentId);
            obj.Executable = string(p.Results.Executable);
            obj.MeasurementKind = lower(strtrim(string(p.Results.MeasurementKind)));
            obj.MeasurementOptions = resolveMeasurementOptions( ...
                obj.MeasurementKind, p.Results.MeasurementOptions);
            obj.CalibrationOptions = resolveMeasurementOptions( ...
                obj.MeasurementKind, p.Results.CalibrationOptions);
            obj.TimeoutSeconds = p.Results.TimeoutSeconds;
            obj.PythonExecutable = string(p.Results.PythonExecutable);
            obj.OneShotRunner = p.Results.OneShotRunner;
            obj.PlacementConfirmation = p.Results.PlacementConfirmation;
            obj.AutomaticTrigger = lower(string(p.Results.AutomaticTrigger));
            obj.InstrumentSwitchSettleSeconds = ...
                double(p.Results.InstrumentSwitchSettleSeconds);
            obj.HighResolution = p.Results.HighResolution;
        end

        function tf = synchronizesStartFeedback(~, mode)
            tf = lower(strtrim(string(mode))) == "automatic";
        end

        function setOperationStartFeedback(obj, callback)
            if ~isempty(callback) && ~isa(callback, "function_handle")
                error("SpectraLab:Spotread:InvalidStartFeedback", ...
                    "Operation start feedback must be a function handle.");
            end
            obj.OperationStartFeedback = callback;
        end

        function info = getInfo(obj)
            info = struct();

            % Physical instrument identity exposed to archives, reports,
            % sessions and other public SpectraLab interfaces.
            info.name = obj.InstrumentId;
            info.instrument_id = obj.InstrumentId;
            info.serial_number = obj.SerialNumber;

            % Implementation provenance. These fields describe how the
            % physical instrument is operated and are not its identity.
            info.driver = "spectralab.drivers.SpotreadInstrument";
            info.backend = "ArgyllCMS spotread";
            info.backend_mode = ...
                "interactive-fallback-and-bounded-one-shot";
            info.measurement_kind = obj.MeasurementKind;
            info.executable = obj.Executable;
            info.python_executable = obj.PythonExecutable;
            info.measurement_options = obj.MeasurementOptions;
            info.calibration_options = obj.CalibrationOptions;
            info.automatic_trigger = obj.AutomaticTrigger;
            info.instrument_switch_settle_seconds = ...
                obj.InstrumentSwitchSettleSeconds;
            info.high_resolution = obj.HighResolution;
            info.version = spectralab.version();
            info.is_open = obj.IsOpen;
        end

        function open(obj)
            if strlength(obj.Executable) == 0
                obj.Executable = ...
                    spectralab.drivers.spotread.findSpotread();
            end

            if strlength(obj.Executable) == 0
                error( ...
                    "SpectraLab:Spotread:NotFound", ...
                    "ERROR [SPL-005]\n\n" + ...
                    "ArgyllCMS spotread was not found.\n\n" + ...
                    "What to do:\n" + ...
                    "1. Install ArgyllCMS.\n" + ...
                    "2. Verify in a terminal that this works:\n\n" + ...
                    "    spotread -?\n\n" + ...
                    "3. Restart MATLAB and run:\n\n" + ...
                    "    startup\n\n" + ...
                    "Advanced option: pass the executable path with:\n" + ...
                    "    spectralab.drivers.createInstrument(" + ...
                    """i1Pro2"", ""Executable"", " + ...
                    """/path/to/spotread"")");
            end

            if strlength(obj.PythonExecutable) == 0
                obj.PythonExecutable = ...
                    spectralab.drivers.spotread.ManualSafeBridge.findPython();
            end

            if strlength(obj.PythonExecutable) == 0
                error( ...
                    "SpectraLab:Spotread:PythonNotFound", ...
                    "ERROR [SPL-003]\n\n" + ...
                    "Python 3 was not found.\n\n" + ...
                    "What to do:\n" + ...
                    "1. Install Python 3.\n" + ...
                    "2. Install pexpect in that Python environment.\n" + ...
                    "3. Restart MATLAB and run:\n\n" + ...
                    "    startup\n\n" + ...
                    "Advanced option: pass the executable path with:\n" + ...
                    "    spectralab.drivers.createInstrument(" + ...
                    """i1Pro2"", ""PythonExecutable"", " + ...
                    """/path/to/python3"")");
            end

            obj.Runner = ...
                spectralab.drivers.spotread.CommandRunner( ...
                    obj.Executable, ...
                    obj.TimeoutSeconds);

            if isempty(obj.OneShotRunner)
                obj.OneShotRunner = ...
                    spectralab.drivers.spotread.OneShotCommandRunner( ...
                        obj.Executable, ...
                        PythonExecutable=obj.PythonExecutable, ...
                        TimeoutSeconds=obj.TimeoutSeconds, ...
                        KeepArtifacts=true, ...
                        KeepStandardInputOpen=( ...
                            obj.AutomaticTrigger == "instrument"));
            end

            obj.IsOpen = true;
        end

        function close(obj)
            obj.IsOpen = false;
        end

        function tf = supportsInteractionMode(~, mode)
            tf = any(lower(strtrim(string(mode))) == ...
                ["interactive", "automatic"]);
        end

        function cal = calibrate(obj, mode)
            obj.requireOpen();

            if nargin < 2 || strlength(string(mode)) == 0
                mode = "interactive";
            end

            mode = lower(string(mode));
            if mode == "automatic"
                cal = obj.calibrateOneShot();
                return
            end

            if mode ~= "interactive"
                error( ...
                    "SpectraLab:Spotread:UnsupportedInteractionMode", ...
                    "ERROR [SPL-015]\n\n" + ...
                    "Automatic mode is currently not supported by " + ...
                    "SpotreadInstrument.\n\n" + ...
                    "What to do:\n" + ...
                    "Use interactive mode:\n\n" + ...
                    "    sess = sess.calibrate(" + ...
                    """Mode"", ""interactive"");");
            end

            data = struct();
            data.note = ...
                "spotread calibration is process-local and is " + ...
                "performed inside measure().";
            data.backend = "manual-safe-one-spotread-session";
            data.executable = obj.Executable;
            data.python_executable = obj.PythonExecutable;

            cal = spectralab.core.Calibration.valid( ...
                obj.getInfo(), ...
                "spotread-one-session-ready", ...
                "Ready; calibration will occur in measurement session.", ...
                data);

            obj.LastCalibration = cal;
        end

        function spec = measure(obj, label, mode)
            obj.requireOpen();
            obj.requireCalibration();

            if nargin < 2 || strlength(string(label)) == 0
                label = obj.InstrumentId + " spectrum";
            end

            if nargin < 3 || strlength(string(mode)) == 0
                mode = "interactive";
            end

            mode = lower(string(mode));
            if mode == "automatic"
                spec = obj.measureOneShot(label);
                return
            end

            if mode ~= "interactive"
                error( ...
                    "SpectraLab:Spotread:UnsupportedInteractionMode", ...
                    "ERROR [SPL-015]\n\n" + ...
                    "Automatic mode is currently not supported by " + ...
                    "SpotreadInstrument.\n\n" + ...
                    "What to do:\n" + ...
                    "Use interactive mode:\n\n" + ...
                    "    spec = sess.measure(" + ...
                    """LED spectrum"", ""Mode"", ""interactive"");");
            end

            r = ...
                spectralab.drivers.spotread.ManualSafeBridge.runMeasurement( ...
                    obj.PythonExecutable, ...
                    obj.Executable, ...
                    obj.MeasurementOptions, ...
                    obj.TimeoutSeconds);

            if r.status ~= 0
                if r.status == 26
                    error( ...
                        "SpectraLab:Spotread:UserInputBridgeTimeout", ...
                        "ERROR [SPL-013]\n\n" + ...
                        "SpectraLab waited for ENTER, but the Python " + ...
                        "bridge did not receive keyboard input.\n\n" + ...
                        "What to do:\n" + ...
                        "1. Click in the MATLAB Command Window.\n" + ...
                        "2. Run:\n\n" + ...
                        "    startup\n" + ...
                        "    measure_led\n\n" + ...
                        "3. When asked, press ENTER in the MATLAB " + ...
                        "Command Window.\n" + ...
                        "4. If the problem repeats, restart MATLAB " + ...
                        "and try again.");

                elseif r.status == 24
                    error( ...
                        "SpectraLab:Spotread:CommunicationsFailure", ...
                        "ERROR [SPL-006]\n\n" + ...
                        "spotread reported a communications failure.\n\n" + ...
                        "What to do:\n" + ...
                        "1. Check that the instrument is connected " + ...
                        "by USB.\n" + ...
                        "2. Close other software that may be using " + ...
                        "the instrument.\n" + ...
                        "3. Unplug and reconnect the instrument.\n" + ...
                        "4. Run in a terminal:\n\n" + ...
                        "    spotread -e\n\n" + ...
                        "Then restart MATLAB and run startup again.");

                else
                    error( ...
                        "SpectraLab:Spotread:BridgeFailed", ...
                        "ERROR [SPL-007]\n\n" + ...
                        "The spotread bridge failed with status %d.\n\n" + ...
                        "What to do:\n" + ...
                        "1. Run spectralab.status() and check Python, " + ...
                        "pexpect and spotread.\n" + ...
                        "2. If all checks are OK, run spotread manually " + ...
                        "in a terminal.\n" + ...
                        "3. See docs/TROUBLESHOOTING.md.", ...
                        r.status);
                end
            end

            rawFile = fullfile( ...
                tempdir, ...
                "spectralab_spotread_last_output.txt");

            if isfile(rawFile)
                rawOutput = string(fileread(rawFile));
            else
                rawOutput = r.output;
            end

            [wl, power, parseInfo] = ...
                spectralab.drivers.spotread.Parser.parseSpectrum( ...
                    rawOutput);

            metadata = struct();
            metadata.backend = ...
                "spotread-manual-safe-one-session";
            metadata.command = r.command;
            metadata.status = r.status;
            metadata.raw_output = rawOutput;
            metadata.raw_output_file = rawFile;
            metadata.parse_info = parseInfo;
            metadata.calibration_note = ...
                "White-reference calibration performed in same " + ...
                "spotread process.";
            metadata.measurement_kind = obj.MeasurementKind;
            metadata.signal_quantity = signalQuantity(obj.MeasurementKind);
            metadata.spotread_options = obj.MeasurementOptions;
            metadata.spotread_colorimetry = ...
                colorimetryMetadata(rawOutput, obj.MeasurementOptions);

            spec = spectralab.core.Spectrum( ...
                wl, ...
                power, ...
                label, ...
                obj.getInfo(), ...
                obj.LastCalibration.toStruct(), ...
                metadata, ...
                spectrumUnit(obj.MeasurementKind));
        end
    end

    methods (Access = private)
        function cal = calibrateOneShot(obj)
            obj.confirmPlacement(obj.calibrationPlacementMessage());

            args = splitOptions(obj.CalibrationOptions);
            if obj.HighResolution
                args(end + 1) = "-H";
            end
            args(end + 1:end + 2) = ["-O", "spectrum.sp"];
            result = obj.OneShotRunner.run(args);
            cleanup = onCleanup(@() cleanupWorkingDirectory(result));
            rawOutput = result.output + newline + result.error_output;
            obj.captureInstrumentIdentity(rawOutput);
            outcome = spectralab.drivers.spotread.OutcomeParser.classify( ...
                rawOutput, result.status, result.timed_out);

            if outcome.kind ~= "CALIBRATION_SUCCEEDED"
                error("SpectraLab:Spotread:OneShotCalibrationFailed", ...
                    "Spotread calibration did not succeed (%s): %s", ...
                    outcome.kind, outcome.message);
            end

            data = struct();
            data.backend = "spotread-bounded-one-shot";
            data.command = result.command;
            data.status = result.status;
            data.duration_seconds = result.duration_seconds;
            data.outcome = outcome.kind;
            data.calibration_was_required = ...
                outcome.calibration_was_required;
            data.high_resolution = obj.HighResolution;
            data.measurement_kind = obj.MeasurementKind;
            data.calibration_options = obj.CalibrationOptions;
            data.raw_output = rawOutput;

            cal = spectralab.core.Calibration.valid( ...
                obj.getInfo(), ...
                "spotread-one-shot-white-reference", ...
                "Spotread calibration completed successfully.", ...
                data);
            obj.LastCalibration = cal;
        end

        function spec = measureOneShot(obj, label, allowRecalibration)
            if nargin < 3
                allowRecalibration = true;
            end

            obj.confirmPlacement(obj.measurementPlacementMessage(label));

            if obj.AutomaticTrigger == "instrument" && ...
                    obj.InstrumentSwitchSettleSeconds > 0
                fprintf( ...
                    "Release the instrument button. Measurement will arm in %.1f seconds.\n", ...
                    obj.InstrumentSwitchSettleSeconds);
                pause(obj.InstrumentSwitchSettleSeconds);
                fprintf("Starting Spotread measurement; wait for READY.\n");
            end

            args = splitOptions(obj.MeasurementOptions);
            if obj.HighResolution
                args(end + 1) = "-H";
            end
            args(end + 1:end + 3) = ["-N", "-O", "spectrum.sp"];
            result = obj.OneShotRunner.run(args);
            cleanup = onCleanup(@() cleanupWorkingDirectory(result));
            rawOutput = result.output + newline + result.error_output;
            obj.captureInstrumentIdentity(rawOutput);
            outcome = spectralab.drivers.spotread.OutcomeParser.classify( ...
                rawOutput, result.status, result.timed_out);

            if outcome.kind == "CALIBRATION_REQUIRED" && allowRecalibration
                % The failed attempt contains no reportable spectrum. Remove
                % its temporary artifacts before asking the operator to move
                % the instrument to the white reference.
                clear cleanup
                fprintf( ...
                    "\nSpotread requires a new calibration. " + ...
                    "No measurement was saved.\n");
                obj.calibrateOneShot();
                spec = obj.measureOneShot(label, false);
                spec = spec.withMetadataField( ...
                    "automatic_recalibration", true);
                spec = spec.withMetadataField( ...
                    "recalibration_reason", outcome.kind);
                return
            end

            if outcome.kind ~= "MEASUREMENT_SUCCEEDED"
                throwMeasurementFailure(outcome);
            end

            [wl, power, parseInfo] = ...
                spectralab.drivers.spotread.Parser.parseSpectrum(rawOutput);
            spectrumFile = fullfile( ...
                result.working_directory, "spectrum.sp");
            [fileWl, filePower, fileInfo] = ...
                spectralab.drivers.spotread.Parser.parseSpectrumFile( ...
                    spectrumFile);
            validateMatchingSpectrum(wl, power, fileWl, filePower);
            validateReportableSignal( ...
                fileWl, filePower, rawOutput, obj.MeasurementKind);

            metadata = struct();
            metadata.backend = "spotread-bounded-one-shot";
            metadata.command = result.command;
            metadata.status = result.status;
            metadata.duration_seconds = result.duration_seconds;
            metadata.raw_output = rawOutput;
            metadata.parse_info = parseInfo;
            metadata.spectrum_file_info = fileInfo;
            metadata.spectrum_source = "spotread spectrum.sp";
            metadata.text_spectrum_samples = numel(wl);
            metadata.one_shot = true;
            metadata.high_resolution = any(args == "-H");
            metadata.skip_initial_calibration = any(args == "-N");
            metadata.calibration_outcome = ...
                obj.LastCalibration.Data.outcome;
            metadata.measurement_kind = obj.MeasurementKind;
            metadata.signal_quantity = signalQuantity(obj.MeasurementKind);
            metadata.spotread_options = obj.MeasurementOptions;
            metadata.spotread_colorimetry = ...
                colorimetryMetadata(rawOutput, obj.MeasurementOptions);

            spec = spectralab.core.Spectrum( ...
                fileWl, filePower, label, obj.getInfo(), ...
                obj.LastCalibration.toStruct(), metadata, ...
                spectrumUnit(obj.MeasurementKind));
        end

        function confirmPlacement(obj, message)
            if ~isempty(obj.PlacementConfirmation)
                obj.PlacementConfirmation(string(message));
                obj.notifyOperationStart();
                return
            end

            if obj.AutomaticTrigger == "instrument"
                obj.notifyOperationStart();
                fprintf("\nSpectraLab one-shot operation:\n%s\n", message);
                fprintf("Wait until Spotread reports READY before pressing the button.\n");
            else
                if usejava('desktop')
                    choice = questdlg( ...
                        char(message), ...
                        "SpectraLab one-shot operation", ...
                        "Continue", ...
                        "Cancel", ...
                        "Continue");
                    if ~strcmp(choice, "Continue")
                        error("SpectraLab:Spotread:OperationCancelled", ...
                            "The operator cancelled the Spotread operation.");
                    end
                    obj.notifyOperationStart();
                else
                    fprintf("\nSpectraLab one-shot operation:\n%s\n", message);
                    input("Press ENTER to continue, or Ctrl-C to abort: ", "s");
                    obj.notifyOperationStart();
                end
            end
        end

        function notifyOperationStart(obj)
            if ~isempty(obj.OperationStartFeedback)
                obj.OperationStartFeedback();
            end
        end

        function captureInstrumentIdentity(obj, rawOutput)
            serialNumber = extractSerialNumber(rawOutput);
            if strlength(serialNumber) > 0
                obj.SerialNumber = serialNumber;
            end
        end

        function message = calibrationPlacementMessage(obj)
            if strlength(obj.SerialNumber) > 0
                message = ...
                    "Place the instrument on its reflective white " + ...
                    "reference. Verify that the calibration plate is " + ...
                    "marked S/N " + obj.SerialNumber + ".";
            else
                message = ...
                    "Place the instrument on its reflective white " + ...
                    "reference. Verify that the calibration plate " + ...
                    "serial number matches the instrument.";
            end
        end

        function message = measurementPlacementMessage(obj, label)
            measurementIdentity = "Measurement " + string(label) + ". ";
            if obj.MeasurementKind == "reflectance"
                message = measurementIdentity + ...
                    "Place the instrument on the reflectance patch. " + ...
                    "Do not measure the white calibration reference.";
            else
                message = measurementIdentity + ...
                    "Place the instrument on the source or sample to be measured.";
            end
        end
    end
end

function options = splitOptions(value)
options = string(regexp(strtrim(char(value)), '\s+', 'split'));
options(strlength(options) == 0) = [];
if ~any(options == "-v")
    options = ["-v", options];
end
end

function options = resolveMeasurementOptions(kind, suppliedOptions)
kind = lower(strtrim(string(kind)));
options = strtrim(string(suppliedOptions));
if strlength(options) == 0
    if kind == "reflectance"
        options = "-s";
    else
        options = "-e -s";
    end
end

tokens = splitOptions(options);
if kind == "reflectance" && any(tokens == "-e")
    error("SpectraLab:Spotread:InvalidReflectanceOptions", ...
        "Reflectance measurements must not use the emissive -e option.");
end
if ~any(tokens == "-s")
    error("SpectraLab:Spotread:SpectrumRequired", ...
        "SpectraLab Spotread measurements require the -s spectrum option.");
end
end

function unit = spectrumUnit(kind)
if string(kind) == "reflectance"
    unit = "relative reflectance (%)";
else
    unit = "arbitrary";
end
end

function quantity = signalQuantity(kind)
if string(kind) == "reflectance"
    quantity = "spectral reflectance factor";
else
    quantity = "spectral power";
end
end

function colorimetry = colorimetryMetadata(rawOutput, options)
colorimetry = spectralab.drivers.spotread.Parser.parseColorimetry(rawOutput);
colorimetry.observer = observerFromOptions(options);
colorimetry.observer_source = "spotread option or documented default";
end

function observer = observerFromOptions(options)
tokens = splitOptions(options);
index = find(tokens == "-Q", 1, "last");
if isempty(index) || index == numel(tokens)
    observer = "1931_2";
else
    observer = tokens(index + 1);
end
end

function serialNumber = extractSerialNumber(rawOutput)
serialNumber = "";
text = char(string(rawOutput));

% ArgyllCMS verbose output uses "Serial Number:". Some i1Pro prompts use
% the shorter "S/N" form, so accept that only as a fallback.
tokens = regexp(text, ...
    '(?im)^\s*Serial\s+Number\s*:\s*([^\r\n]+)', ...
    'tokens', 'once');
if isempty(tokens)
    tokens = regexp(text, ...
        '(?im)reflective\s+white\s+reference\s+S/N\s+([^,\r\n]+)', ...
        'tokens', 'once');
end
if ~isempty(tokens)
    serialNumber = strtrim(string(tokens{1}));
end
end

function throwMeasurementFailure(outcome)
switch outcome.kind
    case "INSTRUMENT_NOT_DETECTED"
        identifier = "SpectraLab:Spotread:InstrumentNotDetected";
    case "COMMUNICATION_FAILURE"
        identifier = "SpectraLab:Spotread:CommunicationsFailure";
    case "TIMEOUT"
        identifier = "SpectraLab:Spotread:MeasurementTimeout";
    case "CALIBRATION_FAILED"
        identifier = "SpectraLab:Spotread:MeasurementCalibrationFailed";
    case "PROCESS_FAILED"
        identifier = "SpectraLab:Spotread:MeasurementProcessFailed";
    otherwise
        identifier = "SpectraLab:Spotread:OneShotMeasurementFailed";
end

error(identifier, ...
    "Spotread measurement did not succeed (%s): %s", ...
    outcome.kind, outcome.message);
end

function cleanupWorkingDirectory(result)
if isfield(result, "artifacts_retained") && ...
        result.artifacts_retained && ...
        isfolder(result.working_directory)
    rmdir(result.working_directory, "s");
end
end

function validateMatchingSpectrum(wl, power, fileWl, filePower)
gridTolerance = 1e-8;
sameGrid = numel(wl) == numel(fileWl) && ...
    all(abs(wl - fileWl) <= gridTolerance);
if sameGrid
    comparisonPower = filePower;
elseif fileWl(1) <= wl(1) + gridTolerance && ...
        fileWl(end) >= wl(end) - gridTolerance && ...
        numel(fileWl) >= numel(wl)
    % With Spotread -H, terminal output may retain the standard coarse
    % control grid while spectrum.sp contains the full high-resolution
    % grid. Compare values at the terminal wavelengths, but preserve the
    % file grid as the authoritative measurement.
    % The coarse terminal spectrum and the high-resolution file spectrum
    % are separate Spotread reconstructions. Their values are not required
    % to equal a linear interpolation. The file is the authoritative
    % primary measurement; range and signal validity are checked below.
    comparisonPower = [];
else
    error("SpectraLab:Spotread:SpectrumMismatch", ...
        "Spotread text and spectrum file use different wavelength grids.");
end
tolerance = max(1e-9, 1e-5 * max(abs(filePower)));
if sameGrid && (any(~isfinite(comparisonPower)) || ...
        any(abs(power - comparisonPower) > tolerance))
    error("SpectraLab:Spotread:SpectrumMismatch", ...
        "Spotread text and spectrum file contain different values.");
end
end

function validateReportableSignal(wl, power, rawOutput, measurementKind)
integratedPower = trapz(wl, power);
xyzToken = regexp(char(rawOutput), ...
    ['Result is XYZ:\s*' ...
     '([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s+' ...
     '([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s+' ...
     '([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)'], ...
    'tokens', 'once');
zeroXYZ = false;
if ~isempty(xyzToken)
    xyz = str2double(xyzToken);
    zeroXYZ = all(abs(xyz) <= 1e-12);
end

if max(power) <= 0 || integratedPower <= 0 || zeroXYZ
    if string(measurementKind) == "reflectance"
        message = ...
            "No usable reflectance signal was detected.\n\n" + ...
            "The instrument may still be on the calibration tile or " + ...
            "may not be positioned on the patch.\n\n" + ...
            "Move the instrument to the reflectance patch and run " + ...
            "the measurement again. No measurement was saved.";
    else
        message = ...
            "No usable light was detected.\n\n" + ...
            "The instrument may still be on the calibration tile, " + ...
            "the source may be off, or the sensor may not be aimed at " + ...
            "the source.\n\n" + ...
            "Move the instrument to the illuminated source or sample " + ...
            "and run the measurement again. No measurement was saved.";
    end
    if usejava('desktop')
        uiwait(errordlg(char(message), ...
            "SpectraLab - No light detected", "modal"));
    end
    error("SpectraLab:Spotread:NoLightDetected", "%s", message);
end
end
