function style = createReportStyle()
%CREATEREPORTSTYLE Create the canonical internal report presentation style.
%
% All dimensions are expressed in typographic points unless otherwise
% stated. The style contains presentation values only.

style = struct( ...
    "Format", "SLAB-REPORT-STYLE", ...
    "Version", "1.0", ...
    "Font", struct( ...
        "Name", "Helvetica"), ...
    "Box", struct( ...
        "WidthFraction", 0.62, ...
        "TitleHeight", 22, ...
        "TitleFontSize", 9, ...
        "TitleMargin", 6, ...
        "ContentPadding", 6, ...
        "CellMargin", 2, ...
        "BorderLineWidth", 0.75, ...
        "BorderColor", [0.25 0.25 0.25]), ...
    "ResultsTable", struct( ...
        "VerticalGap", 28, ...
        "RowHeight", 18, ...
        "SpaceAfter", 8, ...
        "LabelWidthFraction", 0.42, ...
        "FontSize", 9), ...
    "InformationBox", struct( ...
        "VerticalGap", 8, ...
        "RowHeight", 16, ...
        "SectionGap", 8, ...
        "BoxPadding", 12, ...
        "LabelWidthFraction", 0.38, ...
        "FontSize", 8), ...
    "Caption", struct( ...
        "FontSize", 9, ...
        "FontAngle", "italic"), ...
    "Text", struct( ...
        "FontName", "Helvetica", ...
        "HeadingFontSize", 16, ...
        "ParagraphFontSize", 10, ...
        "Margin", 0), ...
    "PageFrame", struct( ...
        "FontName", "Helvetica", ...
        "HeaderTitleFontSize", 12, ...
        "HeaderInformationFontSize", 8, ...
        "FooterFontSize", 7, ...
        "TextMargin", 0, ...
        "RuleOffset", 8, ...
        "RuleColor", [0.55 0.55 0.55], ...
        "RuleLineWidth", 0.5), ...
    "Figure", struct( ...
        "BottomPadding", 40, ...
        "TopPadding", 24));
end
