function registry = createAnalysisRegistry()
%CREATEANALYSISREGISTRY Create the canonical RP-020 analysis registry.
%
%   registry = spectralab.report.internal.createAnalysisRegistry()
%
% RP-020 assigns canonical report specifications to public AnalysisId
% values. The registry is data-only and contains no mutable state.
%
% The first registered report type is ANL-SPECTRUM, representing direct
% reporting of the measured spectrum stored in one SpectraLab archive.

registry = [ ...
    makeEntry( ...
        measuredSpectrumDefinition(), ...
        "Measurement", ...
        @runMeasuredSpectrum, ...
        @renderMeasuredSpectrum)
    makeEntry( ...
        criDefinition(), ...
        "Measurement", ...
        @runCri, ...
        @renderCriSpectrum)
    makeEntry( ...
        transmissionDefinition(), ...
        ["Reference", "Sample"], ...
        @runTransmission, ...
        @renderTransmission)
    makeEntry( ...
        opticalDensityDefinition(), ...
        ["Reference", "Sample"], ...
        @runOpticalDensity, ...
        @renderOpticalDensity)
    makeEntry( ...
        whiteDensityDefinition(), ...
        ["Reference", "Sample"], ...
        @runWhiteDensity, ...
        [])
    makeEntry( ...
        statusADensityDefinition(), ...
        ["Reference", "Sample"], ...
        @runStatusADensity, ...
        [])
    makeEntry( ...
        statusMDensityDefinition(), ...
        ["Reference", "Sample"], ...
        @runStatusMDensity, ...
        [])
    makeEntry( ...
        isoVisualDensityDefinition(), ...
        ["Reference", "Sample"], ...
        @runIsoVisualDensity, ...
        [])];

validateRegistry(registry);
end

function entry = makeEntry( ...
        analysisDefinition, inputRoles, runner, figureRenderer)

entry = struct( ...
    "AnalysisDefinition", analysisDefinition, ...
    "InputRoles", reshape(string(inputRoles), 1, []), ...
    "AnalysisRunner", runner, ...
    "FigureRenderer", figureRenderer);
end

function validateRegistry(registry)
%VALIDATEREGISTRY Validate the canonical registry contract.

required = [ ...
    "AnalysisDefinition"
    "InputRoles"
    "AnalysisRunner"
    "FigureRenderer"];

if ~isstruct(registry) || isempty(registry)
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "Analysis registry must be a non-empty structure array.");
end

for fieldName = required.'
    if ~isfield(registry, fieldName)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "Analysis registry is missing required field '%s'.", ...
            fieldName);
    end
end

analysisIds = strings(1, numel(registry));

for k = 1:numel(registry)
    analysisIds(k) = registry(k).AnalysisDefinition.AnalysisId;
end

if numel(unique(analysisIds)) ~= numel(analysisIds)
    error("SpectraLab:Report:DuplicateAnalysisId", ...
        "Analysis registry contains duplicate AnalysisId values.");
end

for k = 1:numel(registry)
    entry = registry(k);

    validateDefinition(entry.AnalysisDefinition);

    if ~isstring(entry.InputRoles) || ...
            isempty(entry.InputRoles) || ...
            ~isrow(entry.InputRoles) || ...
            any(ismissing(entry.InputRoles)) || ...
            any(strlength(strtrim(entry.InputRoles)) == 0) || ...
            numel(unique(entry.InputRoles)) ~= numel(entry.InputRoles)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "Each registry InputRoles value must be a unique non-empty string row vector.");
    end

    if ~isa(entry.AnalysisRunner, "function_handle")
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "Registry field 'AnalysisRunner' must be a function handle.");
    end

    if entry.AnalysisDefinition.HasFigure
        if ~isa(entry.FigureRenderer, "function_handle")
            error("SpectraLab:Report:InvalidAnalysisRegistry", ...
                "A figure-producing analysis requires a FigureRenderer.");
        end
    elseif ~isempty(entry.FigureRenderer)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "A figureless analysis must not define a FigureRenderer.");
    end
end
end

function validateDefinition(definition)
%VALIDATEDEFINITION Validate one authoritative analysis definition.

required = [ ...
    "AnalysisId"
    "Name"
    "Description"
    "Method"
    "Standard"
    "DefinitionVersion"
    "HasFigure"
    "ResultFields"];

if ~isstruct(definition) || ~isscalar(definition)
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "Each AnalysisDefinition must be a scalar structure.");
end

for fieldName = required.'
    if ~isfield(definition, fieldName)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "AnalysisDefinition is missing required field '%s'.", ...
            fieldName);
    end
end

textFields = [ ...
    "AnalysisId"
    "Name"
    "Description"
    "Method"
    "Standard"
    "DefinitionVersion"];

for fieldName = textFields.'
    value = definition.(fieldName);
    if ~isstring(value) || ~isscalar(value) || ...
            ismissing(value) || strlength(strtrim(value)) == 0
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "AnalysisDefinition.%s must be non-empty scalar text.", ...
            fieldName);
    end
end

if ~islogical(definition.HasFigure) || ~isscalar(definition.HasFigure)
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "AnalysisDefinition.HasFigure must be a logical scalar.");
end

if ~isstruct(definition.ResultFields) || isempty(definition.ResultFields)
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "AnalysisDefinition.ResultFields must be a non-empty structure array.");
end

requiredResultFields = ["Field", "Label", "Unit", "Format"];
for fieldName = requiredResultFields
    if ~isfield(definition.ResultFields, fieldName)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "AnalysisDefinition.ResultFields is missing field '%s'.", ...
            fieldName);
    end
end

for k = 1:numel(definition.ResultFields)
    resultFieldDefinition = definition.ResultFields(k);

    nonEmptyFields = ["Field", "Label", "Format"];
    for fieldName = nonEmptyFields
        value = resultFieldDefinition.(fieldName);
        if ~isstring(value) || ~isscalar(value) || ...
                ismissing(value) || strlength(strtrim(value)) == 0
            error("SpectraLab:Report:InvalidAnalysisRegistry", ...
                "ResultFields.%s must be non-empty scalar text.", ...
                fieldName);
        end
    end

    if ~isstring(resultFieldDefinition.Unit) || ...
            ~isscalar(resultFieldDefinition.Unit) || ...
            ismissing(resultFieldDefinition.Unit)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "ResultFields.Unit must be scalar text.");
    end
end

resultFieldNames = [definition.ResultFields.Field];
if numel(unique(resultFieldNames)) ~= numel(resultFieldNames)
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "AnalysisDefinition.ResultFields contains duplicate Field values.");
end

hasFigureDefinition = isfield(definition, "FigureDefinition");
if definition.HasFigure ~= hasFigureDefinition
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "HasFigure and FigureDefinition must describe the same figure contract.");
end

if definition.HasFigure
    figureDefinition = definition.FigureDefinition;
    requiredFigureFields = [ ...
        "AspectRatio"
        "WidthFraction"
        "MaxHeight"
        "Caption"];

    if ~isstruct(figureDefinition) || ~isscalar(figureDefinition)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "FigureDefinition must be a scalar structure.");
    end

    for fieldName = requiredFigureFields.'
        if ~isfield(figureDefinition, fieldName)
            error("SpectraLab:Report:InvalidAnalysisRegistry", ...
                "FigureDefinition is missing field '%s'.", fieldName);
        end
    end

    numericValues = [ ...
        figureDefinition.AspectRatio
        figureDefinition.WidthFraction
        figureDefinition.MaxHeight];

    if ~isnumeric(numericValues) || ...
            any(~isfinite(numericValues)) || any(numericValues <= 0)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "FigureDefinition dimensions must be positive finite numbers.");
    end

    if ~isstring(figureDefinition.Caption) || ...
            ~isscalar(figureDefinition.Caption) || ...
            ismissing(figureDefinition.Caption) || ...
            strlength(strtrim(figureDefinition.Caption)) == 0
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "FigureDefinition.Caption must be non-empty scalar text.");
    end
end
end

function result = runMeasuredSpectrum(archive)
%RUNMEASUREDSPECTRUM Return report data for primary archived measurement.

result = struct( ...
    "SampleCount", numel(archive.Measurement.Wavelength), ...
    "WavelengthMinimum", min(archive.Measurement.Wavelength), ...
    "WavelengthMaximum", max(archive.Measurement.Wavelength));
end

function renderMeasuredSpectrum(ax, archive, ~)
%RENDERMEASUREDSPECTRUM Render the archived spectrum.

spec = spectralab.archive.restore(archive);

spectralab.plot.spectrum( ...
    spec, ...
    Parent=ax, ...
    Title="Measured spectral power distribution", ...
    Normalize=false, ...
    DisplayName=spec.Label, ...
    ShowSummary=true, ...
    SummaryLocation="east", ...
    ShowSpectralColorBar=true);

legend(ax, "Location", "northeast", "Interpreter", "none");
end

function result = runIsoVisualDensity(referenceArchive, sampleArchive)
%RUNISOVISUALDENSITY Run canonical ISO visual density analysis.

reference = spectralab.archive.restore(referenceArchive);
sample = spectralab.archive.restore(sampleArchive);

analysis = spectralab.analysis.isoVisualDensity( ...
    reference, ...
    sample, ...
    Resample=false);

result = struct( ...
    "Density", analysis.Density, ...
    "Transmittance", analysis.Transmittance);
end

function definition = isoVisualDensityDefinition()
%ISOVISUALDENSITYDEFINITION Return the canonical ANL-007 report definition.

definition = struct( ...
    "AnalysisId", "ANL-007", ...
    "Name", "ISO Visual Density", ...
    "Description", ...
        "ISO visual transmission density from reference and sample archives", ...
    "Method", "ISO visual weighted optical density", ...
    "Standard", "ISO visual: illuminant A × V(lambda)", ...
    "DefinitionVersion", "1", ...
    "HasFigure", false, ...
    "ResultFields", [ ...
        resultField("Density", "ISO visual density", "", "%.4f")
        resultField("Transmittance", "Effective transmittance", "", "%.6f")]);
end

function result = runStatusMDensity(referenceArchive, sampleArchive)
%RUNSTATUSMDENSITY Run canonical Status M RGB density analysis.

reference = spectralab.archive.restore(referenceArchive);
sample = spectralab.archive.restore(sampleArchive);

analysis = spectralab.analysis.statusMDensity( ...
    reference, ...
    sample, ...
    Resample=false);

result = struct( ...
    "RedDensity", analysis.DensityRGB(1), ...
    "GreenDensity", analysis.DensityRGB(2), ...
    "BlueDensity", analysis.DensityRGB(3), ...
    "RedTransmittance", analysis.TransmittanceRGB(1), ...
    "GreenTransmittance", analysis.TransmittanceRGB(2), ...
    "BlueTransmittance", analysis.TransmittanceRGB(3));
end

function definition = statusMDensityDefinition()
%STATUSMDENSITYDEFINITION Return the canonical ANL-008 report definition.

definition = struct( ...
    "AnalysisId", "ANL-008", ...
    "Name", "Status M Density", ...
    "Description", ...
        "Status M red, green, and blue densities from reference and sample archives", ...
    "Method", "Status M weighted optical density", ...
    "Standard", "ISO Status M", ...
    "DefinitionVersion", "1", ...
    "HasFigure", false, ...
    "ResultFields", [ ...
        resultField("RedDensity", "Red density", "", "%.4f")
        resultField("GreenDensity", "Green density", "", "%.4f")
        resultField("BlueDensity", "Blue density", "", "%.4f")
        resultField("RedTransmittance", "Red transmittance", "", "%.6f")
        resultField("GreenTransmittance", "Green transmittance", "", "%.6f")
        resultField("BlueTransmittance", "Blue transmittance", "", "%.6f")]);
end

function result = runStatusADensity(referenceArchive, sampleArchive)
%RUNSTATUSADENSITY Run canonical Status A RGB density analysis.

reference = spectralab.archive.restore(referenceArchive);
sample = spectralab.archive.restore(sampleArchive);

analysis = spectralab.analysis.statusADensity( ...
    reference, ...
    sample, ...
    Resample=false);

result = struct( ...
    "RedDensity", analysis.DensityRGB(1), ...
    "GreenDensity", analysis.DensityRGB(2), ...
    "BlueDensity", analysis.DensityRGB(3), ...
    "RedTransmittance", analysis.TransmittanceRGB(1), ...
    "GreenTransmittance", analysis.TransmittanceRGB(2), ...
    "BlueTransmittance", analysis.TransmittanceRGB(3));
end

function definition = statusADensityDefinition()
%STATUSADENSITYDEFINITION Return the canonical ANL-005 report definition.

definition = struct( ...
    "AnalysisId", "ANL-005", ...
    "Name", "Status A Density", ...
    "Description", ...
        "Status A red, green, and blue densities from reference and sample archives", ...
    "Method", "Status A weighted optical density", ...
    "Standard", "ISO Status A", ...
    "DefinitionVersion", "1", ...
    "HasFigure", false, ...
    "ResultFields", [ ...
        resultField("RedDensity", "Red density", "", "%.4f")
        resultField("GreenDensity", "Green density", "", "%.4f")
        resultField("BlueDensity", "Blue density", "", "%.4f")
        resultField("RedTransmittance", "Red transmittance", "", "%.6f")
        resultField("GreenTransmittance", "Green transmittance", "", "%.6f")
        resultField("BlueTransmittance", "Blue transmittance", "", "%.6f")]);
end

function result = runWhiteDensity(referenceArchive, sampleArchive)
%RUNWHITEDENSITY Run canonical photopically weighted white density.

reference = spectralab.archive.restore(referenceArchive);
sample = spectralab.archive.restore(sampleArchive);

analysis = spectralab.analysis.whiteDensity( ...
    reference, ...
    sample, ...
    Resample=false);

result = struct( ...
    "Density", analysis.Density, ...
    "Transmittance", analysis.Transmittance);
end

function definition = whiteDensityDefinition()
%WHITEDENSITYDEFINITION Return the canonical ANL-004 report definition.

definition = struct( ...
    "AnalysisId", "ANL-004", ...
    "Name", "White Density", ...
    "Description", ...
        "Photopically weighted visual density from reference and sample archives", ...
    "Method", "Photopically weighted optical density", ...
    "Standard", "CIE photopic V(lambda)", ...
    "DefinitionVersion", "1", ...
    "HasFigure", false, ...
    "ResultFields", [ ...
        resultField("Density", "White density", "", "%.4f")
        resultField("Transmittance", "Effective transmittance", "", "%.6f")]);
end

function result = runOpticalDensity(referenceArchive, sampleArchive)
%RUNOPTICALDENSITY Run canonical spectral optical-density analysis.

transmissionAnalysis = spectralab.analysis.transmission( ...
    referenceArchive, ...
    sampleArchive, ...
    Resample=false, ...
    WarnAboveOne=false);

wavelength = transmissionAnalysis.Result.WavelengthNm(:);
transmission = transmissionAnalysis.Result.Value(:);
density = spectralab.analysis.opticalDensity(transmission);

result = struct( ...
    "SampleCount", numel(wavelength), ...
    "WavelengthMinimum", wavelength(1), ...
    "WavelengthMaximum", wavelength(end), ...
    "MeanDensity", mean(density), ...
    "WavelengthNm", wavelength, ...
    "Density", density, ...
    "TransmissionAnalysis", transmissionAnalysis);
end

function renderOpticalDensity(ax, ~, ~, result)
%RENDEROPTICALDENSITY Render the canonical optical-density spectrum.

spectralab.plot.opticalDensity( ...
    result.WavelengthNm, ...
    result.Density, ...
    Parent=ax, ...
    Title="Optical density spectrum", ...
    ShowGrid=true);
end

function definition = opticalDensityDefinition()
%OPTICALDENSITYDEFINITION Return the canonical ANL-002 report definition.

definition = struct( ...
    "AnalysisId", "ANL-002", ...
    "Name", "Optical Density", ...
    "Description", ...
        "Spectral optical density from reference and sample archives", ...
    "Method", "Negative base-10 logarithm of spectral transmission", ...
    "Standard", "SpectraLab ANL-002", ...
    "DefinitionVersion", "1", ...
    "HasFigure", true, ...
    "ResultFields", [ ...
        resultField("SampleCount", "Samples", "", "%.0f")
        resultField("WavelengthMinimum", "Minimum wavelength", "nm", "%.0f")
        resultField("WavelengthMaximum", "Maximum wavelength", "nm", "%.0f")
        resultField("MeanDensity", "Mean optical density", "", "%.4f")], ...
    "FigureDefinition", struct( ...
        "AspectRatio", 3/2, ...
        "WidthFraction", 0.82, ...
        "MaxHeight", 260, ...
        "Caption", ...
            "Spectral optical density calculated from sample and reference archives."));
end

function result = runTransmission(referenceArchive, sampleArchive)
%RUNTRANSMISSION Run canonical spectral transmission analysis.

analysis = spectralab.analysis.transmission( ...
    referenceArchive, ...
    sampleArchive, ...
    Resample=false, ...
    WarnAboveOne=false);

wavelength = analysis.Result.WavelengthNm(:);
transmission = analysis.Result.Value(:);

result = struct( ...
    "SampleCount", numel(wavelength), ...
    "WavelengthMinimum", wavelength(1), ...
    "WavelengthMaximum", wavelength(end), ...
    "MeanTransmission", mean(transmission), ...
    "TransmissionAnalysis", analysis);
end

function renderTransmission(ax, ~, ~, result)
%RENDERTRANSMISSION Render the canonical transmission result.

spectralab.plot.transmission( ...
    result.TransmissionAnalysis, ...
    Parent=ax, ...
    Title="Transmission spectrum", ...
    ShowGrid=true);
end

function definition = transmissionDefinition()
%TRANSMISSIONDEFINITION Return the canonical ANL-001 report definition.

definition = struct( ...
    "AnalysisId", "ANL-001", ...
    "Name", "Transmission", ...
    "Description", ...
        "Spectral transmission from reference and sample archives", ...
    "Method", "Sample/reference spectral ratio", ...
    "Standard", "SpectraLab ANL-001", ...
    "DefinitionVersion", "1", ...
    "HasFigure", true, ...
    "ResultFields", [ ...
        resultField("SampleCount", "Samples", "", "%.0f")
        resultField("WavelengthMinimum", "Minimum wavelength", "nm", "%.0f")
        resultField("WavelengthMaximum", "Maximum wavelength", "nm", "%.0f")
        resultField("MeanTransmission", "Mean transmission", "", "%.4f")], ...
    "FigureDefinition", struct( ...
        "AspectRatio", 3/2, ...
        "WidthFraction", 0.82, ...
        "MaxHeight", 260, ...
        "Caption", ...
            "Spectral transmission calculated from sample and reference archives."));
end

function result = runCri(archive)
%RUNCRI Run CIE 13.3 CRI from one archived spectrum.

spec = spectralab.archive.restore(archive);
analysis = spectralab.analysis.cri(spec, Quiet=true);

if ~isfield(analysis, "Result") || ...
        ~isfield(analysis.Result, "CCT") || ...
        ~isfield(analysis.Result, "Duv") || ...
        ~isfield(analysis.Result, "Ra")
    error("SpectraLab:Report:InvalidAnalysisResult", ...
        "CRI analysis did not return Result.CCT, Result.Duv, and Result.Ra.");
end

result = struct( ...
    "CCT", analysis.Result.CCT, ...
    "Duv", analysis.Result.Duv, ...
    "Ra", analysis.Result.Ra);
end

function renderCriSpectrum(ax, archive, ~)
%RENDERCRISPECTRUM Render the measured spectrum used for CRI.

spec = spectralab.archive.restore(archive);

spectralab.plot.spectrum( ...
    spec, ...
    Parent=ax, ...
    Title="Measured spectral power distribution", ...
    Normalize=true, ...
    DisplayName=spec.Label, ...
    ShowSummary=true, ...
    SummaryLocation="east", ...
    ShowSpectralColorBar=true);

legend(ax, "Location", "northeast", "Interpreter", "none");
end

function definition = criDefinition()
%CRIDEFINITION Return the canonical CRI report definition.

definition = struct( ...
    "AnalysisId", "ANL-CRI", ...
    "Name", "Color Rendering Index", ...
    "Description", ...
        "CIE 13.3 color rendering analysis of archived spectral data", ...
    "Method", "CIE 13.3", ...
    "Standard", "CIE 13.3-1995", ...
    "DefinitionVersion", "1", ...
    "HasFigure", true, ...
    "ResultFields", [ ...
        resultField("CCT", "CCT", "K", "%.0f")
        resultField("Duv", "Duv", "", "%+.5f")
        resultField("Ra", "Ra", "", "%.1f")], ...
    "FigureDefinition", struct( ...
        "AspectRatio", 3/2, ...
        "WidthFraction", 0.82, ...
        "MaxHeight", 260, ...
        "Caption", ...
            "Measured spectral power distribution used for CIE 13.3 analysis."));
end

function definition = measuredSpectrumDefinition()
%MEASUREDSPECTRUMDEFINITION Return the canonical report definition.

definition = struct( ...
    "AnalysisId", "ANL-SPECTRUM", ...
    "Name", "Measured Spectrum", ...
    "Description", ...
        "Direct report of archived spectral measurement data", ...
    "Method", "Direct archived spectral measurement", ...
    "Standard", "SpectraLab archive measurement", ...
    "DefinitionVersion", "1", ...
    "HasFigure", true, ...
    "ResultFields", [ ...
        resultField( ...
            "SampleCount", "Samples", "", "%.0f")
        resultField( ...
            "WavelengthMinimum", "Minimum wavelength", "nm", "%.0f")
        resultField( ...
            "WavelengthMaximum", "Maximum wavelength", "nm", "%.0f")], ...
    "FigureDefinition", struct( ...
        "AspectRatio", 3/2, ...
        "WidthFraction", 0.82, ...
        "MaxHeight", 260, ...
        "Caption", ...
            "Measured spectral power distribution from the source archive."));
end

function value = resultField(fieldName, label, unit, format)

value = struct( ...
    "Field", string(fieldName), ...
    "Label", string(label), ...
    "Unit", string(unit), ...
    "Format", string(format));
end
