function style = createReportStyle()
%CREATEREPORTSTYLE Create the canonical internal report presentation style.
%
% All dimensions are expressed in typographic points unless otherwise
% stated. The style contains presentation values only.

style = struct( ...
    "Format", "SLAB-REPORT-STYLE", ...
    "Version", "1.0", ...
    "Appearance", struct( ...
        "BackgroundColor", "white", ...
        "BoxBorderColor", [0.40 0.40 0.40], ...
        "BoxBorderLineWidth", 0.50, ...
        "PageFrameRuleColor", [0.55 0.55 0.55], ...
        "PageFrameRuleLineWidth", 0.5), ...
    "Font", struct( ...
        "Name", "Helvetica", ...
        "WeightNormal", "normal", ...
        "WeightBold", "bold", ...
        "AngleItalic", "italic"), ...
    "Box", struct( ...
        "WidthFraction", 0.70, ...
        "TitleHeight", 22, ...
        "TitleFontSize", 9, ...
        "TitleMargin", 8, ...
        "ContentPadding", 8, ...
        "CellMargin", 2), ...
    "ResultsTable", struct( ...
        "VerticalGap", 32, ...
        "RowHeight", 18, ...
        "SpaceAfter", 8, ...
        "LabelWidthFraction", 0.42, ...
        "ProvenanceWidthFraction", 0.82, ...
        "FontSize", 9), ...
    "InformationBox", struct( ...
        "VerticalGap", 12, ...
        "RowHeight", 16, ...
        "SectionGap", 8, ...
        "BoxPadding", 12, ...
        "LabelWidthFraction", 0.38, ...
        "FontSize", 8), ...
    "Caption", struct( ...
        "FontSize", 9, ...
        "Margin", 0), ...
    "Text", struct( ...
        "HeadingFontSize", 16, ...
        "ParagraphFontSize", 10, ...
        "Margin", 0), ...
    "PageFrame", struct( ...
        "HeaderTitleFontSize", 15, ...
        "HeaderInformationFontSize", 8, ...
        "FooterFontSize", 7, ...
        "TextMargin", 0, ...
        "RuleOffset", 8), ...
    "Figure", struct( ...
        "BottomPadding", 46, ...
        "TopPadding", 30));
end
