function layout = createLayoutState()
%CREATELAYOUTSTATE Create deterministic A4 portrait layout geometry.
%
% Layout dimensions are expressed in typographic points (1/72 inch).
% RP-007 uses deterministic text estimates and does not depend on MATLAB
% Graphics, installed fonts, screen resolution, or operating system.

pageWidth = 595.276;
pageHeight = 841.890;
margin = 56.693; % 20 mm

layout = struct( ...
    "Units", "points", ...
    "PageWidth", pageWidth, ...
    "PageHeight", pageHeight, ...
    "MarginTop", margin, ...
    "MarginRight", margin, ...
    "MarginBottom", margin, ...
    "MarginLeft", margin, ...
    "ContentWidth", pageWidth - 2 * margin, ...
    "ContentHeight", pageHeight - 2 * margin, ...
    "CurrentPage", 1, ...
    "CursorY", 0);
end
