function registry = createAnalysisRegistry()
%CREATEANALYSISREGISTRY Create the canonical RP-020 analysis registry.
%
%   registry = spectralab.report.internal.createAnalysisRegistry()
%
% RP-020 assigns canonical report specifications to public AnalysisId
% values. The registry is data-only and contains no mutable state.
%
% The first registered report type is ANL-SPECTRUM, representing direct
% reporting of the measured spectrum stored in one SpectraLab archive.

registry = [ ...
    makeEntry( ...
        "ANL-SPECTRUM", ...
        "Measured Spectrum", ...
        "Direct report of archived spectral measurement data", ...
        @runMeasuredSpectrum, ...
        @renderMeasuredSpectrum, ...
        @measuredSpectrumDefinition)
    makeEntry( ...
        "ANL-CRI", ...
        "Color Rendering Index", ...
        "CIE 13.3 color rendering analysis of archived spectral data", ...
        @runCri, ...
        @renderCriSpectrum, ...
        @criDefinition)];

validateRegistry(registry);
end

function entry = makeEntry( ...
        analysisId, name, description, runner, figureRenderer, ...
        definitionFactory)

entry = struct( ...
    "AnalysisId", string(analysisId), ...
    "Name", string(name), ...
    "Description", string(description), ...
    "AnalysisRunner", runner, ...
    "FigureRenderer", figureRenderer, ...
    "DefinitionFactory", definitionFactory);
end

function validateRegistry(registry)
%VALIDATEREGISTRY Validate the canonical registry contract.

required = [ ...
    "AnalysisId"
    "Name"
    "Description"
    "AnalysisRunner"
    "FigureRenderer"
    "DefinitionFactory"];

if ~isstruct(registry) || isempty(registry)
    error("SpectraLab:Report:InvalidAnalysisRegistry", ...
        "Analysis registry must be a non-empty structure array.");
end

for fieldName = required.'
    if ~isfield(registry, fieldName)
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "Analysis registry is missing required field '%s'.", ...
            fieldName);
    end
end

analysisIds = [registry.AnalysisId];

if numel(unique(analysisIds)) ~= numel(analysisIds)
    error("SpectraLab:Report:DuplicateAnalysisId", ...
        "Analysis registry contains duplicate AnalysisId values.");
end

for k = 1:numel(registry)
    entry = registry(k);

    if ~isstring(entry.AnalysisId) || ...
            ~isscalar(entry.AnalysisId) || ...
            strlength(strtrim(entry.AnalysisId)) == 0
        error("SpectraLab:Report:InvalidAnalysisRegistry", ...
            "Each registry AnalysisId must be a non-empty string scalar.");
    end

    functionFields = [ ...
        "AnalysisRunner"
        "FigureRenderer"
        "DefinitionFactory"];

    for fieldName = functionFields.'
        if ~isa(entry.(fieldName), "function_handle")
            error("SpectraLab:Report:InvalidAnalysisRegistry", ...
                "Registry field '%s' must be a function handle.", ...
                fieldName);
        end
    end
end
end

function result = runMeasuredSpectrum(archive)
%RUNMEASUREDSPECTRUM Return report data for primary archived measurement.

result = struct( ...
    "SampleCount", numel(archive.Measurement.Wavelength), ...
    "WavelengthMinimum", min(archive.Measurement.Wavelength), ...
    "WavelengthMaximum", max(archive.Measurement.Wavelength));
end

function renderMeasuredSpectrum(ax, archive, ~)
%RENDERMEASUREDSPECTRUM Render the archived spectrum.

spec = spectralab.archive.restore(archive);

spectralab.plot.spectrum( ...
    spec, ...
    Parent=ax, ...
    Title="Measured spectral power distribution", ...
    Normalize=false, ...
    ShowSummary=false, ...
    ShowSpectralColorBar=true);
end

function result = runCri(archive)
%RUNCRI Run CIE 13.3 CRI from one archived spectrum.

spec = spectralab.archive.restore(archive);
analysis = spectralab.analysis.cri(spec, Quiet=true);

if ~isfield(analysis, "Result") || ...
        ~isfield(analysis.Result, "CCT") || ...
        ~isfield(analysis.Result, "Duv") || ...
        ~isfield(analysis.Result, "Ra")
    error("SpectraLab:Report:InvalidAnalysisResult", ...
        "CRI analysis did not return Result.CCT, Result.Duv, and Result.Ra.");
end

result = struct( ...
    "CCT", analysis.Result.CCT, ...
    "Duv", analysis.Result.Duv, ...
    "Ra", analysis.Result.Ra);
end

function renderCriSpectrum(ax, archive, ~)
%RENDERCRISPECTRUM Render the measured spectrum used for CRI.

spec = spectralab.archive.restore(archive);

spectralab.plot.spectrum( ...
    spec, ...
    Parent=ax, ...
    Title="Measured spectral power distribution", ...
    Normalize=true, ...
    ShowSummary=false, ...
    ShowSpectralColorBar=true);
end

function definition = criDefinition()
%CRIDEFINITION Return the canonical CRI report definition.

definition = struct( ...
    "AnalysisId", "ANL-CRI", ...
    "Name", "Color Rendering Index", ...
    "Method", "CIE 13.3", ...
    "Standard", "CIE 13.3-1995", ...
    "DefinitionVersion", "1", ...
    "HasFigure", true, ...
    "ResultFields", [ ...
        resultField("CCT", "CCT", "K", "%.0f")
        resultField("Duv", "Duv", "", "%+.5f")
        resultField("Ra", "Ra", "", "%.1f")], ...
    "FigureDefinition", struct( ...
        "AspectRatio", 3/2, ...
        "WidthFraction", 0.82, ...
        "MaxHeight", 260, ...
        "Caption", ...
            "Measured spectral power distribution used for CIE 13.3 analysis."));
end

function definition = measuredSpectrumDefinition()
%MEASUREDSPECTRUMDEFINITION Return the canonical report definition.

definition = struct( ...
    "AnalysisId", "ANL-SPECTRUM", ...
    "Name", "Measured Spectrum", ...
    "Method", "Direct archived spectral measurement", ...
    "Standard", "SpectraLab archive measurement", ...
    "DefinitionVersion", "1", ...
    "HasFigure", true, ...
    "ResultFields", [ ...
        resultField( ...
            "SampleCount", "Samples", "", "%.0f")
        resultField( ...
            "WavelengthMinimum", "Minimum wavelength", "nm", "%.0f")
        resultField( ...
            "WavelengthMaximum", "Maximum wavelength", "nm", "%.0f")], ...
    "FigureDefinition", struct( ...
        "AspectRatio", 3/2, ...
        "WidthFraction", 0.82, ...
        "MaxHeight", 260, ...
        "Caption", ...
            "Measured spectral power distribution from the source archive."));
end

function value = resultField(fieldName, label, unit, format)

value = struct( ...
    "Field", string(fieldName), ...
    "Label", string(label), ...
    "Unit", string(unit), ...
    "Format", string(format));
end
