function height = estimateInformationBoxHeight(model)
%ESTIMATEINFORMATIONBOXHEIGHT Deterministic InformationBox height.

arguments
    model (1,1) struct
end

if ~isfield(model, "MetadataRows") || ...
        ~isfield(model, "ResultRows") || ...
        ~isstruct(model.MetadataRows) || ...
        ~isstruct(model.ResultRows)
    error("SpectraLab:Report:InvalidInformationBox", ...
        "InformationBox must contain MetadataRows and ResultRows.");
end

style = spectralab.report.internal.createReportStyle();

height = style.Box.TitleHeight + ...
    style.InformationBox.BoxPadding + ...
    numel(model.MetadataRows) * style.InformationBox.RowHeight + ...
    style.InformationBox.SectionGap + ...
    numel(model.ResultRows) * style.InformationBox.RowHeight + ...
    style.InformationBox.BoxPadding;
end
