function height = estimateInformationBoxHeight(model)
%ESTIMATEINFORMATIONBOXHEIGHT Deterministic InformationBox height.

arguments
    model (1,1) struct
end

if ~isfield(model, "MeasurementInformationRows") || ...
        ~isfield(model, "ResultRows") || ...
        ~isstruct(model.MeasurementInformationRows) || ...
        ~isstruct(model.ResultRows)
    error("SpectraLab:Report:InvalidInformationBox", ...
        "InformationBox must contain MeasurementInformationRows and ResultRows.");
end

style = spectralab.report.internal.createReportStyle();

height = style.Box.TitleHeight + ...
    style.InformationBox.BoxPadding + ...
    sum(arrayfun(@rowLineCount, model.MeasurementInformationRows)) * ...
        style.InformationBox.RowHeight + ...
    style.InformationBox.SectionGap + ...
    sum(arrayfun(@rowLineCount, model.ResultRows)) * ...
        style.InformationBox.RowHeight + ...
    style.InformationBox.BoxPadding;
end

function count = rowLineCount(row)
count = 1;
if isfield(row, "LineCount") && isscalar(row.LineCount) && ...
        isfinite(row.LineCount) && row.LineCount >= 1
    count = double(row.LineCount);
end
end
