function info = exportPDF(pdfFile, layoutPlan, renderContext)
%EXPORTPDF Export a minimal self-contained A4 portrait PDF.
%
%   info = spectralab.report.internal.exportPDF( ...
%       pdfFile, layoutPlan, renderContext)
%
% RP-017a renders heading, paragraph, tables, spacer, captions, and the
% actual report-owned figure. It reads the completed LayoutPlan and
% RenderContext only; it performs no analysis or layout calculations.

arguments
    pdfFile (1,1) string
    layoutPlan (:,1) struct
    renderContext (1,1) struct
end

pdfFile = validateTarget(pdfFile);
validateInputs(layoutPlan, renderContext);

folder = string(fileparts(pdfFile));
if folder == ""
    folder = string(pwd);
end

temporaryFile = string(tempname(folder)) + ".pdf";
cleanupTemporary = onCleanup(@() deleteIfExists(temporaryFile)); %#ok<NASGU>

pageCount = max([layoutPlan.Page], [], "omitmissing");
if isempty(pageCount) || pageCount < 1
    pageCount = 1;
end

layout = spectralab.report.internal.createLayoutState();
records = renderContext.State.RenderedElements;

for page = 1:pageCount
    fig = createPageFigure(layout);
    cleanupFigure = onCleanup(@() closeIfValid(fig)); %#ok<NASGU>

    drawPageFrame( ...
        fig, ...
        layout, ...
        renderContext.PageFrame, ...
        page, ...
        pageCount);

    pagePlacements = layoutPlan([layoutPlan.Page] == page);
    for k = 1:numel(pagePlacements)
        placement = pagePlacements(k);
        if placement.ExplicitPageBreak
            continue
        end
        if ~placement.Measured
            error("SpectraLab:Report:UnmeasuredPDFElement", ...
                "PDF export requires a measured element. Element '%s' has no layout height.", ...
                placement.ElementId);
        end

        record = findRecord(records, placement.ElementId);
        drawElement(fig, layout, placement, record, renderContext);
    end

    if page == 1
        exportgraphics(fig, temporaryFile, ...
            "ContentType", "vector", ...
            "BackgroundColor", "white");
    else
        exportgraphics(fig, temporaryFile, ...
            "ContentType", "vector", ...
            "BackgroundColor", "white", ...
            "Append", true);
    end

    closeIfValid(fig);
    clear cleanupFigure
end

[ok, message] = movefile(temporaryFile, pdfFile);
if ~ok
    error("SpectraLab:Report:PDFExportFailed", ...
        "Unable to finalize PDF report '%s': %s", pdfFile, message);
end

info = struct( ...
    "PDFFile", pdfFile, ...
    "PageCount", double(pageCount), ...
    "Format", "PDF", ...
    "PageSize", "A4", ...
    "Orientation", "portrait");
end

function pdfFile = validateTarget(pdfFile)
pdfFile = string(pdfFile);
if ~endsWith(lower(pdfFile), ".pdf")
    error("SpectraLab:Report:InvalidPDFFile", ...
        "PDF output filename must use the .pdf extension.");
end

folder = string(fileparts(pdfFile));
if folder ~= "" && ~isfolder(folder)
    error("SpectraLab:Report:OutputFolderNotFound", ...
        "PDF output folder does not exist: %s", folder);
end

if isfile(pdfFile)
    error("SpectraLab:Report:ReportFileAlreadyExists", ...
        "Report file already exists: %s", pdfFile);
end
end

function validateInputs(layoutPlan, renderContext)
requiredPlacement = ["ElementId", "ElementType", "Page", "Y", ...
    "Height", "Measured", "ExplicitPageBreak", "AutomaticPageBreak"];
for k = 1:numel(layoutPlan)
    for j = 1:numel(requiredPlacement)
        if ~isfield(layoutPlan(k), requiredPlacement(j))
            error("SpectraLab:Report:InvalidLayoutPlan", ...
                "LayoutPlan entry is missing required field '%s'.", ...
                requiredPlacement(j));
        end
    end
end

if ~isfield(renderContext, "State") || ...
        ~isfield(renderContext.State, "RenderedElements") || ...
        ~isstruct(renderContext.State.RenderedElements)
    error("SpectraLab:Report:InvalidRenderContext", ...
        "RenderContext must contain State.RenderedElements.");
end

if ~isfield(renderContext, "PageFrame") || ...
        ~isstruct(renderContext.PageFrame) || ...
        ~isscalar(renderContext.PageFrame)
    error("SpectraLab:Report:InvalidPageFrame", ...
        "RenderContext must contain one PageFrame model.");
end
end

function fig = createPageFigure(layout)
style = spectralab.report.internal.createReportStyle();
fig = figure( ...
    "Visible", "off", ...
    "Color", style.Appearance.BackgroundColor, ...
    "Units", "points", ...
    "Position", [100 100 layout.PageWidth layout.PageHeight], ...
    "PaperUnits", "points", ...
    "PaperSize", [layout.PageWidth layout.PageHeight], ...
    "PaperPosition", [0 0 layout.PageWidth layout.PageHeight], ...
    "InvertHardcopy", "off", ...
    "MenuBar", "none", ...
    "ToolBar", "none");

% A full-page background axes prevents exportgraphics from tightly cropping
% the document to its annotations. This preserves the physical A4 canvas and
% therefore the declared 20 mm page margins.
bg = axes(fig, ...
    "Units", "normalized", ...
    "Position", [0 0 1 1], ...
    "XLim", [0 1], ...
    "YLim", [0 1], ...
    "Color", style.Appearance.BackgroundColor, ...
    "Visible", "off", ...
    "HitTest", "off", ...
    "HandleVisibility", "off");
rectangle(bg, "Position", [0 0 1 1], ...
    "FaceColor", "white", ...
    "EdgeColor", "none", ...
    "HitTest", "off", ...
    "HandleVisibility", "off");
end

function drawPageFrame(fig, layout, model, page, pageCount)
style = spectralab.report.internal.createReportStyle();
%DRAWPAGEFRAME Draw the fixed report header and footer.

validatePageFrame(model);

left = layout.MarginLeft / layout.PageWidth;
right = 1 - layout.MarginRight / layout.PageWidth;
contentWidth = right - left;

headerY = 1 - 34 / layout.PageHeight;
footerY = 20 / layout.PageHeight;

headerHeight = 16 / layout.PageHeight;
footerHeight = 16 / layout.PageHeight;

headerLeft = [left headerY contentWidth/2 headerHeight];
headerRight = [left + contentWidth/2 headerY contentWidth/2 headerHeight];

footerLeft = [left footerY contentWidth/3 footerHeight];
footerCenter = [left + contentWidth/3 footerY contentWidth/3 footerHeight];
footerRight = [left + 2*contentWidth/3 footerY contentWidth/3 footerHeight];

drawPageFrameHeaderText( ...
    fig, headerLeft, headerRight, model, style);

drawPageFrameText(fig, footerLeft, model.FooterLeft, ...
    "left", style.PageFrame.FooterFontSize, ...
    style.Font.WeightNormal, "normal", "middle", style);
drawPageFrameText(fig, footerCenter, model.FooterCenter, ...
    "center", style.PageFrame.FooterFontSize, ...
    style.Font.WeightNormal, "normal", "middle", style);
drawPageFrameText(fig, footerRight, ...
    "Page " + string(page) + " of " + string(pageCount), ...
    "right", style.PageFrame.FooterFontSize, ...
    style.Font.WeightNormal, "normal", "middle", style);

headerRuleY = 1 - layout.MarginTop / layout.PageHeight + ...
    style.PageFrame.RuleOffset / layout.PageHeight;
footerRuleY = layout.MarginBottom / layout.PageHeight - ...
    style.PageFrame.RuleOffset / layout.PageHeight;

annotation(fig, "line", [left right], [headerRuleY headerRuleY], ...
    "Color", style.Appearance.PageFrameRuleColor, ...
    "LineWidth", style.Appearance.PageFrameRuleLineWidth);

annotation(fig, "line", [left right], [footerRuleY footerRuleY], ...
    "Color", style.Appearance.PageFrameRuleColor, ...
    "LineWidth", style.Appearance.PageFrameRuleLineWidth);
end


function drawPageFrameHeaderText( ...
        fig, leftPosition, rightPosition, model, style)
%DRAWPAGEFRAMEHEADERTEXT Draw both header texts in one shared row.

headerAxes = axes( ...
    "Parent", fig, ...
    "Units", "normalized", ...
    "Position", [0 0 1 1], ...
    "Visible", "off", ...
    "XLim", [0 1], ...
    "YLim", [0 1], ...
    "HitTest", "off");

rowCenterY = leftPosition(2) + leftPosition(4) / 2;

text(headerAxes, ...
    leftPosition(1), ...
    rowCenterY, ...
    char(string(model.HeaderLeft)), ...
    "Interpreter", "none", ...
    "FontName", style.Font.Name, ...
    "FontSize", style.PageFrame.HeaderTitleFontSize, ...
    "FontWeight", style.Font.WeightBold, ...
    "FontAngle", style.Font.AngleItalic, ...
    "HorizontalAlignment", "left", ...
    "VerticalAlignment", "middle", ...
    "Clipping", "off");

text(headerAxes, ...
    rightPosition(1) + rightPosition(3), ...
    rowCenterY, ...
    char(string(model.HeaderRight)), ...
    "Interpreter", "none", ...
    "FontName", style.Font.Name, ...
    "FontSize", style.PageFrame.HeaderInformationFontSize, ...
    "FontWeight", style.Font.WeightNormal, ...
    "FontAngle", "normal", ...
    "HorizontalAlignment", "right", ...
    "VerticalAlignment", "middle", ...
    "Clipping", "off");
end


function drawPageFrameText( ...
        fig, position, content, alignment, fontSize, ...
        fontWeight, fontAngle, verticalAlignment, style)

annotation(fig, "textbox", position, ...
    "String", char(string(content)), ...
    "Interpreter", "none", ...
    "FontName", style.Font.Name, ...
    "FontSize", fontSize, ...
    "FontWeight", fontWeight, ...
    "FontAngle", fontAngle, ...
    "HorizontalAlignment", alignment, ...
    "VerticalAlignment", verticalAlignment, ...
    "EdgeColor", "none", ...
    "Margin", style.PageFrame.TextMargin, ...
    "FitBoxToText", "off");
end


function validatePageFrame(model)

required = [ ...
    "Format"
    "Version"
    "HeaderLeft"
    "HeaderRight"
    "FooterLeft"
    "FooterCenter"];

for fieldName = required.'
    if ~isfield(model, fieldName)
        error("SpectraLab:Report:InvalidPageFrame", ...
            "PageFrame is missing required field '%s'.", ...
            fieldName);
    end
end

if string(model.Format) ~= "SLAB-REPORT-PAGE-FRAME"
    error("SpectraLab:Report:InvalidPageFrame", ...
        "PageFrame has an unsupported format.");
end
end


function record = findRecord(records, elementId)
matches = string({records.Id}) == string(elementId);
if nnz(matches) ~= 1
    error("SpectraLab:Report:MissingRenderedElement", ...
        "Expected exactly one rendered element for '%s'.", elementId);
end
record = records(matches);
end

function drawElement(fig, layout, placement, record, renderContext)
style = spectralab.report.internal.createReportStyle();
type = string(record.Type);
switch type
    case "heading"
        drawTextBox(fig, layout, placement, string(record.Content), ...
            style.Text.HeadingFontSize, "bold", "left", style);
    case "paragraph"
        drawTextBox(fig, layout, placement, string(record.Content), ...
            style.Text.ParagraphFontSize, "normal", "left", style);
    case "table"
        if string(record.Role) == "informationBox"
            drawInformationBox(fig, layout, placement, record.Content);
        else
            drawResultsTable(fig, layout, placement, record.Content);
        end
    case "figure"
        drawReportFigure(fig, layout, placement, record.Content, renderContext);
    case "caption"
        drawFigureCaption(fig, layout, placement, record.Content);
    case "spacer"
        % A spacer consumes layout height but draws no marks.
    otherwise
        error("SpectraLab:Report:UnsupportedPDFElement", ...
            "RP-012 PDF backend does not support element type '%s'.", type);
end
end

function drawTextBox(fig, layout, placement, content, fontSize, fontWeight, alignment, style)
pos = normalizedBox(layout, placement, layout.ContentWidth);
annotation(fig, "textbox", pos, ...
    "String", char(content), ...
    "Interpreter", "none", ...
    "FontName", style.Font.Name, ...
    "FontSize", fontSize, ...
    "FontWeight", fontWeight, ...
    "HorizontalAlignment", alignment, ...
    "VerticalAlignment", "top", ...
    "EdgeColor", "none", ...
    "Margin", style.Text.Margin, ...
    "FitBoxToText", "off");
end

function [innerPlacement, titleHeight] = drawBoxTitle( ...
        fig, layout, boxPlacement, boxWidth, model)

style = spectralab.report.internal.createReportStyle();

titleHeight = 0;
innerPlacement = boxPlacement;

if ~isfield(model, "Title") || ...
        strlength(strtrim(string(model.Title))) == 0
    return
end

titleHeight = style.Box.TitleHeight;
titlePlacement = boxPlacement;
titlePlacement.Height = titleHeight;

titlePosition = normalizedBox( ...
    layout, ...
    titlePlacement, ...
    boxWidth);

annotation(fig, "textbox", titlePosition, ...
    "String", char(string(model.Title)), ...
    "Interpreter", "none", ...
    "FontName", style.Font.Name, ...
    "FontSize", style.Box.TitleFontSize, ...
    "FontWeight", style.Font.WeightBold, ...
    "HorizontalAlignment", "left", ...
    "VerticalAlignment", "middle", ...
    "EdgeColor", "none", ...
    "Margin", style.Box.TitleMargin, ...
    "FitBoxToText", "off");

innerPlacement.Y = innerPlacement.Y + titleHeight;
innerPlacement.Height = max(innerPlacement.Height - titleHeight, 1);
end


function drawResultsTable(fig, layout, placement, model)
%DRAWRESULTSTABLE Draw a compact framed report table.
%
% The table uses 62 percent of the available content width and is aligned
% to the left margin. The remaining area on the right is intentionally
% left blank for handwritten notes.
%
% The table is inset vertically within its measured layout area to create
% visible separation from adjacent report elements.

style = spectralab.report.internal.createReportStyle();

    if ~isstruct(model) || ~isfield(model, "Rows")
        error("SpectraLab:Report:InvalidPDFTable", ...
            "PDF table element does not contain a valid table model.");
    end

    rows = model.Rows;
    rowCount = numel(rows);

    if rowCount == 0
        return
    end

    rowLineCounts = arrayfun(@resultsTableRowLineCount, rows);
    totalLineCount = sum(rowLineCounts);

    boxWidthFraction = style.Box.WidthFraction;

    if isfield(model, "Role") && string(model.Role) == "provenance"
        boxWidthFraction = ...
            style.ResultsTable.ProvenanceWidthFraction;
    end

    boxWidth = layout.ContentWidth * boxWidthFraction;
    verticalGap = style.ResultsTable.VerticalGap;

    boxPlacement = placement;
    boxPlacement.Y = placement.Y + verticalGap / 2;
    boxPlacement.Height = max(placement.Height - verticalGap, 1);

    boxPosition = normalizedBox( ...
        layout, ...
        boxPlacement, ...
        boxWidth);

    annotation(fig, "rectangle", boxPosition, ...
        "LineWidth", style.Appearance.BoxBorderLineWidth, ...
        "EdgeColor", style.Appearance.BoxBorderColor);

    [innerPlacement, ~] = drawBoxTitle( ...
        fig, layout, boxPlacement, boxWidth, model);

    padding = style.Box.ContentPadding;
    innerPlacement.Y = innerPlacement.Y + padding;
    innerPlacement.Height = max( ...
        innerPlacement.Height - 2 * padding, ...
        1);

    lineHeight = innerPlacement.Height / totalLineCount;

    labelWidth = boxWidth * style.ResultsTable.LabelWidthFraction;
    valueWidth = boxWidth - labelWidth;

    lineOffset = 0;

    for k = 1:rowCount
        rowPlacement = innerPlacement;
        rowPlacement.Y = ...
            innerPlacement.Y + lineOffset * lineHeight;
        rowPlacement.Height = rowLineCounts(k) * lineHeight;

        lineOffset = lineOffset + rowLineCounts(k);

        labelPosition = normalizedBox( ...
            layout, ...
            rowPlacement, ...
            labelWidth);

        valuePosition = normalizedBox( ...
            layout, ...
            rowPlacement, ...
            valueWidth);

        valuePosition(1) = valuePosition(1) + ...
            labelWidth / layout.PageWidth;

        annotation(fig, "textbox", labelPosition, ...
            "String", char(string(rows(k).Label)), ...
            "Interpreter", "none", ...
            "FontName", style.Font.Name, ...
            "FontSize", style.ResultsTable.FontSize, ...
            "FontWeight", style.Font.WeightBold, ...
            "HorizontalAlignment", "left", ...
            "VerticalAlignment", "middle", ...
            "EdgeColor", "none", ...
            "Margin", style.Box.CellMargin, ...
            "FitBoxToText", "off");

        annotation(fig, "textbox", valuePosition, ...
            "String", char(string(rows(k).DisplayText)), ...
            "Interpreter", "none", ...
            "FontName", style.Font.Name, ...
            "FontSize", style.ResultsTable.FontSize, ...
            "FontWeight", style.Font.WeightNormal, ...
            "HorizontalAlignment", "left", ...
            "VerticalAlignment", "middle", ...
            "EdgeColor", "none", ...
            "Margin", style.Box.CellMargin, ...
            "FitBoxToText", "off");
    end
end


function count = resultsTableRowLineCount(row)

count = 1;

if isfield(row, "LineCount")
    candidate = double(row.LineCount);

    if isscalar(candidate) && isfinite(candidate) && candidate >= 1
        count = candidate;
    end
end
end


function drawInformationBox(fig, layout, placement, model)
%DRAWINFORMATIONBOX Draw a compact framed information box.
%
% The box uses 62 percent of the available content width and is aligned to
% the left page margin. The remaining width on the right is intentionally
% left blank for handwritten notes on printed reports.

style = spectralab.report.internal.createReportStyle();

if ~isstruct(model) || ...
        ~isfield(model, "MeasurementInformationRows") || ...
        ~isfield(model, "ResultRows")

    error("SpectraLab:Report:InvalidInformationBox", ...
        "PDF InformationBox element has an invalid model.");
end

rows = [ ...
    model.MeasurementInformationRows
    metadataFromResults(model.ResultRows)];

if isempty(rows)
    return
end

boxWidth = layout.ContentWidth * style.Box.WidthFraction;
verticalGap = style.InformationBox.VerticalGap;

boxPlacement = placement;
boxPlacement.Y = placement.Y + verticalGap / 2;
boxPlacement.Height = max(placement.Height - verticalGap, 1);

boxPosition = normalizedBox(layout, boxPlacement, boxWidth);

annotation(fig, "rectangle", boxPosition, ...
    "LineWidth", style.Appearance.BoxBorderLineWidth, ...
    "EdgeColor", style.Appearance.BoxBorderColor);

[innerPlacement, ~] = drawBoxTitle( ...
    fig, layout, boxPlacement, boxWidth, model);

padding = style.Box.ContentPadding;
innerPlacement.Y = innerPlacement.Y + padding;
innerPlacement.Height = max( ...
    innerPlacement.Height - 2 * padding, ...
    1);

rowHeight = innerPlacement.Height / numel(rows);

labelWidth = boxWidth * style.InformationBox.LabelWidthFraction;
valueWidth = boxWidth - labelWidth;

for k = 1:numel(rows)
    rowPlacement = innerPlacement;
    rowPlacement.Y = ...
        innerPlacement.Y + (k - 1) * rowHeight;
    rowPlacement.Height = rowHeight;

    labelPosition = normalizedBox( ...
        layout, ...
        rowPlacement, ...
        labelWidth);

    valuePosition = normalizedBox( ...
        layout, ...
        rowPlacement, ...
        valueWidth);

    valuePosition(1) = valuePosition(1) + ...
        labelWidth / layout.PageWidth;

    annotation(fig, "textbox", labelPosition, ...
        "String", char(string(rows(k).Label)), ...
        "Interpreter", "none", ...
        "FontName", style.Font.Name, ...
        "FontSize", style.InformationBox.FontSize, ...
        "FontWeight", style.Font.WeightBold, ...
        "HorizontalAlignment", "left", ...
        "VerticalAlignment", "middle", ...
        "EdgeColor", "none", ...
        "Margin", style.Box.CellMargin, ...
        "FitBoxToText", "off");

    annotation(fig, "textbox", valuePosition, ...
        "String", char(string(rows(k).DisplayText)), ...
        "Interpreter", "none", ...
        "FontName", style.Font.Name, ...
        "FontSize", style.InformationBox.FontSize, ...
        "FontWeight", style.Font.WeightNormal, ...
        "HorizontalAlignment", "left", ...
        "VerticalAlignment", "middle", ...
        "EdgeColor", "none", ...
        "Margin", style.Box.CellMargin, ...
        "FitBoxToText", "off");
end
end


function rows = metadataFromResults(resultRows)
rows = repmat(struct("Label","","DisplayText",""),numel(resultRows),1);
for k=1:numel(resultRows)
    rows(k).Label = string(resultRows(k).Label);
    rows(k).DisplayText = string(resultRows(k).DisplayText);
end
end

function drawFigureCaption(fig, layout, placement, model)
style = spectralab.report.internal.createReportStyle();
if ~isstruct(model) || ~isfield(model, "Text") || ...
        string(model.Role) ~= "primaryFigureCaption"
    error("SpectraLab:Report:InvalidFigureCaption", ...
        "PDF caption element does not contain a valid figure-caption model.");
end
pos = normalizedBox(layout, placement, layout.ContentWidth);
annotation(fig, "textbox", pos, ...
    "String", char(string(model.Text)), ...
    "Interpreter", "none", ...
    "FontName", style.Font.Name, ...
    "FontSize", style.Caption.FontSize, ...
    "FontAngle", style.Font.AngleItalic, ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "top", ...
    "EdgeColor", "none", ...
    "Margin", style.Caption.Margin, ...
    "FitBoxToText", "off");
end

function drawReportFigure(fig, layout, placement, model, renderContext)
style = spectralab.report.internal.createReportStyle();
if ~isstruct(model) || ~isfield(model, "Width") || ~isfield(model, "Height")
    error("SpectraLab:Report:InvalidPDFFigure", ...
        "PDF figure element does not contain a valid figure model.");
end
if ~isfield(renderContext, "Graphics") || ...
        ~isfield(renderContext.Graphics, "Axes") || ...
        ~isscalar(renderContext.Graphics.Axes) || ...
        ~isgraphics(renderContext.Graphics.Axes, "axes")
    error("SpectraLab:Report:MissingFigureGraphics", ...
        "PDF export requires one valid report-owned source axes for the figure element.");
end

width = min(double(model.Width), layout.ContentWidth);
height = double(placement.Height);
pos = normalizedBox(layout, placement, width);
figureBottomPadding = style.Figure.BottomPadding;
figureTopPadding = style.Figure.TopPadding;
pos(2) = pos(2) + figureBottomPadding / layout.PageHeight;
pos(4) = max( ...
    pos(4) - ...
    (figureBottomPadding + figureTopPadding) / layout.PageHeight, ...
    1 / layout.PageHeight);
pos(1) = pos(1) + (layout.ContentWidth - width) / (2 * layout.PageWidth);

sourceAxes = renderContext.Graphics.Axes;
reportAxes = copyobj(sourceAxes, fig);
set(reportAxes, ...
    "Units", "normalized", ...
    "Position", pos, ...
    "ActivePositionProperty", "position", ...
    "HandleVisibility", "off");
end

function pos = normalizedBox(layout, placement, width)
x = layout.MarginLeft / layout.PageWidth;
yBottomPoints = layout.PageHeight - layout.MarginTop - ...
    placement.Y - placement.Height;
y = yBottomPoints / layout.PageHeight;
w = width / layout.PageWidth;
h = placement.Height / layout.PageHeight;
pos = [x y w h];
end

function deleteIfExists(file)
if isfile(file)
    delete(file);
end
end

function closeIfValid(fig)
if ~isempty(fig) && isgraphics(fig)
    close(fig);
end
end
