function profile = figureLayoutProfile()
%FIGURELAYOUTPROFILE Canonical geometry for SpectraLab report figures.
%
% The profile reserves an explicit left gutter for axis labels and a fixed
% right-side column for legends and explanatory information.  All report
% renderers and export backends use these values so that PNG and PDF
% products retain the same visual hierarchy.

profile = struct( ...
    "AxesWithSidebar", [0.11 0.12 0.56 0.80], ...
    "AxesWithLegend", [0.11 0.12 0.55 0.80], ...
    "AxesOuterWithoutSidebar", [0.02 0.08 0.96 0.84], ...
    "SidePanel", [0.72 0.22 0.24 0.42], ...
    "SideLegend", [0.72 0.70 0.24 0.18], ...
    "MaximumSideColumnCharacters", 26);
end
