function profile = figureLayoutProfile()
%FIGURELAYOUTPROFILE Canonical geometry for SpectraLab report figures.
%
% The profile reserves an explicit left gutter for axis labels and a fixed
% right-side column for legends and explanatory information.  All report
% renderers and export backends use these values so that PNG and PDF
% products retain the same visual hierarchy.

profile = struct( ...
    "InteractiveFigurePosition", [100 100 1400 700], ...
    "PNGFigureSizePoints", [1008 504], ...
    "PNGResolution", 100, ...
    "AxesWithSidebar", [0.11 0.12 0.56 0.80], ...
    "AxesWithLegend", [0.11 0.12 0.55 0.80], ...
    "AxesOuterWithoutSidebar", [0.02 0.08 0.96 0.84], ...
    "SidePanel", [0.70 0.10 0.28 0.60], ...
    "SideLegend", [0.70 0.75 0.28 0.17], ...
    "SidePanelFontSize", 8, ...
    "MaximumSideLegendCharacters", 12, ...
    "MaximumSideColumnCharacters", 26);
end
