% Create one self-contained Camera-41 reflectance input and proof PNG.
outputFolder=string(pwd);
[referenceName,referenceFolder]=uigetfile({"*.mat","SpectraLab MAT (*.mat)"}, ...
    "Reflectance REFERENCE - illuminated white reference standard", ...
    spectralab.ui.archiveFolder(outputFolder));
if isequal(referenceName,0), return; end
spectralab.ui.archiveFolder(outputFolder,string(referenceFolder));
referenceFile=fullfile(string(referenceFolder),string(referenceName));
[sampleName,sampleFolder]=uigetfile({"*.mat","SpectraLab MAT (*.mat)"}, ...
    "Reflectance SAMPLE - illuminated target or material", ...
    string(referenceFolder));
if isequal(sampleName,0), return; end
spectralab.ui.archiveFolder(outputFolder,string(sampleFolder));
sampleFile=fullfile(string(sampleFolder),string(sampleName));
confirmation=questdlg(char( ...
    "Create spectral reflectance as SAMPLE / REFERENCE?"+newline+newline+ ...
    "REFERENCE (white reference standard):"+newline+referenceFile+newline+newline+ ...
    "SAMPLE (target or material):"+newline+sampleFile+newline+newline+ ...
    "Check the assigned roles before continuing."), ...
    "Confirm Camera-41 reflectance inputs", ...
    "Create input","Cancel","Cancel");
if ~strcmp(confirmation,"Create input")
    disp("Camera-41 reflectance input cancelled. Nothing was saved.");
    return
end
[~,sampleStem]=fileparts(sampleFile);
defaultID=spectralab.archive.normalizeArtifactID(sampleStem);
answer=inputdlg("Short artifact ID (target, material or purpose)", ...
    "Camera-41 reflectance input",[1 60],cellstr(defaultID));
if isempty(answer), return; end
artifactID=spectralab.archive.normalizeArtifactID(string(answer{1}));
outputs=spectralab.archive.nextArtifactOutput(outputFolder, ...
    artifactID,"reflectance",ProofFolder=outputFolder);
reference=spectralab.archive.load(referenceFile,Quiet=true,Validation="error");
sample=spectralab.archive.load(sampleFile,Quiet=true,Validation="error");
artifact=spectralab.analysis.createReflectanceArtifact(reference,sample, ...
    ReferenceFile=referenceFile,SampleFile=sampleFile, ...
    Name=sampleStem+" spectral reflectance");
spectralab.archive.saveSpectralArtifact(artifact,outputs.ArtifactFile);
proof=spectralab.plot.spectralArtifactProof( ...
    artifact,outputs.ProofPNG,ShowFigure=true);
fprintf("\nCamera-41 reflectance input complete\n");
fprintf("  Reference: %s\n  Sample:    %s\n",referenceFile,sampleFile);
fprintf("  Artifact:  %s\n  Proof PNG: %s\n", ...
    outputs.ArtifactFile,proof.PNGFile);
