% Create one self-contained Camera-41 transmission input and proof PNG.
outputFolder=string(pwd);
[referenceName,referenceFolder]=uigetfile({"*.mat","SpectraLab MAT (*.mat)"}, ...
    "Transmission REFERENCE - source without film, filter or sample", ...
    spectralab.ui.archiveFolder(outputFolder));
if isequal(referenceName,0), return; end
referenceFile=fullfile(string(referenceFolder),string(referenceName));
[sampleName,sampleFolder]=uigetfile({"*.mat","SpectraLab MAT (*.mat)"}, ...
    "Transmission SAMPLE - same source measured through film or filter", ...
    string(referenceFolder));
if isequal(sampleName,0), return; end
sampleFile=fullfile(string(sampleFolder),string(sampleName));
confirmation=questdlg(char( ...
    "Create spectral transmission as SAMPLE / REFERENCE?"+newline+newline+ ...
    "REFERENCE (source without sample):"+newline+referenceFile+newline+newline+ ...
    "SAMPLE (source through film or filter):"+newline+sampleFile+newline+newline+ ...
    "Check the assigned roles before continuing."), ...
    "Confirm Camera-41 transmission inputs", ...
    "Create input","Cancel","Cancel");
if ~strcmp(confirmation,"Create input")
    disp("Camera-41 transmission input cancelled. Nothing was saved.");
    return
end
[~,sampleStem]=fileparts(sampleFile);
defaultID=spectralab.archive.normalizeArtifactID(sampleStem);
answer=inputdlg("Short artifact ID (film, target or purpose)", ...
    "Camera-41 transmission input",[1 60],cellstr(defaultID));
if isempty(answer), return; end
artifactID=spectralab.archive.normalizeArtifactID(string(answer{1}));
outputs=spectralab.archive.nextArtifactOutput(outputFolder, ...
    artifactID,"transmission",ProofFolder=outputFolder);
reference=spectralab.archive.load(referenceFile,Quiet=true,Validation="error");
sample=spectralab.archive.load(sampleFile,Quiet=true,Validation="error");
artifact=spectralab.analysis.createTransmissionArtifact(reference,sample, ...
    ReferenceFile=referenceFile,SampleFile=sampleFile, ...
    Name=sampleStem+" spectral transmission");
spectralab.archive.saveSpectralArtifact(artifact,outputs.ArtifactFile);
proof=spectralab.plot.spectralArtifactProof( ...
    artifact,outputs.ProofPNG,ShowFigure=true);
fprintf("\nCamera-41 transmission input complete\n");
fprintf("  Reference: %s\n  Sample:    %s\n",referenceFile,sampleFile);
fprintf("  Artifact:  %s\n  Proof PNG: %s\n", ...
    outputs.ArtifactFile,proof.PNGFile);
