function tests = test_core_weightedDensity
%TEST_CORE_WEIGHTEDDENSITY Tests for the shared weighted-density engine.

    tests = functiontests(localfunctions);
end


function testIdenticalSignalsGiveZeroDensity(testCase)

    wavelengthNm = (400:10:700).';

    reference = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    sample = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    weighting = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    result = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        weighting);

    verifyEqual(testCase, result.Transmittance, 1, ...
        AbsTol=1e-12);

    verifyEqual(testCase, result.Density, 0, ...
        AbsTol=1e-12);
end


function testHalfTransmissionGivesExpectedDensity(testCase)

    wavelengthNm = (400:10:700).';

    reference = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    sample = localSpectrum( ...
        wavelengthNm, ...
        0.5 .* ones(size(wavelengthNm)));

    weighting = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    result = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        weighting);

    verifyEqual(testCase, result.Transmittance, 0.5, ...
        AbsTol=1e-12);

    verifyEqual(testCase, result.Density, -log10(0.5), ...
        AbsTol=1e-12);
end


function testTenPercentTransmissionGivesDensityOne(testCase)

    wavelengthNm = (400:10:700).';

    reference = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    sample = localSpectrum( ...
        wavelengthNm, ...
        0.1 .* ones(size(wavelengthNm)));

    weighting = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    result = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        weighting);

    verifyEqual(testCase, result.Transmittance, 0.1, ...
        AbsTol=1e-12);

    verifyEqual(testCase, result.Density, 1, ...
        AbsTol=1e-12);
end


function testDifferentWavelengthGridsAreInterpolated(testCase)

    reference = localSpectrum( ...
        [400; 500; 600; 700], ...
        [1; 1; 1; 1]);

    sample = localSpectrum( ...
        [400; 450; 550; 650; 700], ...
        [0.5; 0.5; 0.5; 0.5; 0.5]);

    weighting = localSpectrum( ...
        [400; 475; 525; 625; 700], ...
        [0; 1; 1; 1; 0]);

    result = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        weighting);

    verifyEqual(testCase, result.Transmittance, 0.5, ...
        AbsTol=1e-12);

    verifyEqual(testCase, result.Density, -log10(0.5), ...
        AbsTol=1e-12);
end


function testZeroSampleGivesInfiniteDensity(testCase)

    wavelengthNm = (400:10:700).';

    reference = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    sample = localSpectrum( ...
        wavelengthNm, ...
        zeros(size(wavelengthNm)));

    weighting = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    result = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        weighting);

    verifyEqual(testCase, result.Transmittance, 0);
    verifyTrue(testCase, isinf(result.Density));
end


function testNoCommonRangeThrowsError(testCase)

    reference = localSpectrum( ...
        [400; 500], ...
        [1; 1]);

    sample = localSpectrum( ...
        [600; 700], ...
        [0.5; 0.5]);

    weighting = localSpectrum( ...
        [400; 700], ...
        [1; 1]);

    verifyError(testCase, ...
        @() spectralab.core.weightedDensity( ...
            reference, ...
            sample, ...
            weighting), ...
        "spectralab:core:weightedDensity:NoOverlap");
end


function testNegativeSampleThrowsError(testCase)

    reference = localSpectrum( ...
        [400; 500; 600], ...
        [1; 1; 1]);

    sample = localSpectrum( ...
        [400; 500; 600], ...
        [0.5; -0.1; 0.5]);

    weighting = localSpectrum( ...
        [400; 500; 600], ...
        [1; 1; 1]);

    verifyError(testCase, ...
        @() spectralab.core.weightedDensity( ...
            reference, ...
            sample, ...
            weighting), ...
        "spectralab:core:weightedDensity:NegativeSignal");
end


function testZeroWeightingThrowsError(testCase)

    wavelengthNm = (400:10:700).';

    reference = localSpectrum( ...
        wavelengthNm, ...
        ones(size(wavelengthNm)));

    sample = localSpectrum( ...
        wavelengthNm, ...
        0.5 .* ones(size(wavelengthNm)));

    weighting = localSpectrum( ...
        wavelengthNm, ...
        zeros(size(wavelengthNm)));

    verifyError(testCase, ...
        @() spectralab.core.weightedDensity( ...
            reference, ...
            sample, ...
            weighting), ...
        "spectralab:core:weightedDensity:ZeroWeighting");
end


function spectrum = localSpectrum(wavelengthNm, value)

    spectrum = struct( ...
        "WavelengthNm", wavelengthNm(:), ...
        "Value", value(:));
end
	
	
	function testResamplingCanBeEnabled(testCase)

	    reference = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 2.0; 1.0]);

	    sample = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [0.5; 1.0; 0.5]);

	    weighting = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 1.0; 1.0]);

	    result = spectralab.core.weightedDensity( ...
	        reference, ...
	        sample, ...
	        weighting, ...
	        Resample=true, ...
	        RefinementFactor=4, ...
	        InterpolationMethod="pchip");

	    verifyTrue(testCase, result.Resampled);
	    verifyEqual(testCase, result.RefinementFactor, 4);
	    verifyEqual(testCase, result.InterpolationMethod, "pchip");

	    verifyEqual( ...
	        testCase, ...
	        result.Transmittance, ...
	        0.5, ...
	        "AbsTol", 1e-12);

	    verifyEqual( ...
	        testCase, ...
	        result.Density, ...
	        -log10(0.5), ...
	        "AbsTol", 1e-12);

	end


	function testResamplingIsDisabledByDefault(testCase)

	    reference = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 2.0; 1.0]);

	    sample = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [0.5; 1.0; 0.5]);

	    weighting = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 1.0; 1.0]);

	    result = spectralab.core.weightedDensity( ...
	        reference, ...
	        sample, ...
	        weighting);

	    verifyFalse(testCase, result.Resampled);
	    verifyEqual(testCase, result.RefinementFactor, 4);
	    verifyEqual(testCase, result.InterpolationMethod, "pchip");

	end


	function testFactorOneDoesNotAlterDensity(testCase)

	    reference = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 2.0; 1.0]);

	    sample = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [0.5; 1.0; 0.5]);

	    weighting = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 1.0; 1.0]);

	    normalResult = spectralab.core.weightedDensity( ...
	        reference, ...
	        sample, ...
	        weighting);

	    factorOneResult = spectralab.core.weightedDensity( ...
	        reference, ...
	        sample, ...
	        weighting, ...
	        Resample=true, ...
	        RefinementFactor=1);

	    verifyEqual( ...
	        testCase, ...
	        factorOneResult.Density, ...
	        normalResult.Density, ...
	        "AbsTol", 1e-12);

	    verifyEqual( ...
	        testCase, ...
	        factorOneResult.Transmittance, ...
	        normalResult.Transmittance, ...
	        "AbsTol", 1e-12);

	end


	function testResamplingSupportsDifferentGrids(testCase)

	    reference = struct( ...
	        "WavelengthNm", [400; 500; 600], ...
	        "Value", [1.0; 2.0; 1.0]);

	    sample = struct( ...
	        "WavelengthNm", [420; 480; 540; 600], ...
	        "Value", [0.5; 0.8; 0.7; 0.5]);

	    weighting = struct( ...
	        "WavelengthNm", [400; 450; 500; 550; 600], ...
	        "Value", [0.0; 0.5; 1.0; 0.5; 0.0]);

	    result = spectralab.core.weightedDensity( ...
	        reference, ...
	        sample, ...
	        weighting, ...
	        Resample=true, ...
	        RefinementFactor=4);

	    verifyTrue(testCase, isfinite(result.Density));
	    verifyTrue(testCase, isfinite(result.Transmittance));

	    verifyEqual( ...
	        testCase, ...
	        result.WavelengthRangeNm, ...
	        [420, 600]);

	end