function tests = test_report_keyValueTable
%TEST_REPORT_KEYVALUETABLE Verify canonical metadata table sources.

tests = functiontests(localfunctions);
end

function testMeasurementUsesResolvedInformation(testCase)
context = struct();
context.Measurement = struct("Name", "Raw name");
context.MeasurementInformation = struct( ...
    "Name", "Resolved name", ...
    "Project", "Project 081", ...
    "Sample", "Sample A", ...
    "Operator", "Operator A", ...
    "Date", datetime(2026, 8, 1, 10, 17, 7));

model = spectralab.report.internal.buildKeyValueTable( ...
    "measurementInformation", context);

verifyEqual(testCase, [model.Rows.Label], ...
    ["Measurement", "Project", "Sample", "Operator", "Date"]);
verifyEqual(testCase, [model.Rows.DisplayText], ...
    ["Resolved name", "Project 081", "Sample A", "Operator A", ...
     "2026-08-01 10:17:07"]);
end
