function tests = test_analysis_xyz
%TEST_ANALYSIS_XYZ Tests CIE 1931 XYZ analysis.

    tests = functiontests(localfunctions);
end


function setupOnce(testCase)

    wavelength = (380:10:730).';
    value = exp(-0.5*((wavelength-560)/55).^2);

    inputResult = struct();
    inputResult.Type = "SyntheticSpectrum";
    inputResult.Result = struct();
    inputResult.Result.WavelengthNm = wavelength;
    inputResult.Result.Value = value;

    testCase.TestData.InputResult = inputResult;
end


function testCreatesXyzResult(testCase)

    result = spectralab.analysis.xyz( ...
        testCase.TestData.InputResult);

    verifyEqual(testCase, result.Type, "CIE1931XYZ");
    verifyTrue(testCase, isfield(result.Result, "X"));
    verifyTrue(testCase, isfield(result.Result, "Y"));
    verifyTrue(testCase, isfield(result.Result, "Z"));

    verifyGreaterThan(testCase, result.Result.X, 0);
    verifyGreaterThan(testCase, result.Result.Y, 0);
    verifyGreaterThan(testCase, result.Result.Z, 0);
end


function testRetainsThreeResponses(testCase)

    result = spectralab.analysis.xyz( ...
        testCase.TestData.InputResult);

    verifyTrue(testCase, isfield(result, "XResponse"));
    verifyTrue(testCase, isfield(result, "YResponse"));
    verifyTrue(testCase, isfield(result, "ZResponse"));

    verifyEqual( ...
        testCase, ...
        result.XResponse.Result.WavelengthNm, ...
        result.YResponse.Result.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        result.XResponse.Result.WavelengthNm, ...
        result.ZResponse.Result.WavelengthNm);
end


function testRawValuesMatchManualIntegration(testCase)

    result = spectralab.analysis.xyz( ...
        testCase.TestData.InputResult);

    expectedX = trapz( ...
        result.XResponse.Result.WavelengthNm, ...
        result.XResponse.Result.Value);

    expectedY = trapz( ...
        result.YResponse.Result.WavelengthNm, ...
        result.YResponse.Result.Value);

    expectedZ = trapz( ...
        result.ZResponse.Result.WavelengthNm, ...
        result.ZResponse.Result.Value);

    verifyEqual( ...
        testCase, ...
        result.Result.RawX, ...
        expectedX, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        result.Result.RawY, ...
        expectedY, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        result.Result.RawZ, ...
        expectedZ, ...
        "AbsTol", 1e-12);
end


function testNoneNormalizationPreservesRawValues(testCase)

    result = spectralab.analysis.xyz( ...
        testCase.TestData.InputResult, ...
        Normalization="none");

    verifyEqual(testCase, result.Result.X, result.Result.RawX);
    verifyEqual(testCase, result.Result.Y, result.Result.RawY);
    verifyEqual(testCase, result.Result.Z, result.Result.RawZ);
    verifyEqual(testCase, result.Processing.ScaleFactor, 1);
end


function testY100Normalization(testCase)

    result = spectralab.analysis.xyz( ...
        testCase.TestData.InputResult, ...
        Normalization="Y100");

    verifyEqual( ...
        testCase, ...
        result.Result.Y, ...
        100, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        result.Result.X / result.Result.Y, ...
        result.Result.RawX / result.Result.RawY, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        result.Result.Z / result.Result.Y, ...
        result.Result.RawZ / result.Result.RawY, ...
        "AbsTol", 1e-12);
end


function testSupportsRequestedRange(testCase)

    requestedRange = [420 680];

    result = spectralab.analysis.xyz( ...
        testCase.TestData.InputResult, ...
        WavelengthRange=requestedRange);

    verifyEqual( ...
        testCase, ...
        result.Range.EffectiveRangeNm, ...
        requestedRange);
end


function testRejectsPartlySpecifiedRange(testCase)

    verifyError( ...
        testCase, ...
        @() spectralab.analysis.xyz( ...
            testCase.TestData.InputResult, ...
            WavelengthRange=[400 NaN]), ...
        "spectralab:analysis:xyz:InvalidRange");
end
