function tests = test_plot_transmission
%TEST_PLOT_TRANSMISSION Tests for spectral transmission plotting.

    tests = functiontests(localfunctions);
end


function testCreatesLine(testCase)
    figureHandle = figure("Visible", "off");
    cleanup = onCleanup(@() close(figureHandle));

    axesHandle = axes("Parent", figureHandle);

    wavelengthNm = [400, 500, 600];
    transmittance = [1.0, 0.5, 0.1];

    lineHandle = spectralab.plot.transmission( ...
        wavelengthNm, ...
        transmittance, ...
        Parent=axesHandle);

    verifyClass( ...
        testCase, ...
        lineHandle, ...
        "matlab.graphics.chart.primitive.Line");

    verifyEqual(testCase, lineHandle.XData, wavelengthNm);
    verifyEqual(testCase, lineHandle.YData, transmittance);
    verifyEqual(testCase, lineHandle.Parent, axesHandle);

    clear cleanup
end


function testAxisLabels(testCase)
    figureHandle = figure("Visible", "off");
    cleanup = onCleanup(@() close(figureHandle));

    axesHandle = axes("Parent", figureHandle);

    spectralab.plot.transmission( ...
        [400, 500, 600], ...
        [1.0, 0.5, 0.1], ...
        Parent=axesHandle);

    verifyEqual( ...
        testCase, ...
        string(axesHandle.XLabel.String), ...
        "Wavelength (nm)");

    verifyEqual( ...
        testCase, ...
        string(axesHandle.YLabel.String), ...
        "Transmission");

    clear cleanup
end


function testCustomTitle(testCase)
    figureHandle = figure("Visible", "off");
    cleanup = onCleanup(@() close(figureHandle));

    axesHandle = axes("Parent", figureHandle);

    spectralab.plot.transmission( ...
        [400, 500], ...
        [1.0, 0.5], ...
        Parent=axesHandle, ...
        Title="Film transmission");

    verifyEqual( ...
        testCase, ...
        string(axesHandle.Title.String), ...
        "Film transmission");

    clear cleanup
end


function testPreservesParentAxes(testCase)
    figureHandle = figure("Visible", "off");
    cleanup = onCleanup(@() close(figureHandle));

    axesHandle = axes("Parent", figureHandle);

    lineHandle = spectralab.plot.transmission( ...
        [400, 500], ...
        [1.0, 0.5], ...
        Parent=axesHandle);

    verifyEqual(testCase, lineHandle.Parent, axesHandle);

    clear cleanup
end


function testRejectsSizeMismatch(testCase)
    testFunction = @() spectralab.plot.transmission( ...
        [400, 500, 600], ...
        [1.0, 0.5]);

    verifyError( ...
        testCase, ...
        testFunction, ...
        "spectralab:plot:transmission:SizeMismatch");
end


function testRejectsEmptyWavelength(testCase)
    testFunction = @() spectralab.plot.transmission([], []);

    verifyError( ...
        testCase, ...
        testFunction, ...
        "spectralab:plot:transmission:EmptyWavelength");
end


function testRejectsEmptyTransmission(testCase)
    testFunction = @() spectralab.plot.transmission( ...
        [400, 500], ...
        []);

    verifyError( ...
        testCase, ...
        testFunction, ...
        "spectralab:plot:transmission:EmptyTransmission");
end


function testRejectsNonFiniteWavelength(testCase)
    testFunction = @() spectralab.plot.transmission( ...
        [400, NaN], ...
        [1.0, 0.5]);

    verifyError( ...
        testCase, ...
        testFunction, ...
        "spectralab:plot:transmission:NonFiniteWavelength");
end


function testRejectsNonFiniteTransmission(testCase)
    testFunction = @() spectralab.plot.transmission( ...
        [400, 500], ...
        [1.0, NaN]);

    verifyError( ...
        testCase, ...
        testFunction, ...
        "spectralab:plot:transmission:NonFiniteTransmission");
end


function testCustomLineWidth(testCase)
    figureHandle = figure("Visible", "off");
    cleanup = onCleanup(@() close(figureHandle));

    axesHandle = axes("Parent", figureHandle);

    lineHandle = spectralab.plot.transmission( ...
        [400, 500], ...
        [1.0, 0.5], ...
        Parent=axesHandle, ...
        LineWidth=2.5);

    verifyEqual(testCase, lineHandle.LineWidth, 2.5);

    clear cleanup
end


function testGridCanBeDisabled(testCase)
    figureHandle = figure("Visible", "off");
    cleanup = onCleanup(@() close(figureHandle));

    axesHandle = axes("Parent", figureHandle);

    spectralab.plot.transmission( ...
        [400, 500], ...
        [1.0, 0.5], ...
        Parent=axesHandle, ...
        ShowGrid=false);

    verifyEqual( ...
        testCase, ...
        string(axesHandle.XGrid), ...
        "off");

    verifyEqual( ...
        testCase, ...
        string(axesHandle.YGrid), ...
        "off");

    clear cleanup
end