function tests = test_report_generate
%TEST_REPORT_GENERATE Verify RP-019 public report orchestration.

tests = functiontests(localfunctions);
end

function setup(testCase)

folder = string(tempname);
mkdir(folder);

testCase.TestData.TempFolder = folder;
testCase.addTeardown(@() removeFolder(folder));
end

function testGeneratesPdfFromSavedArchive(testCase)

folder = string(testCase.TestData.TempFolder);
archiveFile = fullfile(folder, "measurement.mat");
outputFolder = fullfile(folder, "reports");

archive = createArchiveFile(archiveFile);

specification = makeSpecification();

info = spectralab.report.generate( ...
    archiveFile, ...
    specification, ...
    outputFolder, ...
    GenerationTime=datetime(2026,7,30,10,0,0));

verifyTrue(testCase, isfile(info.PDFFile));
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, "measurement_ANL-TEST_report.pdf"));
verifyEqual(testCase, info.Context.Archive.UUID, archive.Identity.UUID);
verifyEqual(testCase, info.Context.Result.Value, 2.5);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-TEST");
verifyFalse(testCase, info.Context.Analysis.HasFigure);
end

function testRefusesToOverwriteExistingPdf(testCase)

folder = string(testCase.TestData.TempFolder);
archiveFile = fullfile(folder, "measurement.mat");
outputFolder = fullfile(folder, "reports");

archive = createArchiveFile(archiveFile);

specification = makeSpecification();

spectralab.report.generate( ...
    archiveFile, specification, outputFolder);

verifyError(testCase, @() ...
    spectralab.report.generate( ...
        archiveFile, specification, outputFolder), ...
    "SpectraLab:Report:ReportFileAlreadyExists");
end

function testGeneratesMeasuredSpectrumByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
archiveFile = fullfile(folder, "spectrum_measurement.mat");
outputFolder = fullfile(folder, "reports");

archive = createArchiveFile(archiveFile);

info = spectralab.report.generate( ...
    archiveFile, ...
    "ANL-SPECTRUM", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyTrue(testCase, isfile(info.PNGFile));
verifyEqual(testCase, ...
    info.Context.Analysis.AnalysisId, ...
    "ANL-SPECTRUM");
verifyEqual(testCase, ...
    info.Context.Result.SampleCount, ...
    numel(archive.Measurement.Wavelength));
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "spectrum_measurement_ANL-SPECTRUM_report.pdf"));
verifyEqual(testCase, ...
    string(info.PNGFile), ...
    fullfile(outputFolder, ...
        "spectrum_measurement_ANL-SPECTRUM_figure.png"));
end

function testGeneratesCriReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
archiveFile = fullfile(folder, "cri_measurement.mat");
outputFolder = fullfile(folder, "reports");

archive = createCriArchiveFile(archiveFile);

info = spectralab.report.generate( ...
    archiveFile, ...
    "ANL-CRI", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyTrue(testCase, isfile(info.PNGFile));
verifyEqual(testCase, ...
    info.Context.Analysis.AnalysisId, ...
    "ANL-CRI");
verifyTrue(testCase, isfinite(info.Context.Result.CCT));
verifyTrue(testCase, isfinite(info.Context.Result.Duv));
verifyTrue(testCase, isfinite(info.Context.Result.Ra));
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "cri_measurement_ANL-CRI_report.pdf"));
verifyEqual(testCase, ...
    string(info.PNGFile), ...
    fullfile(outputFolder, ...
        "cri_measurement_ANL-CRI_figure.png"));
verifyEqual(testCase, ...
    info.Context.Archive.UUID, ...
    archive.Identity.UUID);
end

function testGeneratesReportFromTwoArchiveContract(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "reference.mat");
sampleFile = fullfile(folder, "sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, [2; 4; 6; 8]);
createArchiveFileWithPower(sampleFile, [1; 2; 3; 4]);

specification = makeTwoArchiveSpecification();

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    specification, ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.ArchiveFiles, [referenceFile, sampleFile]);
verifyEqual(testCase, info.Context.Result.MeanRatio, 0.5, AbsTol=1e-12);
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, "sample_ANL-TWO-ARCHIVE_report.pdf"));
end

function testRejectsWrongArchiveCount(testCase)

folder = string(testCase.TestData.TempFolder);
archiveFile = fullfile(folder, "measurement.mat");

createArchiveFile(archiveFile);
specification = makeTwoArchiveSpecification();

verifyError(testCase, @() ...
    spectralab.report.generate( ...
        archiveFile, specification, fullfile(folder, "reports")), ...
    "SpectraLab:Report:ArchiveCountMismatch");
end

function testGeneratesTransmissionReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "transmission_reference.mat");
sampleFile = fullfile(folder, "transmission_sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, 2 .* ones(4,1));
createArchiveFileWithPower(sampleFile, ones(4,1));

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    "ANL-001", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyTrue(testCase, isfile(info.PNGFile));
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-001");
verifyEqual(testCase, ...
    info.Context.Result.MeanTransmission, ...
    0.5, ...
    AbsTol=1e-12);
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "transmission_sample_ANL-001_report.pdf"));
verifyEqual(testCase, ...
    string(info.PNGFile), ...
    fullfile(outputFolder, ...
        "transmission_sample_ANL-001_figure.png"));
end

function testGeneratesOpticalDensityReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "density_reference.mat");
sampleFile = fullfile(folder, "density_sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, 10 .* ones(4,1));
createArchiveFileWithPower(sampleFile, ones(4,1));

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    "ANL-002", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyTrue(testCase, isfile(info.PNGFile));
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-002");
verifyEqual(testCase, ...
    info.Context.Result.MeanDensity, ...
    1, ...
    AbsTol=1e-12);
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "density_sample_ANL-002_report.pdf"));
verifyEqual(testCase, ...
    string(info.PNGFile), ...
    fullfile(outputFolder, ...
        "density_sample_ANL-002_figure.png"));
end

function testGeneratesWhiteDensityReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "white_reference.mat");
sampleFile = fullfile(folder, "white_sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, 10 .* ones(4,1));
createArchiveFileWithPower(sampleFile, ones(4,1));

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    "ANL-004", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyEqual(testCase, string(info.PNGFile), "");
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-004");
verifyEqual(testCase, info.Context.Result.Density, 1, AbsTol=1e-12);
verifyEqual(testCase, ...
    info.Context.Result.Transmittance, ...
    0.1, ...
    AbsTol=1e-12);
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "white_sample_ANL-004_report.pdf"));
end

function testGeneratesStatusADensityReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "status_a_reference.mat");
sampleFile = fullfile(folder, "status_a_sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, 10 .* ones(4,1));
createArchiveFileWithPower(sampleFile, ones(4,1));

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    "ANL-005", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyEqual(testCase, string(info.PNGFile), "");
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-005");

verifyEqual(testCase, ...
    [info.Context.Result.RedDensity, ...
     info.Context.Result.GreenDensity, ...
     info.Context.Result.BlueDensity], ...
    [1, 1, 1], ...
    AbsTol=1e-12);

verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "status_a_sample_ANL-005_report.pdf"));
end

function testGeneratesStatusMDensityReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "status_m_reference.mat");
sampleFile = fullfile(folder, "status_m_sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, 10 .* ones(4,1));
createArchiveFileWithPower(sampleFile, ones(4,1));

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    "ANL-008", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyEqual(testCase, string(info.PNGFile), "");
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-008");

verifyEqual(testCase, ...
    [info.Context.Result.RedDensity, ...
     info.Context.Result.GreenDensity, ...
     info.Context.Result.BlueDensity], ...
    [1, 1, 1], ...
    AbsTol=1e-12);

verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "status_m_sample_ANL-008_report.pdf"));
end

function testGeneratesIsoVisualDensityReportByAnalysisId(testCase)

folder = string(testCase.TestData.TempFolder);
referenceFile = fullfile(folder, "iso_visual_reference.mat");
sampleFile = fullfile(folder, "iso_visual_sample.mat");
outputFolder = fullfile(folder, "reports");

createArchiveFileWithPower(referenceFile, 10 .* ones(4,1));
createArchiveFileWithPower(sampleFile, ones(4,1));

info = spectralab.report.generate( ...
    [referenceFile, sampleFile], ...
    "ANL-007", ...
    outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyEqual(testCase, string(info.PNGFile), "");
verifyEqual(testCase, info.InputRoles, ["Reference", "Sample"]);
verifyEqual(testCase, info.Context.Analysis.AnalysisId, "ANL-007");
verifyEqual(testCase, info.Context.Result.Density, 1, AbsTol=1e-12);
verifyEqual(testCase, ...
    info.Context.Result.Transmittance, ...
    0.1, ...
    AbsTol=1e-12);
verifyEqual(testCase, ...
    string(info.PDFFile), ...
    fullfile(outputFolder, ...
        "iso_visual_sample_ANL-007_report.pdf"));
end

function testRejectsMissingRunner(testCase)

specification = rmfield(makeSpecification(), "AnalysisRunner");

verifyError(testCase, @() ...
    spectralab.report.generate( ...
        "missing.mat", specification, tempdir), ...
    "SpectraLab:Report:InvalidSpecification");
end

function testRejectsMissingFigureRenderer(testCase)

specification = makeSpecification();
specification.AnalysisDefinition.HasFigure = true;
specification.AnalysisDefinition.FigureDefinition = makeFigureDefinition();

verifyError(testCase, @() ...
    spectralab.report.generate( ...
        "missing.mat", specification, tempdir), ...
    "SpectraLab:Report:FigureSpecificationRequired");
end

function testGeneratesPdfAndPngForFigureAnalysis(testCase)

folder = string(testCase.TestData.TempFolder);
archiveFile = fullfile(folder, "figure_measurement.mat");
outputFolder = fullfile(folder, "reports");

archive = createArchiveFile(archiveFile);

specification = makeSpecification();
specification.AnalysisDefinition.HasFigure = true;
specification.AnalysisDefinition.FigureDefinition = makeFigureDefinition();
specification.FigureRenderer = @renderFigure;

info = spectralab.report.generate( ...
    archiveFile, specification, outputFolder);

verifyTrue(testCase, isfile(info.PDFFile));
verifyTrue(testCase, isfile(info.PNGFile));
verifyEqual(testCase, ...
    string(info.PNGFile), ...
    fullfile(outputFolder, "figure_measurement_ANL-TEST_figure.png"));
verifyEqual(testCase, info.Context.Archive.UUID, archive.Identity.UUID);
end

function renderFigure(ax, archive, result)

plot(ax, ...
    archive.Measurement.Wavelength, ...
    archive.Measurement.Value, ...
    "LineWidth", 1.2);

grid(ax, "on");
xlabel(ax, "Wavelength (nm)");
ylabel(ax, "Relative value");
title(ax, "RP-019 generated figure");

if result.Value <= 0
    error("SpectraLab:Report:InvalidTestResult", ...
        "Test result must be positive.");
end
end

function definition = makeFigureDefinition()

definition = struct( ...
    "AspectRatio", 3/2, ...
    "WidthFraction", 0.82, ...
    "MaxHeight", 260, ...
    "Caption", "Measured spectrum generated by RP-019.");
end

function specification = makeSpecification()

definition = struct( ...
    "AnalysisId", "ANL-TEST", ...
    "Name", "Test Analysis", ...
    "Method", "Deterministic test method", ...
    "Standard", "SpectraLab test contract", ...
    "DefinitionVersion", "1", ...
    "HasFigure", false, ...
    "ResultFields", resultField());

specification = struct( ...
    "AnalysisDefinition", definition, ...
    "AnalysisRunner", @runAnalysis);
end

function specification = makeTwoArchiveSpecification()

definition = struct( ...
    "AnalysisId", "ANL-TWO-ARCHIVE", ...
    "Name", "Two Archive Contract", ...
    "Method", "Sample/reference mean ratio", ...
    "Standard", "SpectraLab test contract", ...
    "DefinitionVersion", "1", ...
    "HasFigure", false, ...
    "ResultFields", struct( ...
        "Field", "MeanRatio", ...
        "Label", "Mean ratio", ...
        "Unit", "", ...
        "Format", "%.3f"));

specification = struct( ...
    "InputRoles", ["Reference", "Sample"], ...
    "AnalysisDefinition", definition, ...
    "AnalysisRunner", @runTwoArchiveAnalysis);
end

function result = runTwoArchiveAnalysis(reference, sample)

ratio = double(sample.Measurement.Value) ./ ...
    double(reference.Measurement.Value);

result = struct("MeanRatio", mean(ratio));
end

function result = runAnalysis(archive)

result = struct( ...
    "Value", mean(double(archive.Measurement.Value)));
end

function field = resultField()

field = struct( ...
    "Field", "Value", ...
    "Label", "Value", ...
    "Unit", "a.u.", ...
    "Format", "%.2f");
end

function archive = createArchiveFile(archiveFile)

wavelength = (380:10:410).';
power = [1; 2; 3; 4];

instrument = struct( ...
    "Name", "X-Rite i1Pro 2", ...
    "Driver", "spotread", ...
    "SerialNumber", "1001799");

calibration = struct( ...
    "CalibrationID", "CAL-001");

metadata = struct( ...
    "Operator", "Christer Törnkvist", ...
    "Project", "RP-019", ...
    "SampleID", "PUBLIC-REPORT-001", ...
    "Description", "", ...
    "Laboratory", "", ...
    "Tags", strings(0), ...
    "Comment", "");

spec = spectralab.core.Spectrum( ...
    wavelength, ...
    power, ...
    "RP-019 measurement", ...
    instrument, ...
    calibration, ...
    metadata, ...
    "relative");

spec = spec.withTimestamp(datetime(2026,7,30,9,30,0));

archive = spectralab.archive.create(spec);
spectralab.archive.save(archive, archiveFile);
end

function removeFolder(folder)

if isfolder(folder)
    rmdir(folder, "s");
end
end

function archive = createCriArchiveFile(archiveFile)

wavelength = (380:10:730).';
power = 0.2 + ...
    0.6 * exp(-0.5 * ((wavelength - 455) / 25).^2) + ...
    0.9 * exp(-0.5 * ((wavelength - 545) / 45).^2) + ...
    0.5 * exp(-0.5 * ((wavelength - 610) / 35).^2);

instrument = struct( ...
    "Name", "X-Rite i1Pro 2", ...
    "Driver", "spotread", ...
    "SerialNumber", "1001799");

metadata = struct( ...
    "Operator", "Christer Törnkvist", ...
    "Project", "RP-020", ...
    "SampleID", "CRI-PUBLIC-001");

spec = spectralab.core.Spectrum( ...
    wavelength, ...
    power, ...
    "CRI public report", ...
    instrument, ...
    struct(), ...
    metadata, ...
    "relative");

archive = spectralab.archive.create(spec);
spectralab.archive.save(archive, archiveFile);
end

function archive = createArchiveFileWithPower(archiveFile, power)

wavelength = (380:10:410).';

spec = spectralab.core.Spectrum( ...
    wavelength, ...
    power(:), ...
    "RP-020 two-archive measurement", ...
    struct("Name", "X-Rite i1Pro 2"), ...
    struct(), ...
    struct(), ...
    "relative");

archive = spectralab.archive.create(spec);
spectralab.archive.save(archive, archiveFile);
end
