function tests = test_archive_timestamp_preservation
%TEST_ARCHIVE_TIMESTAMP_PRESERVATION Regression test for ARCH-006.
tests = functiontests(localfunctions);
end

function testRestoredSpectrumPreservesMeasurementTimestamp(testCase)
timestamp = datetime(2026,7,13,10,5,0);

instrument = struct( ...
    "Name", "X-Rite i1Pro 2", ...
    "Driver", "spotread", ...
    "SerialNumber", "1001799");

spec = spectralab.core.Spectrum( ...
    (380:10:730)', ...
    ones(36,1), ...
    "Timestamp preservation", ...
    instrument, ...
    struct("CalibrationID", "CAL-001"), ...
    struct("Operator", "Christer Törnkvist"), ...
    "arbitrary");

spec = spec.withTimestamp(timestamp);
archive = spectralab.archive.create(spec);
restored = spectralab.archive.restore(archive);
recreated = spectralab.archive.create(restored);

verifyEqual(testCase, restored.Timestamp, timestamp);
verifyEqual(testCase, recreated.Identity.ContentHash, ...
    archive.Identity.ContentHash);
verifyNotEqual(testCase, recreated.Identity.UUID, archive.Identity.UUID);
end
