function tests = test_analysis_isoVisualDensity
%TEST_ANALYSIS_ISOVISUALDENSITY Tests for ISO visual density analysis.

    tests = functiontests(localfunctions);
end


function testReturnsExpectedFields(testCase)

    [reference, sample] = localConstantTransmissionSpectra(0.5);

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyTrue(testCase, isstruct(result));
    verifyTrue(testCase, isfield(result, "Density"));
    verifyTrue(testCase, isfield(result, "Transmittance"));
    verifyTrue(testCase, isfield(result, "ReferenceWeightedValue"));
    verifyTrue(testCase, isfield(result, "SampleWeightedValue"));
    verifyTrue(testCase, isfield(result, "WavelengthRangeNm"));
    verifyTrue(testCase, isfield(result, "WeightingName"));
end


function testHalfTransmissionProducesExpectedDensity(testCase)

    [reference, sample] = localConstantTransmissionSpectra(0.5);

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyEqual( ...
        testCase, ...
        result.Transmittance, ...
        0.5, ...
        AbsTol=1e-10);

    verifyEqual( ...
        testCase, ...
        result.Density, ...
        -log10(0.5), ...
        AbsTol=1e-10);
end


function testTenPercentTransmissionProducesDensityOne(testCase)

    [reference, sample] = localConstantTransmissionSpectra(0.1);

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyEqual( ...
        testCase, ...
        result.Transmittance, ...
        0.1, ...
        AbsTol=1e-10);

    verifyEqual( ...
        testCase, ...
        result.Density, ...
        1, ...
        AbsTol=1e-10);
end


function testIdenticalSpectraProduceZeroDensity(testCase)

    [reference, sample] = localConstantTransmissionSpectra(1);

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyEqual( ...
        testCase, ...
        result.Transmittance, ...
        1, ...
        AbsTol=1e-10);

    verifyEqual( ...
        testCase, ...
        result.Density, ...
        0, ...
        AbsTol=1e-10);
end


function testUsesISOVisualWeighting(testCase)

    [reference, sample] = localConstantTransmissionSpectra(0.5);

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyEqual( ...
        testCase, ...
        result.WeightingName, ...
        "ISO visual: illuminant A × V(lambda)");
end


function testISOVisualDiffersFromPhotopicOnlyWeighting(testCase)
% Verify that illuminant A affects a spectrally selective sample.

    wavelengthNm = (380:10:730).';

    reference = struct( ...
        "WavelengthNm", wavelengthNm, ...
        "Value", ones(size(wavelengthNm)));

    % Transmission increases toward longer wavelengths.
    sampleValue = linspace(0.1, 0.9, numel(wavelengthNm)).';

    sample = struct( ...
        "WavelengthNm", wavelengthNm, ...
        "Value", sampleValue);

    isoResult = spectralab.analysis.isoVisualDensity( ...
        reference, ...
        sample);

    whiteResult = spectralab.analysis.whiteDensity( ...
        reference, ...
        sample);

    % Illuminant A gives relatively greater weight to long wavelengths.
    verifyGreaterThan( ...
        testCase, ...
        isoResult.Transmittance, ...
        whiteResult.Transmittance);

    verifyLessThan( ...
        testCase, ...
        isoResult.Density, ...
        whiteResult.Density);
end


function testDifferentWavelengthGridsAreSupported(testCase)

    referenceWavelengthNm = (380:10:730).';
    sampleWavelengthNm = (380:5:730).';

    reference = struct( ...
        "WavelengthNm", referenceWavelengthNm, ...
        "Value", ones(size(referenceWavelengthNm)));

    sample = struct( ...
        "WavelengthNm", sampleWavelengthNm, ...
        "Value", 0.25 .* ones(size(sampleWavelengthNm)));

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyEqual( ...
        testCase, ...
        result.Transmittance, ...
        0.25, ...
        AbsTol=1e-10);

    verifyEqual( ...
        testCase, ...
        result.Density, ...
        -log10(0.25), ...
        AbsTol=1e-10);
end


function testZeroTransmissionProducesInfiniteDensity(testCase)

    [reference, sample] = localConstantTransmissionSpectra(0);

    result = spectralab.analysis.isoVisualDensity(reference, sample);

    verifyEqual(testCase, result.Transmittance, 0);
    verifyTrue(testCase, isinf(result.Density));
end


function testSampleAboveReferenceProducesWarning(testCase)

    [reference, sample] = localConstantTransmissionSpectra(1.1);

    verifyWarning( ...
        testCase, ...
        @() spectralab.analysis.isoVisualDensity(reference, sample), ...
        "spectralab:core:weightedDensity:TransmittanceAboveOne");
end


function testResamplingOptionsAreForwarded(testCase)

    wavelengthNm = (400:50:700).';

    reference = struct( ...
        "WavelengthNm", wavelengthNm, ...
        "Value", ones(size(wavelengthNm)));

    sample = struct( ...
        "WavelengthNm", wavelengthNm, ...
        "Value", 0.5 .* ones(size(wavelengthNm)));

    result = spectralab.analysis.isoVisualDensity( ...
        reference, ...
        sample, ...
        Resample=true, ...
        RefinementFactor=4, ...
        InterpolationMethod="pchip");

    verifyTrue(testCase, result.Resampled);
    verifyEqual(testCase, result.RefinementFactor, 4);
    verifyEqual(testCase, result.InterpolationMethod, "pchip");

    verifyEqual( ...
        testCase, ...
        result.Density, ...
        -log10(0.5), ...
        AbsTol=1e-12);
end


function [reference, sample] = ...
        localConstantTransmissionSpectra(transmittance)

    wavelengthNm = (380:10:730).';

    reference = struct( ...
        "WavelengthNm", wavelengthNm, ...
        "Value", ones(size(wavelengthNm)));

    sample = struct( ...
        "WavelengthNm", wavelengthNm, ...
        "Value", transmittance .* ones(size(wavelengthNm)));
end
