function tests = test_iso_visual_filter
%TEST_ISO_VISUAL_FILTER Tests for the ISO visual spectral product.

    tests = functiontests(localfunctions);
end


function testReturnsSpectralFilter(testCase)

    filter = spectralab.filters.isoVisual();

    verifyClass( ...
        testCase, ...
        filter, ...
        "spectralab.core.SpectralFilter");

    verifyEqual( ...
        testCase, ...
        filter.Name, ...
        "ISO visual density spectral product");

    verifyEqual( ...
        testCase, ...
        filter.Representation, ...
        "table");
end


function testIsNormalized(testCase)

    filter = spectralab.filters.isoVisual();

    verifyEqual( ...
        testCase, ...
        max(filter.Value), ...
        1, ...
        "AbsTol", 1e-12);

    verifyGreaterThanOrEqual( ...
        testCase, ...
        filter.Value, ...
        zeros(size(filter.Value)));
end


function testHasExpectedRange(testCase)

    filter = spectralab.filters.isoVisual();

    verifyGreaterThanOrEqual( ...
        testCase, ...
        filter.RangeNm(1), ...
        360);

    verifyLessThanOrEqual( ...
        testCase, ...
        filter.RangeNm(2), ...
        830);

    verifyGreaterThan( ...
        testCase, ...
        diff(filter.RangeNm), ...
        0);
end


function testEvaluationIsFinite(testCase)

    filter = spectralab.filters.isoVisual();

    wavelengthNm = linspace( ...
        filter.RangeNm(1), ...
        filter.RangeNm(2), ...
        101);

    value = filter.evaluate(wavelengthNm);

    verifySize(testCase, value, size(wavelengthNm));
    verifyTrue(testCase, all(isfinite(value)));
    verifyGreaterThanOrEqual( ...
        testCase, ...
        value, ...
        zeros(size(value)));
end


function testMatchesStoredTableAtOriginalPoints(testCase)

    filter = spectralab.filters.isoVisual();

    actual = filter.evaluate(filter.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        actual(:), ...
        filter.Value(:), ...
        "AbsTol", 1e-12);
end