function tests = test_analysis_transmission
%TEST_ANALYSIS_TRANSMISSION Tests for spectralab.analysis.transmission.

    tests = functiontests(localfunctions);
end


function testIdenticalGridsWithoutResamplingUseMeasuredValues(testCase)

    wavelength = (400:10:700).';

    referenceValue = ones(size(wavelength));
    sampleValue = 0.5 .* ones(size(wavelength));

    referenceArchive = makeArchive( ...
        wavelength, ...
        referenceValue, ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        sampleValue, ...
        "Sample");

    result = spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        Resample=false, ...
        WarnAboveOne=false);

    verifyEqual( ...
        testCase, ...
        result.Result.WavelengthNm, ...
        wavelength);

    verifyEqual( ...
        testCase, ...
        result.Result.Value, ...
        0.5 .* ones(size(wavelength)), ...
        AbsTol=1e-12);

    verifyEqual( ...
        testCase, ...
        result.Parameters.Alignment, ...
        "Exact");

    verifyFalse( ...
        testCase, ...
        result.Parameters.Resampled);
end


function testIdenticalGridsAreRefinedWhenResamplingEnabled(testCase)

    wavelength = (400:10:700).';

    referenceValue = ones(size(wavelength));
    sampleValue = 0.5 .* ones(size(wavelength));

    referenceArchive = makeArchive( ...
        wavelength, ...
        referenceValue, ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        sampleValue, ...
        "Sample");

    result = spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        Resample=true, ...
        RefinementFactor=2, ...
        InterpolationMethod="pchip", ...
        WarnAboveOne=false);

    expectedSampleCount = ...
        (numel(wavelength) - 1) * 2 + 1;

    verifyEqual( ...
        testCase, ...
        numel(result.Result.WavelengthNm), ...
        expectedSampleCount);

    verifyEqual( ...
        testCase, ...
        result.Result.WavelengthNm(1), ...
        wavelength(1));

    verifyEqual( ...
        testCase, ...
        result.Result.WavelengthNm(end), ...
        wavelength(end));

    verifyEqual( ...
        testCase, ...
        result.Result.Value, ...
        0.5 .* ones(expectedSampleCount, 1), ...
        AbsTol=1e-12);

    verifyEqual( ...
        testCase, ...
        result.Parameters.Alignment, ...
        "Interpolated");

    verifyTrue( ...
        testCase, ...
        result.Parameters.Resampled);

    verifyEqual( ...
        testCase, ...
        result.Parameters.RefinementFactor, ...
        2);

    verifyEqual( ...
        testCase, ...
        result.Parameters.InterpolationMethod, ...
        "pchip");
end


function testRefinementFactorFourCreatesExpectedGrid(testCase)

    wavelength = (380:10:730).';

    referenceValue = ones(size(wavelength));
    sampleValue = 0.25 .* ones(size(wavelength));

    referenceArchive = makeArchive( ...
        wavelength, ...
        referenceValue, ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        sampleValue, ...
        "Sample");

    result = spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        Resample=true, ...
        RefinementFactor=4, ...
        WarnAboveOne=false);

    expectedSampleCount = ...
        (numel(wavelength) - 1) * 4 + 1;

    verifyEqual( ...
        testCase, ...
        expectedSampleCount, ...
        141);

    verifyEqual( ...
        testCase, ...
        numel(result.Result.WavelengthNm), ...
        expectedSampleCount);

    verifyEqual( ...
        testCase, ...
        result.Result.Value, ...
        0.25 .* ones(expectedSampleCount, 1), ...
        AbsTol=1e-12);
end


function testDifferentGridsWithoutResamplingThrowError(testCase)

    referenceWavelength = (400:10:700).';
    sampleWavelength = (405:10:695).';

    referenceArchive = makeArchive( ...
        referenceWavelength, ...
        ones(size(referenceWavelength)), ...
        "Reference");

    sampleArchive = makeArchive( ...
        sampleWavelength, ...
        0.5 .* ones(size(sampleWavelength)), ...
        "Sample");

    verifyError( ...
        testCase, ...
        @() spectralab.analysis.transmission( ...
            referenceArchive, ...
            sampleArchive, ...
            Resample=false), ...
        "SpectraLab:Analysis:WavelengthMismatch");
end


function testDifferentGridsAreAlignedWhenResamplingEnabled(testCase)

    referenceWavelength = (400:10:700).';
    sampleWavelength = (405:10:695).';

    referenceValue = ones(size(referenceWavelength));
    sampleValue = 0.5 .* ones(size(sampleWavelength));

    referenceArchive = makeArchive( ...
        referenceWavelength, ...
        referenceValue, ...
        "Reference");

    sampleArchive = makeArchive( ...
        sampleWavelength, ...
        sampleValue, ...
        "Sample");

    result = spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        Resample=true, ...
        RefinementFactor=2, ...
        WarnAboveOne=false);

    verifyGreaterThanOrEqual( ...
        testCase, ...
        result.Result.WavelengthNm(1), ...
        405);

    verifyLessThanOrEqual( ...
        testCase, ...
        result.Result.WavelengthNm(end), ...
        695);

    verifyEqual( ...
        testCase, ...
        result.Result.Value, ...
        0.5 .* ones(size(result.Result.Value)), ...
        AbsTol=1e-12);

    verifyEqual( ...
        testCase, ...
        result.Parameters.Alignment, ...
        "Interpolated");

    verifyTrue( ...
        testCase, ...
        result.Parameters.Resampled);
end


function testIdenticalSignalsGiveUnityTransmission(testCase)

    wavelength = (400:10:700).';
    value = linspace(0.2, 1.0, numel(wavelength)).';

    referenceArchive = makeArchive( ...
        wavelength, ...
        value, ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        value, ...
        "Sample");

    result = spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        WarnAboveOne=false);

    verifyEqual( ...
        testCase, ...
        result.Result.Value, ...
        ones(size(wavelength)), ...
        AbsTol=1e-12);
end


function testWarnsWhenTransmissionExceedsOne(testCase)

    wavelength = (400:10:700).';

    referenceArchive = makeArchive( ...
        wavelength, ...
        ones(size(wavelength)), ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        1.1 .* ones(size(wavelength)), ...
        "Sample");

    verifyWarning( ...
        testCase, ...
        @() spectralab.analysis.transmission( ...
            referenceArchive, ...
            sampleArchive, ...
            WarnAboveOne=true), ...
        "SpectraLab:Analysis:TransmittanceAboveOne");
end


function testWarningCanBeDisabled(testCase)

    wavelength = (400:10:700).';

    referenceArchive = makeArchive( ...
        wavelength, ...
        ones(size(wavelength)), ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        1.1 .* ones(size(wavelength)), ...
        "Sample");

    lastwarn("");

    spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        WarnAboveOne=false);

    [~, warningIdentifier] = lastwarn;

    verifyEmpty( ...
        testCase, ...
        warningIdentifier);
end


function testZeroReferenceValueThrowsError(testCase)

    wavelength = (400:10:700).';

    referenceValue = ones(size(wavelength));
    referenceValue(5) = 0;

    referenceArchive = makeArchive( ...
        wavelength, ...
        referenceValue, ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        0.5 .* ones(size(wavelength)), ...
        "Sample");

    verifyError( ...
        testCase, ...
        @() spectralab.analysis.transmission( ...
            referenceArchive, ...
            sampleArchive), ...
        "SpectraLab:Analysis:InvalidReferenceSignal");
end


function testResultContainsExpectedProvenance(testCase)

    wavelength = (400:10:700).';

    referenceArchive = makeArchive( ...
        wavelength, ...
        ones(size(wavelength)), ...
        "Reference");

    sampleArchive = makeArchive( ...
        wavelength, ...
        0.5 .* ones(size(wavelength)), ...
        "Sample");

    result = spectralab.analysis.transmission( ...
        referenceArchive, ...
        sampleArchive, ...
        Resample=true, ...
        RefinementFactor=4, ...
        InterpolationMethod="makima", ...
        WarnAboveOne=false);

    verifyEqual( ...
        testCase, ...
        result.Definition.Type, ...
        "TransmissionSpectrum");

    verifyEqual( ...
        testCase, ...
        result.Definition.Method, ...
        "SampleReferenceRatio");

    verifyEqual( ...
        testCase, ...
        result.Parameters.Alignment, ...
        "Interpolated");

    verifyTrue( ...
        testCase, ...
        result.Parameters.Resampled);

    verifyEqual( ...
        testCase, ...
        result.Parameters.RefinementFactor, ...
        4);

    verifyEqual( ...
        testCase, ...
        result.Parameters.InterpolationMethod, ...
        "makima");

    verifyEqual( ...
        testCase, ...
        result.Parameters.EffectiveWavelengthRangeNm, ...
        [400, 700]);

    verifyNotEmpty( ...
        testCase, ...
        result.Identity.ContentHash);
end


	function archive = makeArchive(wavelength, value, measurementName)
	%MAKEARCHIVE Create a minimal valid SpectraLab archive for testing.

	    archive = struct();


	    %% Identity

	    archive.Identity = struct();

	    archive.Identity.UUID = ...
	        string(java.util.UUID.randomUUID);

	    archive.Identity.Created = ...
	        datetime("now", "TimeZone", "UTC");

	    archive.Identity.CreatedBy = ...
	        "SpectraLab test";

	    archive.Identity.HashAlgorithm = ...
	        "SHA-256";

	    archive.Identity.ContentHash = ...
	        "";


	    %% Version

	    archive.Version = struct();

	    archive.Version.Format = ...
	        "SLAB-MAT";

	    archive.Version.Version = ...
	        "0.6";

	    archive.Version.Software = ...
	        spectralab.version();


	    %% Measurement

	    archive.Measurement = struct();

	    archive.Measurement.Name = ...
	        string(measurementName);

	    archive.Measurement.Timestamp = ...
	        datetime("now", "TimeZone", "UTC");

	    archive.Measurement.Wavelength = ...
	        double(wavelength(:));

	    archive.Measurement.Value = ...
	        double(value(:));

	    archive.Measurement.Mode = ...
	        "Emission";

	    archive.Measurement.Operator = ...
	        "SpectraLab test";


	    %% Metadata

	    archive.Metadata = struct();


	    %% Instrument

	    archive.Instrument = struct();

	    archive.Instrument.Name = ...
	        "Synthetic test instrument";

	    archive.Instrument.SerialNumber = ...
	        "TEST-001";


	    %% Quality

	    archive.Quality = struct();


	    %% History

	    archive.History = struct.empty;


	    %% Calculate the canonical archive content hash

	    payload = struct();

	    payload.Measurement = ...
	        archive.Measurement;

	    payload.Instrument = ...
	        archive.Instrument;

	    payload.Quality = ...
	        archive.Quality;

	    archive.Identity.ContentHash = ...
	        spectralab.archive.contentHash(payload);
	end