function tests = test_core_resampleSpectrumPair

    tests = functiontests(localfunctions);

end


function testReturnsTwoRefinedSpectra(testCase)

    referenceSpec = createReferenceSpectrum();
    sampleSpec = createSampleSpectrum();

    [referenceResult, sampleResult] = ...
        spectralab.core.resampleSpectrumPair( ...
            referenceSpec, ...
            sampleSpec, ...
            RefinementFactor=4);

    verifyEqual( ...
        testCase, ...
        referenceResult.WavelengthNm, ...
        (380:2.5:400).', ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        sampleResult.WavelengthNm, ...
        (385:2.5:405).', ...
        "AbsTol", 1e-12);

end


function testUsesSameInterpolationSettings(testCase)

    referenceSpec = createReferenceSpectrum();
    sampleSpec = createSampleSpectrum();

    [referenceResult, sampleResult] = ...
        spectralab.core.resampleSpectrumPair( ...
            referenceSpec, ...
            sampleSpec, ...
            RefinementFactor=2, ...
            Method="pchip");

    expectedReference = spectralab.core.resampleSpectrum( ...
        referenceSpec, ...
        RefinementFactor=2, ...
        Method="pchip");

    expectedSample = spectralab.core.resampleSpectrum( ...
        sampleSpec, ...
        RefinementFactor=2, ...
        Method="pchip");

    verifyEqual( ...
        testCase, ...
        referenceResult.WavelengthNm, ...
        expectedReference.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        referenceResult.Power, ...
        expectedReference.Power, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        sampleResult.WavelengthNm, ...
        expectedSample.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        sampleResult.Power, ...
        expectedSample.Power, ...
        "AbsTol", 1e-12);

end


function testFactorOneReturnsOriginalData(testCase)

    referenceSpec = createReferenceSpectrum();
    sampleSpec = createSampleSpectrum();

    [referenceResult, sampleResult] = ...
        spectralab.core.resampleSpectrumPair( ...
            referenceSpec, ...
            sampleSpec, ...
            RefinementFactor=1);

    verifyEqual( ...
        testCase, ...
        referenceResult.WavelengthNm, ...
        referenceSpec.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        referenceResult.Power, ...
        referenceSpec.Power);

    verifyEqual( ...
        testCase, ...
        sampleResult.WavelengthNm, ...
        sampleSpec.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        sampleResult.Power, ...
        sampleSpec.Power);

end


function testDifferentWavelengthRangesAreAllowed(testCase)

    referenceSpec = spectralab.core.Spectrum( ...
        [380; 390; 400], ...
        [1.0; 2.0; 1.5]);

    sampleSpec = spectralab.core.Spectrum( ...
        [390; 400; 410; 420], ...
        [0.8; 1.2; 1.0; 0.7]);

    [referenceResult, sampleResult] = ...
        spectralab.core.resampleSpectrumPair( ...
            referenceSpec, ...
            sampleSpec, ...
            RefinementFactor=2);

    verifyEqual(testCase, referenceResult.WavelengthNm(1), 380);
    verifyEqual(testCase, referenceResult.WavelengthNm(end), 400);

    verifyEqual(testCase, sampleResult.WavelengthNm(1), 390);
    verifyEqual(testCase, sampleResult.WavelengthNm(end), 420);

end


function testDefaultMatchesExplicitSettings(testCase)

    referenceSpec = createReferenceSpectrum();
    sampleSpec = createSampleSpectrum();

    [defaultReference, defaultSample] = ...
        spectralab.core.resampleSpectrumPair( ...
            referenceSpec, ...
            sampleSpec);

    [explicitReference, explicitSample] = ...
        spectralab.core.resampleSpectrumPair( ...
            referenceSpec, ...
            sampleSpec, ...
            RefinementFactor=4, ...
            Method="pchip");

    verifyEqual( ...
        testCase, ...
        defaultReference.WavelengthNm, ...
        explicitReference.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        defaultReference.Power, ...
        explicitReference.Power, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        defaultSample.WavelengthNm, ...
        explicitSample.WavelengthNm);

    verifyEqual( ...
        testCase, ...
        defaultSample.Power, ...
        explicitSample.Power, ...
        "AbsTol", 1e-12);

end


function referenceSpec = createReferenceSpectrum()

    referenceSpec = spectralab.core.Spectrum( ...
        [380; 390; 400], ...
        [1.0; 2.0; 1.5]);

end


function sampleSpec = createSampleSpectrum()

    sampleSpec = spectralab.core.Spectrum( ...
        [385; 395; 405], ...
        [0.5; 1.0; 0.6]);

end