function tests = test_core_resampleSpectrum

    tests = functiontests(localfunctions);

end


function testFactorFourCreatesExpectedGrid(testCase)

    spec = createTestSpectrum();

    result = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4);

    expectedWavelengthNm = (380:2.5:400).';

    verifyEqual( ...
        testCase, ...
        result.WavelengthNm, ...
        expectedWavelengthNm, ...
        "AbsTol", 1e-12);

end


function testOriginalWavelengthsArePreserved(testCase)

    spec = createTestSpectrum();

    result = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4);

    for wavelengthNm = spec.WavelengthNm(:).'
        verifyTrue( ...
            testCase, ...
            any(abs(result.WavelengthNm - wavelengthNm) < 1e-12));
    end

end


function testOriginalPowerValuesArePreserved(testCase)

    spec = createTestSpectrum();

    result = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4);

    for index = 1:numel(spec.WavelengthNm)

        position = find( ...
            abs(result.WavelengthNm - spec.WavelengthNm(index)) < 1e-12, ...
            1);

        verifyEqual( ...
            testCase, ...
            result.Power(position), ...
            spec.Power(index), ...
            "AbsTol", 1e-12);
    end

end


function testEndpointsArePreserved(testCase)

    spec = createTestSpectrum();

    result = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4);

    verifyEqual( ...
        testCase, ...
        result.WavelengthNm(1), ...
        spec.WavelengthNm(1));

    verifyEqual( ...
        testCase, ...
        result.WavelengthNm(end), ...
        spec.WavelengthNm(end));

end


function testDoesNotExtrapolate(testCase)

    spec = createTestSpectrum();

    result = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4);

    verifyGreaterThanOrEqual( ...
        testCase, ...
        min(result.WavelengthNm), ...
        min(spec.WavelengthNm));

    verifyLessThanOrEqual( ...
        testCase, ...
        max(result.WavelengthNm), ...
        max(spec.WavelengthNm));

end


function testFactorOneReturnsOriginalSpectrum(testCase)

    spec = createTestSpectrum();

    result = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=1);

    verifyEqual(testCase, result.WavelengthNm, spec.WavelengthNm);
    verifyEqual(testCase, result.Power, spec.Power);

end


function testPchipIsDefaultMethod(testCase)

    spec = createTestSpectrum();

    defaultResult = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4);

    explicitResult = spectralab.core.resampleSpectrum( ...
        spec, ...
        RefinementFactor=4, ...
        Method="pchip");

    verifyEqual( ...
        testCase, ...
        defaultResult.Power, ...
        explicitResult.Power, ...
        "AbsTol", 1e-12);

end


function testRejectsInvalidRefinementFactor(testCase)

    spec = createTestSpectrum();

    verifyError( ...
        testCase, ...
        @() spectralab.core.resampleSpectrum( ...
            spec, ...
            RefinementFactor=0), ...
        "MATLAB:validators:mustBeGreaterThanOrEqual");

end


function spec = createTestSpectrum()

    wavelengthNm = [380; 390; 400];
    power = [1.0; 2.0; 1.5];

    spec = spectralab.core.Spectrum( ...
        wavelengthNm, ...
        power);

end