function tests = test_archive_metadata_propagation
%TEST_ARCHIVE_METADATA_PROPAGATION Tests META-001 and existing Operator flow.
tests = functiontests(localfunctions);
end

function testOperatorAndInstrumentAreArchived(testCase)
instrument = struct( ...
    "Name", "X-Rite i1Pro 2", ...
    "Driver", "spotread", ...
    "SerialNumber", "1001799");

calibration = struct("CalibrationID", "CAL-TEST-001");

metadata = struct( ...
    "Operator", "Christer Törnkvist", ...
    "Comment", "Metadata propagation test");

spec = spectralab.core.Spectrum( ...
    (380:10:730)', ...
    ones(36,1), ...
    "Metadata test", ...
    instrument, ...
    calibration, ...
    metadata, ...
    "arbitrary");

archive = spectralab.archive.create(spec);

verifyEqual(testCase, archive.Measurement.Operator, ...
    "Christer Törnkvist");
verifyEqual(testCase, archive.Metadata.Comment, ...
    "Metadata propagation test");
verifyEqual(testCase, archive.Instrument.Name, ...
    "X-Rite i1Pro 2");
verifyEqual(testCase, archive.Instrument.Driver, ...
    "spotread");
verifyEqual(testCase, archive.Instrument.SerialNumber, ...
    "1001799");
verifyEqual(testCase, archive.Instrument.CalibrationID, ...
    "CAL-TEST-001");
end

function testCommonAliasesAreAccepted(testCase)
instrument = struct( ...
    "model", "X-Rite i1Pro 2", ...
    "backend", "spotread", ...
    "serial", "1001799");

calibration = struct("id", "CAL-ALIAS");

spec = spectralab.core.Spectrum( ...
    (380:10:730)', ...
    ones(36,1), ...
    "Alias test", ...
    instrument, ...
    calibration, ...
    struct("Operator", "Test Operator"), ...
    "arbitrary");

archive = spectralab.archive.create(spec);

verifyEqual(testCase, archive.Instrument.Name, ...
    "X-Rite i1Pro 2");
verifyEqual(testCase, archive.Instrument.Driver, ...
    "spotread");
verifyEqual(testCase, archive.Instrument.SerialNumber, ...
    "1001799");
verifyEqual(testCase, archive.Instrument.CalibrationID, ...
    "CAL-ALIAS");
end

function testMissingInstrumentMetadataRemainsReadable(testCase)
spec = spectralab.core.Spectrum( ...
    (380:10:730)', ...
    ones(36,1), ...
    "Legacy-compatible test");

archive = spectralab.archive.create(spec);

verifyEqual(testCase, archive.Instrument.Name, "");
verifyEqual(testCase, archive.Instrument.Driver, "");
verifyEqual(testCase, archive.Instrument.SerialNumber, "");
verifyEqual(testCase, archive.Instrument.CalibrationID, "");
end
