% SpotreadInstrument bounded one-shot integration tests

thisFile = mfilename("fullpath");
testFolder = fileparts(thisFile);
helperFolder = fullfile(testFolder, "helpers");
fixtureFolder = fullfile(testFolder, "fixtures");
addpath(helperFolder);
pathCleanup = onCleanup(@() rmpath(helperFolder));

calibrationOutput = fileread(fullfile(fixtureFolder, ...
    "spotread_i1pro2_calibration_complete.txt"));
calibrationOutput = sprintf( ...
    "Instrument Type: X-Rite i1Pro 2\nSerial Number: 1234567\n%s", ...
    calibrationOutput);
measurementOutput = fileread(fullfile(fixtureFolder, ...
    "spotread_i1pro2_measurement_complete.txt"));
measurementFile = fullfile(fixtureFolder, ...
    "spotread_i1pro2_measurement_complete.sp");

runner = FakeOneShotRunner({ ...
    struct("output", calibrationOutput), ...
    struct("output", measurementOutput, ...
        "spectrum_file", measurementFile)});
inst = spectralab.drivers.SpotreadInstrument( ...
    "Executable", "/fake/spotread", ...
    "PythonExecutable", "/fake/python", ...
    "OneShotRunner", runner, ...
    "InstrumentSwitchSettleSeconds", 0, ...
    "PlacementConfirmation", @(~) []);
sess = spectralab.core.Session(inst, AudibleFeedback=false);
sess = sess.open();
sess = sess.calibrate("Mode", "automatic");
assert(sess.State == "CALIBRATED");
assert(inst.hasValidCalibration());
spec = sess.measure("Physical fixture", "Mode", "automatic");
assert(isa(spec, "spectralab.core.Spectrum"));
assert(numel(spec.Power) == 36);
assert(all(spec.Power > 0));
assert(spec.Metadata.one_shot);
assert(spec.Metadata.skip_initial_calibration);
assert(~spec.Metadata.high_resolution);
assert(any(runner.Calls{1} == "-O"));
assert(any(runner.Calls{1} == "-v"));
assert(~any(runner.Calls{1} == "-N"));
assert(any(runner.Calls{2} == "-N"));
assert(any(runner.Calls{2} == "-O"));
assert(any(runner.Calls{2} == "-v"));
assert(spec.Instrument.serial_number == "1234567");
archive = spectralab.archive.create(spec);
assert(archive.Instrument.SerialNumber == "1234567");

eventRecorder = EventRecorder();
timingRunner = FakeOneShotRunner({ ...
    struct("output", calibrationOutput), ...
    struct("output", measurementOutput, ...
        "spectrum_file", measurementFile)});
timingInst = spectralab.drivers.SpotreadInstrument( ...
    "Executable", "/fake/spotread", ...
    "PythonExecutable", "/fake/python", ...
    "OneShotRunner", timingRunner, ...
    "InstrumentSwitchSettleSeconds", 0, ...
    "PlacementConfirmation", ...
        @(~) eventRecorder.record("prompt"));
timingInst.setOperationStartFeedback( ...
    @() eventRecorder.record("start"));
timingInst.open();
timingInst.calibrate("automatic");
timingInst.measure("Feedback timing fixture", "automatic");
assert(isequal(eventRecorder.Events, ...
    ["start"; "prompt"; "start"; "prompt"]));

highRunner = FakeOneShotRunner({ ...
    struct("output", calibrationOutput), ...
    struct("output", measurementOutput, ...
        "spectrum_file", measurementFile)});
highInst = spectralab.drivers.SpotreadInstrument( ...
    "Executable", "/fake/spotread", ...
    "PythonExecutable", "/fake/python", ...
    "OneShotRunner", highRunner, ...
    "HighResolution", true, ...
    "InstrumentSwitchSettleSeconds", 0, ...
    "PlacementConfirmation", @(~) []);
highSession = spectralab.core.Session(highInst, AudibleFeedback=false);
highSession = highSession.open();
highSession = highSession.calibrate("Mode", "automatic");
highSpec = highSession.measure( ...
    "High-resolution command fixture", "Mode", "automatic");
assert(any(highRunner.Calls{1} == "-H"));
assert(any(highRunner.Calls{2} == "-H"));
assert(highSpec.Metadata.high_resolution);
assert(highSpec.Calibration.data.high_resolution);

darkText = fileread(fullfile(fixtureFolder, ...
    "spotread_i1pro2_dark_measurement.txt"));
darkRunner = FakeOneShotRunner({ ...
    struct("output", calibrationOutput), ...
    struct("output", darkText, "spectrum_file", fullfile( ...
        fixtureFolder, "spotread_i1pro2_dark_measurement.sp"))});
darkInst = spectralab.drivers.SpotreadInstrument( ...
    "Executable", "/fake/spotread", ...
    "PythonExecutable", "/fake/python", ...
    "OneShotRunner", darkRunner, ...
    "InstrumentSwitchSettleSeconds", 0, ...
    "PlacementConfirmation", @(~) []);
darkSession = spectralab.core.Session(darkInst, AudibleFeedback=false);
darkSession = darkSession.open();
darkSession = darkSession.calibrate("Mode", "automatic");
failed = false;
caughtIdentifier = "";
try
    darkSession.measure("Dark fixture", "Mode", "automatic");
catch ME
    caughtIdentifier = string(ME.identifier);
    failed = strcmp(ME.identifier, ...
        "SpectraLab:Spotread:NoLightDetected");
end
assert(failed, "Unexpected error: %s", caughtIdentifier);

failedCalibrationRunner = FakeOneShotRunner({ ...
    struct("output", "Calibration failed", "status", 1)});
failedInst = spectralab.drivers.SpotreadInstrument( ...
    "Executable", "/fake/spotread", ...
    "PythonExecutable", "/fake/python", ...
    "OneShotRunner", failedCalibrationRunner, ...
    "InstrumentSwitchSettleSeconds", 0, ...
    "PlacementConfirmation", @(~) []);
failedSession = spectralab.core.Session(failedInst, AudibleFeedback=false);
failedSession = failedSession.open();
failed = false;
try
    failedSession.calibrate("Mode", "automatic");
catch ME
    failed = strcmp(ME.identifier, ...
        "SpectraLab:Spotread:OneShotCalibrationFailed");
end
assert(failed);
assert(~failedInst.hasValidCalibration());

fprintf("test_spotread_oneShotInstrument OK\n");
