function tests = test_transmission_density
%TEST_TRANSMISSION_DENSITY Tests canonical transmission-density analysis.

    tests = functiontests(localfunctions);
end


function setupOnce(testCase)
% Create valid mock archives using the public SpectraLab workflow.

    inst = spectralab.drivers.MockInstrument();

    sess = spectralab.core.Session(inst);
    sess = sess.open();
    sess = sess.calibrate();

    referenceSpectrum = sess.measure("Density reference");
    sampleSpectrum = sess.measure("Density sample");

    referenceArchive = spectralab.archive.create(referenceSpectrum);
    sampleArchive = spectralab.archive.create(sampleSpectrum);

    rangeNm = [ ...
        max(min(referenceSpectrum.WavelengthNm), 400), ...
        min(max(referenceSpectrum.WavelengthNm), 700)];

    flatFilter = spectralab.filters.flat( ...
        rangeNm, ...
        Name="Density test flat filter");

    testCase.TestData.ReferenceArchive = referenceArchive;
    testCase.TestData.SampleArchive = sampleArchive;
    testCase.TestData.FlatFilter = flatFilter;
end


function testIdenticalArchivesGiveZeroDensity(testCase)

    archive = testCase.TestData.ReferenceArchive;
    filter = testCase.TestData.FlatFilter;

    result = spectralab.analysis.transmissionDensity( ...
        archive, ...
        archive, ...
        filter, ...
        WarnBelowTransmission=0, ...
        WarnAboveDensity=Inf);

    verifyEqual( ...
        testCase, ...
        result.Result.EffectiveTransmission, ...
        1, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        result.Result.Density, ...
        0, ...
        "AbsTol", 1e-12);
end


function testUsesCanonicalTransmissionPipeline(testCase)

    reference = testCase.TestData.ReferenceArchive;
    sample = testCase.TestData.SampleArchive;
    filter = testCase.TestData.FlatFilter;

    result = spectralab.analysis.transmissionDensity( ...
        reference, ...
        sample, ...
        filter, ...
        WarnBelowTransmission=0, ...
        WarnAboveDensity=Inf);

    verifyEqual(testCase, result.Type, "TransmissionDensity");
    verifyTrue(testCase, isfield(result, "Transmission"));
    verifyTrue(testCase, isfield(result, "FilterResponse"));

    verifyTrue(testCase, isfield(result.Transmission, "Result"));
    verifyTrue( ...
        testCase, ...
        isfield(result.Transmission.Result, "WavelengthNm"));
    verifyTrue( ...
        testCase, ...
        isfield(result.Transmission.Result, "Value"));

    verifyEqual( ...
        testCase, ...
        result.FilterResponse.Source.Type, ...
        "AnalysisResult");

	responseWavelength = ...
	    result.FilterResponse.Result.WavelengthNm(:);

	transmissionWavelength = ...
	    result.Transmission.Result.WavelengthNm(:);

	transmissionValue = ...
	    result.Transmission.Result.Value(:);

	[isPresent, location] = ismember( ...
	    responseWavelength, ...
	    transmissionWavelength);

	verifyTrue(testCase, all(isPresent));

	verifyEqual( ...
	    testCase, ...
	    result.FilterResponse.Result.InputValue(:), ...
	    transmissionValue(location), ...
	    "AbsTol", 1e-12);
end


function testNormalizedIntegrationMatchesReturnedValue(testCase)

    reference = testCase.TestData.ReferenceArchive;
    sample = testCase.TestData.SampleArchive;
    filter = testCase.TestData.FlatFilter;

    result = spectralab.analysis.transmissionDensity( ...
        reference, ...
        sample, ...
        filter, ...
        WarnBelowTransmission=0, ...
        WarnAboveDensity=Inf);

    response = result.FilterResponse;

    expectedTransmission = ...
        trapz( ...
            response.Result.WavelengthNm, ...
            response.Result.Value) / ...
        trapz( ...
            response.Result.WavelengthNm, ...
            response.Result.FilterValue);

    expectedDensity = -log10(expectedTransmission);

    verifyEqual( ...
        testCase, ...
        result.Result.EffectiveTransmission, ...
        expectedTransmission, ...
        "AbsTol", 1e-12);

    verifyEqual( ...
        testCase, ...
        result.Result.Density, ...
        expectedDensity, ...
        "AbsTol", 1e-12);
end


function testStoresIntegrationProvenance(testCase)

    archive = testCase.TestData.ReferenceArchive;
    filter = testCase.TestData.FlatFilter;

    result = spectralab.analysis.transmissionDensity( ...
        archive, ...
        archive, ...
        filter, ...
        WarnBelowTransmission=0, ...
        WarnAboveDensity=Inf);

    verifyEqual( ...
        testCase, ...
        result.Processing.IntegrationMethod, ...
        "trapezoidal");

    verifyEqual( ...
        testCase, ...
        result.Processing.Normalization, ...
        "integral(filter)");

    verifyTrue( ...
        testCase, ...
        contains(result.Processing.Pipeline, "filterResponse"));
end


function testSupportsRequestedWavelengthRange(testCase)

    archive = testCase.TestData.ReferenceArchive;
    filter = testCase.TestData.FlatFilter;

    requestedRange = [420 680];

    result = spectralab.analysis.transmissionDensity( ...
        archive, ...
        archive, ...
        filter, ...
        WavelengthRange=requestedRange, ...
        WarnBelowTransmission=0, ...
        WarnAboveDensity=Inf);

    verifyEqual( ...
        testCase, ...
        result.Range.EffectiveRangeNm, ...
        requestedRange);
end


function testRejectsPartlySpecifiedRange(testCase)

    archive = testCase.TestData.ReferenceArchive;
    filter = testCase.TestData.FlatFilter;

    verifyError( ...
        testCase, ...
        @() spectralab.analysis.transmissionDensity( ...
            archive, ...
            archive, ...
            filter, ...
            WavelengthRange=[400 NaN]), ...
        "spectralab:analysis:transmissionDensity:InvalidRange");
end


function testDensityWarningsCanBeDisabled(testCase)
% Use identical archives so analysis.transmission itself emits no warning.
% This isolates the warning controls owned by transmissionDensity.

    archive = testCase.TestData.ReferenceArchive;
    filter = testCase.TestData.FlatFilter;

    verifyWarningFree( ...
        testCase, ...
        @() spectralab.analysis.transmissionDensity( ...
            archive, ...
            archive, ...
            filter, ...
            WarnBelowTransmission=0, ...
            WarnAboveDensity=Inf));
end
