function tests = test_archive_roundtrip_integrity
%TEST_ARCHIVE_ROUNDTRIP_INTEGRITY End-to-end ARCH-006 tests.
tests = functiontests(localfunctions);
end

function testScientificDataAndMetadataSurviveRoundTrip(testCase)
filename = tempname + ".mat";
cleanup = onCleanup(@() deleteIfExists(filename));

instrument = struct( ...
    "Name", "X-Rite i1Pro 2", ...
    "Driver", "spotread", ...
    "SerialNumber", "1001799");

calibration = struct("CalibrationID", "CAL-ROUNDTRIP-001");

metadata = struct( ...
    "Operator", "Christer Törnkvist", ...
    "Project", "CSW Filter Study", ...
    "SampleID", "SAM-10B", ...
    "Comment", "Round-trip integrity test");

wavelength = (380:10:730)';
power = linspace(0.1, 1.0, numel(wavelength))';

specOriginal = spectralab.core.Spectrum( ...
    wavelength, ...
    power, ...
    "ARCH-006 round trip", ...
    instrument, ...
    calibration, ...
    metadata, ...
    "arbitrary");

archiveCreated = spectralab.archive.create(specOriginal);
spectralab.archive.save(archiveCreated, filename);

archiveLoaded = spectralab.archive.load( ...
    filename, Quiet=true, Validation="error");

specRestored = spectralab.archive.restore( ...
    archiveLoaded, Validation="error");

verifyEqual(testCase, specRestored.WavelengthNm, wavelength);
verifyEqual(testCase, specRestored.Power, power);
verifyEqual(testCase, specRestored.Label, "ARCH-006 round trip");
verifyEqual(testCase, specRestored.PowerUnit, "arbitrary");

verifyEqual(testCase, specRestored.Metadata.Operator, ...
    "Christer Törnkvist");
verifyEqual(testCase, specRestored.Metadata.Project, ...
    "CSW Filter Study");
verifyEqual(testCase, specRestored.Metadata.SampleID, ...
    "SAM-10B");
verifyEqual(testCase, specRestored.Metadata.Comment, ...
    "Round-trip integrity test");

verifyEqual(testCase, specRestored.Instrument.Name, ...
    "X-Rite i1Pro 2");
verifyEqual(testCase, specRestored.Instrument.Driver, ...
    "spotread");
verifyEqual(testCase, specRestored.Instrument.SerialNumber, ...
    "1001799");
verifyEqual(testCase, specRestored.Calibration.CalibrationID, ...
    "CAL-ROUNDTRIP-001");
end

function testContentHashSurvivesSaveLoad(testCase)
filename = tempname + ".mat";
cleanup = onCleanup(@() deleteIfExists(filename));

archiveCreated = makeArchive();
spectralab.archive.save(archiveCreated, filename);

archiveLoaded = spectralab.archive.load( ...
    filename, Quiet=true, Validation="error");

verifyEqual(testCase, ...
    archiveLoaded.Identity.ContentHash, ...
    archiveCreated.Identity.ContentHash);
end

function testRecreatedArchiveHasSameScientificHash(testCase)
filename = tempname + ".mat";
cleanup = onCleanup(@() deleteIfExists(filename));

archiveCreated = makeArchive();
spectralab.archive.save(archiveCreated, filename);

archiveLoaded = spectralab.archive.load( ...
    filename, Quiet=true, Validation="error");

specRestored = spectralab.archive.restore( ...
    archiveLoaded, Validation="error");

archiveRecreated = spectralab.archive.create(specRestored);

verifyEqual(testCase, ...
    archiveRecreated.Identity.ContentHash, ...
    archiveCreated.Identity.ContentHash);

verifyNotEqual(testCase, ...
    archiveRecreated.Identity.UUID, ...
    archiveCreated.Identity.UUID);
end

function testRoundTripValidationRemainsClean(testCase)
filename = tempname + ".mat";
cleanup = onCleanup(@() deleteIfExists(filename));

archiveCreated = makeArchive();
spectralab.archive.save(archiveCreated, filename);

archiveLoaded = spectralab.archive.load( ...
    filename, Quiet=true, Validation="error");

validation = spectralab.archive.validate(archiveLoaded);

verifyTrue(testCase, validation.IsValid);
verifyEmpty(testCase, validation.Errors);
end

function archive = makeArchive()
instrument = struct( ...
    "Name", "X-Rite i1Pro 2", ...
    "Driver", "spotread", ...
    "SerialNumber", "1001799");

calibration = struct("CalibrationID", "CAL-ROUNDTRIP-001");

metadata = struct( ...
    "Operator", "Christer Törnkvist", ...
    "Project", "CSW Filter Study", ...
    "SampleID", "SAM-10B", ...
    "Comment", "Round-trip integrity test");

wavelength = (380:10:730)';
power = linspace(0.1, 1.0, numel(wavelength))';

spec = spectralab.core.Spectrum( ...
    wavelength, ...
    power, ...
    "ARCH-006 round trip", ...
    instrument, ...
    calibration, ...
    metadata, ...
    "arbitrary");

archive = spectralab.archive.create(spec);
end

function deleteIfExists(filename)
if isfile(filename)
    delete(filename);
end
end
