function comparison = compareDensityPairs( ...
        referenceA, sampleA, referenceB, sampleB, options)
%COMPAREDENSITYPAIRS Compare two independently calculated density spectra.
%
%   D_A(lambda) = -log10(sample_A(lambda) / reference_A(lambda))
%   D_B(lambda) = -log10(sample_B(lambda) / reference_B(lambda))

arguments
    referenceA (1,1) struct
    sampleA (1,1) struct
    referenceB (1,1) struct
    sampleB (1,1) struct
    options.Resample (1,1) logical = false
    options.RefinementFactor (1,1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.InterpolationMethod (1,1) string = "pchip"
    options.MinimumTransmittance (1,1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 1e-12
end

transmissionComparison = spectralab.analysis.compareTransmissionPairs( ...
    referenceA, sampleA, referenceB, sampleB, ...
    Resample=options.Resample, ...
    RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);

densityA = spectralab.analysis.opticalDensity( ...
    transmissionComparison.Result.TransmissionA, ...
    MinimumTransmittance=options.MinimumTransmittance);
densityB = spectralab.analysis.opticalDensity( ...
    transmissionComparison.Result.TransmissionB, ...
    MinimumTransmittance=options.MinimumTransmittance);
difference = densityA - densityB;

comparison = struct();
comparison.Definition = struct( ...
    "Type", "DensityPairComparison", ...
    "ExpressionA", "D_A(lambda) = -log10(T_A(lambda))", ...
    "ExpressionB", "D_B(lambda) = -log10(T_B(lambda))");
comparison.Parameters = transmissionComparison.Parameters;
comparison.Parameters.MinimumTransmittance = options.MinimumTransmittance;
comparison.Result = struct( ...
    "WavelengthNm", transmissionComparison.Result.WavelengthNm, ...
    "DensityA", densityA, ...
    "DensityB", densityB, ...
    "Difference", difference, ...
    "RMSDifference", sqrt(mean(difference.^2)), ...
    "MaximumAbsoluteDifference", max(abs(difference)), ...
    "MeanDensityA", mean(densityA), ...
    "MeanDensityB", mean(densityB));
comparison.TransmissionComparison = transmissionComparison;
end
