function comparison = compareTransmissionPairs( ...
        referenceA, sampleA, referenceB, sampleB, options)
%COMPARETRANSMISSIONPAIRS Compare two independently calculated spectra.
%
%   Each transmission is calculated by spectralab.analysis.transmission:
%
%       T_A(lambda) = sampleA(lambda) / referenceA(lambda)
%       T_B(lambda) = sampleB(lambda) / referenceB(lambda)
%
%   The two resulting transmission spectra are then aligned on their common
%   wavelength range. References A and B may be the same archive, but need
%   not be.

arguments
    referenceA (1,1) struct
    sampleA (1,1) struct
    referenceB (1,1) struct
    sampleB (1,1) struct
    options.Resample (1,1) logical = false
    options.RefinementFactor (1,1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.InterpolationMethod (1,1) string = "pchip"
end

transmissionA = spectralab.analysis.transmission(referenceA, sampleA, ...
    Resample=options.Resample, ...
    RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);
transmissionB = spectralab.analysis.transmission(referenceB, sampleB, ...
    Resample=options.Resample, ...
    RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);

wavelengthA = transmissionA.Result.WavelengthNm(:);
wavelengthB = transmissionB.Result.WavelengthNm(:);
valueA = transmissionA.Result.Value(:);
valueB = transmissionB.Result.Value(:);

if isequal(wavelengthA, wavelengthB)
    wavelength = wavelengthA;
    alignment = "Exact";
else
    if ~options.Resample
        error("SpectraLab:Analysis:TransmissionComparisonWavelengthMismatch", ...
            ["The two transmission spectra use different wavelength grids. " ...
             "Set Resample=true to compare them on a common grid."]);
    end
    lowerNm = max(wavelengthA(1), wavelengthB(1));
    upperNm = min(wavelengthA(end), wavelengthB(end));
    if lowerNm >= upperNm
        error("SpectraLab:Analysis:NoCommonWavelengthRange", ...
            "The two transmission spectra have no common wavelength range.");
    end
    wavelength = unique([ ...
        wavelengthA(wavelengthA >= lowerNm & wavelengthA <= upperNm); ...
        wavelengthB(wavelengthB >= lowerNm & wavelengthB <= upperNm)]);
    valueA = interp1(wavelengthA, valueA, wavelength, ...
        options.InterpolationMethod);
    valueB = interp1(wavelengthB, valueB, wavelength, ...
        options.InterpolationMethod);
    alignment = "Interpolated";
end

difference = valueA - valueB;
comparison = struct();
comparison.Definition = struct( ...
    "Type", "TransmissionPairComparison", ...
    "ExpressionA", "T_A(lambda) = sample_A(lambda) / reference_A(lambda)", ...
    "ExpressionB", "T_B(lambda) = sample_B(lambda) / reference_B(lambda)");
comparison.Parameters = struct( ...
    "Alignment", alignment, ...
    "Resampled", options.Resample, ...
    "RefinementFactor", options.RefinementFactor, ...
    "InterpolationMethod", options.InterpolationMethod, ...
    "EffectiveWavelengthRangeNm", wavelength([1 end]).');
comparison.Result = struct( ...
    "WavelengthNm", wavelength, ...
    "TransmissionA", valueA, ...
    "TransmissionB", valueB, ...
    "Difference", difference, ...
    "RMSDifference", sqrt(mean(difference.^2)), ...
    "MaximumAbsoluteDifference", max(abs(difference)), ...
    "MeanTransmissionA", mean(valueA), ...
    "MeanTransmissionB", mean(valueB));
comparison.TransmissionA = transmissionA;
comparison.TransmissionB = transmissionB;
end
