function artifact = createTransmissionArtifact(reference, sample, options)
%CREATETRANSMISSIONARTIFACT Create one self-contained transmission package.
arguments
    reference (1,1) struct
    sample (1,1) struct
    options.ReferenceFile (1,1) string = ""
    options.SampleFile (1,1) string = ""
    options.Resample (1,1) logical = true
    options.RefinementFactor (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.InterpolationMethod (1,1) string = "pchip"
    options.Name (1,1) string = "Derived spectral transmission"
end

transmission = spectralab.analysis.transmission(reference, sample, ...
    Resample=options.Resample, RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);
[wavelength,value,contract] = spectralab.io.applyCamera41ExportContract( ...
    transmission.Result.WavelengthNm,transmission.Result.Value);
effectiveRange=[wavelength(1) wavelength(end)];
parameters=transmission.Parameters;
parameters.Camera41ExportContract=contract;
parameters.RequestedOutputWavelengthRangeNm=contract.WavelengthRangeNm;
parameters.EffectiveOutputWavelengthRangeNm=effectiveRange;

metadata = struct("Description","Derived spectral transmission", ...
    "measurement_kind","transmission", ...
    "signal_quantity","spectral_transmittance");
spec = spectralab.core.Spectrum(wavelength, value, options.Name, ...
    struct("Name","SpectraLab derived analysis", ...
        "Driver","spectralab.analysis.createTransmissionArtifact"), ...
    struct(), metadata, "1");
archive = spectralab.archive.create(spec);
archive.Measurement.Context.Origin = "derived";
archive.Derivation = struct( ...
    "Definition",transmission.Definition, ...
    "Parameters",parameters, ...
    "Sources",struct( ...
        "Reference",source(reference,options.ReferenceFile), ...
        "Sample",source(sample,options.SampleFile)), ...
    "Output",struct("Type","Spectrum","Cardinality",1, ...
        "Role","ReusableAnalysisInput"));
hashPayload = struct("Measurement",archive.Measurement, ...
    "Instrument",archive.Instrument,"Quality",archive.Quality, ...
    "Derivation",archive.Derivation);
archive.Identity.ContentHash = spectralab.archive.contentHash(hashPayload);

artifact = struct( ...
    "Schema","spectralab.spectral-artifact", ...
    "SchemaVersion","1.0", ...
    "Identity",struct(), ...
    "Origin","derived", ...
    "Kind","single_spectrum", ...
    "Quantity","spectral_transmittance", ...
    "Payload",struct("Archive",archive), ...
    "Provenance",archive.Derivation);
artifact.Identity = struct( ...
    "UUID",string(java.util.UUID.randomUUID), ...
    "Created",datetime("now","TimeZone","UTC"), ...
    "ContentHash",spectralab.archive.contentHash(rmfield(artifact,"Identity")));
end

function value = source(archive, filename)
value = struct("Filename",filename, ...
    "UUID",string(archive.Identity.UUID), ...
    "ContentHash",string(archive.Identity.ContentHash), ...
    "MeasurementName",string(archive.Measurement.Name));
end
