function analysis = spectralMean(firstArchive, secondArchive, options)
%SPECTRALMEAN Create a traceable mean spectrum from two archives.
%
%   analysis = spectralab.analysis.spectralMean(A, B)
%
% Result.DerivedArchive is a new archive whose scientific identity includes
% the method and the UUID/content hash of both source archives.

arguments
    firstArchive (1,1) struct
    secondArchive (1,1) struct
    options.Resample (1,1) logical = false
    options.RefinementFactor (1,1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.InterpolationMethod (1,1) string = "pchip"
    options.ResultName (1,1) string = "Spectral mean"
    options.SourceFiles (1,:) string = ["", ""]
end

if numel(options.SourceFiles) ~= 2
    error("SpectraLab:Analysis:InvalidSourceFiles", ...
        "SourceFiles must contain exactly two filenames.");
end

aligned = spectralab.analysis.internal.alignArchivePair( ...
    firstArchive, secondArchive, ...
    Resample=options.Resample, ...
    RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);
meanValue = (aligned.FirstValue + aligned.SecondValue) / 2;

sources = [sourceSummary(firstArchive, "Source A", options.SourceFiles(1)); ...
    sourceSummary(secondArchive, "Source B", options.SourceFiles(2))];
definition = struct( ...
    "AnalysisId", "ANL-009", ...
    "Type", "DerivedMeanSpectrum", ...
    "Method", "PointwiseArithmeticMean", ...
    "Expression", "M(lambda) = (A(lambda) + B(lambda)) / 2");
parameters = parameterSummary(aligned);

instrument = struct( ...
    "Name", "SpectraLab derived analysis", ...
    "Driver", "spectralab.analysis.spectralMean");
metadata = struct( ...
    "Description", "Derived arithmetic mean of two SpectraLab archives", ...
    "Comment", "Sources: " + displaySource(sources(1)) + ...
        "; " + displaySource(sources(2)));
spec = spectralab.core.Spectrum( ...
    aligned.WavelengthNm, meanValue, options.ResultName, ...
    instrument, struct(), metadata, aligned.Unit);
derivedArchive = spectralab.archive.create(spec);
derivedArchive.Derivation = struct( ...
    "Definition", definition, ...
    "Parameters", parameters, ...
    "Sources", sources);
payload = struct( ...
    "Measurement", derivedArchive.Measurement, ...
    "Instrument", derivedArchive.Instrument, ...
    "Quality", derivedArchive.Quality, ...
    "Derivation", derivedArchive.Derivation);
derivedArchive.Identity.ContentHash = ...
    spectralab.archive.contentHash(payload);

analysis = makeAnalysis(definition, parameters, sources, ...
    aligned.WavelengthNm, meanValue, aligned.Unit);
analysis.Result.DerivedArchive = derivedArchive;
end

function analysis = makeAnalysis(definition, parameters, sources, wavelength, value, unit)
analysis = struct();
analysis.Identity = struct( ...
    "UUID", string(java.util.UUID.randomUUID), ...
    "Created", datetime("now", "TimeZone", "UTC"), ...
    "CreatedBy", "spectralab.analysis.spectralMean");
analysis.Definition = definition;
analysis.Parameters = parameters;
analysis.Result = struct( ...
    "WavelengthNm", wavelength(:), "Value", value(:), "Unit", unit);
analysis.Sources = sources;
hashPayload = struct("Definition", definition, "Parameters", parameters, ...
    "Result", analysis.Result, "Sources", sources);
analysis.Identity.ContentHash = spectralab.archive.contentHash(hashPayload);
end

function parameters = parameterSummary(aligned)
parameters = struct( ...
    "Alignment", aligned.Alignment, ...
    "Resampled", aligned.Resampled, ...
    "RefinementFactor", aligned.RefinementFactor, ...
    "InterpolationMethod", aligned.InterpolationMethod, ...
    "EffectiveWavelengthRangeNm", ...
        aligned.WavelengthNm([1 end]).');
end

function source = sourceSummary(archive, role, filename)
source = struct( ...
    "Role", role, ...
    "Filename", string(filename), ...
    "MeasurementName", string(archive.Measurement.Name), ...
    "UUID", string(archive.Identity.UUID), ...
    "ContentHash", string(archive.Identity.ContentHash));
end

function value = displaySource(source)
value = source.Role + "=" + source.Filename + ...
    " [UUID " + source.UUID + "]";
end
