function analysis = spectralDifference(firstArchive, secondArchive, options)
%SPECTRALDIFFERENCE Calculate the signed spectrum A minus B.
%
% This diagnostic analysis is reportable but intentionally creates no
% derived MAT archive.

arguments
    firstArchive (1,1) struct
    secondArchive (1,1) struct
    options.Resample (1,1) logical = false
    options.RefinementFactor (1,1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.InterpolationMethod (1,1) string = "pchip"
    options.SourceFiles (1,:) string = ["", ""]
end

if numel(options.SourceFiles) ~= 2
    error("SpectraLab:Analysis:InvalidSourceFiles", ...
        "SourceFiles must contain exactly two filenames.");
end

aligned = spectralab.analysis.internal.alignArchivePair( ...
    firstArchive, secondArchive, ...
    Resample=options.Resample, ...
    RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);
difference = aligned.FirstValue - aligned.SecondValue;
sources = [sourceSummary(firstArchive, "Minuend (A)", options.SourceFiles(1)); ...
    sourceSummary(secondArchive, "Subtrahend (B)", options.SourceFiles(2))];

analysis = struct();
analysis.Identity = struct( ...
    "UUID", string(java.util.UUID.randomUUID), ...
    "Created", datetime("now", "TimeZone", "UTC"), ...
    "CreatedBy", "spectralab.analysis.spectralDifference");
analysis.Definition = struct( ...
    "AnalysisId", "ANL-010", ...
    "Type", "SpectralDifference", ...
    "Method", "PointwiseSignedDifference", ...
    "Expression", "D(lambda) = A(lambda) - B(lambda)");
analysis.Parameters = struct( ...
    "Alignment", aligned.Alignment, ...
    "Resampled", aligned.Resampled, ...
    "RefinementFactor", aligned.RefinementFactor, ...
    "InterpolationMethod", aligned.InterpolationMethod, ...
    "EffectiveWavelengthRangeNm", aligned.WavelengthNm([1 end]).');
analysis.Result = struct( ...
    "WavelengthNm", aligned.WavelengthNm, ...
    "Value", difference, ...
    "Unit", aligned.Unit, ...
    "RMSDifference", sqrt(mean(difference.^2)), ...
    "MaximumAbsoluteDifference", max(abs(difference)));
analysis.Sources = sources;
hashPayload = struct("Definition", analysis.Definition, ...
    "Parameters", analysis.Parameters, "Result", analysis.Result, ...
    "Sources", sources);
analysis.Identity.ContentHash = spectralab.archive.contentHash(hashPayload);
end

function source = sourceSummary(archive, role, filename)
source = struct( ...
    "Role", role, ...
    "Filename", string(filename), ...
    "MeasurementName", string(archive.Measurement.Name), ...
    "UUID", string(archive.Identity.UUID), ...
    "ContentHash", string(archive.Identity.ContentHash));
end
