function analysis = spectralMean(firstInput, secondArchive, options)
%SPECTRALMEAN Create a traceable mean spectrum from selected archives.
%
%   analysis = spectralab.analysis.spectralMean()
%       Opens a modal multi-file selection dialog.
%
%   analysis = spectralab.analysis.spectralMean(FILES)
%       FILES is a string array of two or more archive filenames.
%
%   analysis = spectralab.analysis.spectralMean(ARCHIVES)
%       ARCHIVES is a struct array or cell array of archive structures.
%
%   analysis = spectralab.analysis.spectralMean(A, B)
%       Backward-compatible two-archive form.

arguments
    firstInput = []
    secondArchive = []
    options.Resample (1,1) logical = false
    options.RefinementFactor (1,1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.InterpolationMethod (1,1) string = "pchip"
    options.ResultName (1,1) string = "Spectral mean"
    options.SourceFiles (1,:) string = strings(1,0)
end

[archives, sourceFiles] = resolveSources( ...
    firstInput, secondArchive, options.SourceFiles);
aligned = spectralab.analysis.internal.alignArchiveSet(archives, ...
    Resample=options.Resample, ...
    RefinementFactor=options.RefinementFactor, ...
    InterpolationMethod=options.InterpolationMethod);
meanValue = mean(aligned.ValueMatrix, 2);
statistics = stabilityStatistics(aligned.ValueMatrix, meanValue);

sources = repmat(sourceSummary(archives{1}, "Source 1", sourceFiles(1)), ...
    aligned.SourceCount, 1);
for index = 1:aligned.SourceCount
    sources(index) = sourceSummary(archives{index}, ...
        "Source " + index, sourceFiles(index));
end
definition = struct( ...
    "AnalysisId", "ANL-009", ...
    "Type", "DerivedMeanSpectrum", ...
    "Method", "PointwiseArithmeticMean", ...
    "Expression", "M(lambda) = sum(S_i(lambda)) / N");
parameters = parameterSummary(aligned);

instrument = struct( ...
    "Name", "SpectraLab derived analysis", ...
    "Driver", "spectralab.analysis.spectralMean");
sourceDescriptions = strings(1, aligned.SourceCount);
for index = 1:aligned.SourceCount
    sourceDescriptions(index) = displaySource(sources(index));
end
metadata = struct( ...
    "Description", "Derived arithmetic mean of " + ...
        aligned.SourceCount + " SpectraLab archives", ...
    "Comment", "Sources: " + strjoin(sourceDescriptions, "; "));
spec = spectralab.core.Spectrum( ...
    aligned.WavelengthNm, meanValue, options.ResultName, ...
    instrument, struct(), metadata, aligned.Unit);
derivedArchive = spectralab.archive.create(spec);
derivedArchive.Derivation = struct( ...
    "Definition", definition, ...
    "Parameters", parameters, ...
    "Statistics", statistics, ...
    "Sources", sources);
payload = struct( ...
    "Measurement", derivedArchive.Measurement, ...
    "Instrument", derivedArchive.Instrument, ...
    "Quality", derivedArchive.Quality, ...
    "Derivation", derivedArchive.Derivation);
derivedArchive.Identity.ContentHash = ...
    spectralab.archive.contentHash(payload);

analysis = makeAnalysis(definition, parameters, sources, ...
    aligned.WavelengthNm, meanValue, aligned.Unit, statistics);
analysis.Result.DerivedArchive = derivedArchive;
end

function [archives, sourceFiles] = resolveSources(firstInput, secondArchive, requestedFiles)
if isempty(firstInput) && isempty(secondArchive)
    sourceFiles = spectralab.ui.selectArchiveFiles(string(pwd), ...
        Title="Select spectra for arithmetic mean", ...
        MinimumSelection=2);
    if isempty(sourceFiles)
        error("SpectraLab:Analysis:SelectionCancelled", ...
            "Spectral-mean file selection was cancelled.");
    end
    archives = loadArchives(sourceFiles);
elseif isstring(firstInput) || ischar(firstInput)
    if ~isempty(secondArchive)
        error("SpectraLab:Analysis:AmbiguousSources", ...
            "Do not supply a second archive with a filename list.");
    end
    sourceFiles = string(firstInput);
    archives = loadArchives(sourceFiles);
elseif iscell(firstInput) && isempty(secondArchive)
    archives = reshape(firstInput, 1, []);
    sourceFiles = requestedFiles;
elseif isstruct(firstInput) && isempty(secondArchive)
    archives = arrayfun(@(item) item, firstInput, UniformOutput=false);
    sourceFiles = requestedFiles;
elseif isstruct(firstInput) && isstruct(secondArchive)
    archives = {firstInput, secondArchive};
    sourceFiles = requestedFiles;
else
    error("SpectraLab:Analysis:InvalidSources", ...
        "Supply archive files, archive structures, or use the selection dialog.");
end

if numel(archives) < 2
    error("SpectraLab:Analysis:TooFewSources", ...
        "Select at least two archives for a spectral mean.");
end
if isempty(sourceFiles)
    sourceFiles = repmat("", 1, numel(archives));
elseif numel(sourceFiles) ~= numel(archives)
    error("SpectraLab:Analysis:InvalidSourceFiles", ...
        "SourceFiles must contain one filename per source archive.");
else
    sourceFiles = reshape(string(sourceFiles), 1, []);
end
end

function archives = loadArchives(sourceFiles)
sourceFiles = reshape(string(sourceFiles), 1, []);
archives = cell(1, numel(sourceFiles));
for index = 1:numel(sourceFiles)
    archives{index} = spectralab.archive.load( ...
        sourceFiles(index), Quiet=true, Validation="error");
end
end

function analysis = makeAnalysis( ...
        definition, parameters, sources, wavelength, value, unit, statistics)
analysis = struct();
analysis.Identity = struct( ...
    "UUID", string(java.util.UUID.randomUUID), ...
    "Created", datetime("now", "TimeZone", "UTC"), ...
    "CreatedBy", "spectralab.analysis.spectralMean");
analysis.Definition = definition;
analysis.Parameters = parameters;
analysis.Result = struct( ...
    "WavelengthNm", wavelength(:), ...
    "Value", value(:), ...
    "Unit", unit, ...
    "StandardDeviation", statistics.StandardDeviation, ...
    "RelativeStandardDeviationPercent", ...
        statistics.RelativeStandardDeviationPercent, ...
    "MeanRelativeStandardDeviationPercent", ...
        statistics.MeanRelativeStandardDeviationPercent);
analysis.Sources = sources;
hashPayload = struct("Definition", definition, "Parameters", parameters, ...
    "Result", analysis.Result, "Sources", sources);
analysis.Identity.ContentHash = spectralab.archive.contentHash(hashPayload);
end

function statistics = stabilityStatistics(valueMatrix, meanValue)
%STABILITYSTATISTICS Quantify pointwise spread relative to the mean spectrum.
%
% Standard deviation uses the sample definition (N-1). Relative standard
% deviation is undefined where the pointwise mean is zero and is recorded
% as NaN so it cannot be mistaken for a stable measurement.

standardDeviation = std(valueMatrix, 0, 2);
relativeStandardDeviationPercent = nan(size(meanValue));
nonzeroMean = meanValue ~= 0;
relativeStandardDeviationPercent(nonzeroMean) = 100 * ...
    standardDeviation(nonzeroMean) ./ abs(meanValue(nonzeroMean));
validRelativeStandardDeviation = ...
    isfinite(relativeStandardDeviationPercent);

statistics = struct( ...
    "StandardDeviation", standardDeviation(:), ...
    "RelativeStandardDeviationPercent", ...
        relativeStandardDeviationPercent(:), ...
    "MeanRelativeStandardDeviationPercent", ...
        mean(relativeStandardDeviationPercent(validRelativeStandardDeviation)));
end

function parameters = parameterSummary(aligned)
parameters = struct( ...
    "Alignment", aligned.Alignment, ...
    "Resampled", aligned.Resampled, ...
    "RefinementFactor", aligned.RefinementFactor, ...
    "InterpolationMethod", aligned.InterpolationMethod, ...
    "SourceCount", aligned.SourceCount, ...
    "EffectiveWavelengthRangeNm", ...
        aligned.WavelengthNm([1 end]).');
end

function source = sourceSummary(archive, role, filename)
source = struct( ...
    "Role", role, ...
    "Filename", string(filename), ...
    "MeasurementName", string(archive.Measurement.Name), ...
    "UUID", string(archive.Identity.UUID), ...
    "ContentHash", string(archive.Identity.ContentHash));
end

function value = displaySource(source)
value = source.Role + "=" + source.Filename + ...
    " [UUID " + source.UUID + "]";
end
