function result = statusMDensity(reference, sample, options)
%STATUSMDENSITY Calculate Status M red, green, and blue densities.
%
%   RESULT = spectralab.analysis.statusMDensity(REFERENCE, SAMPLE)
%
%   calculates Status M RGB densities using the common weighted-density
%   engine. The same calculation logic is used for all three channels;
%   only the spectral weighting function changes.
%
%   Name-value arguments
%   --------------------
%   Resample
%       Enable spectral pre-resampling before weighted integration.
%       Default: false.
%
%   RefinementFactor
%       Number of equal subintervals created within each original
%       wavelength interval. Default: 4.
%
%   InterpolationMethod
%       Interpolation method:
%
%           "pchip"   default
%           "makima"
%           "spline"

    arguments
        reference
        sample

        options.Resample (1,1) logical = false

        options.RefinementFactor (1,1) double ...
            {mustBeInteger, ...
             mustBeGreaterThanOrEqual(options.RefinementFactor, 1)} = 4

        options.InterpolationMethod (1,1) string ...
            {mustBeMember(options.InterpolationMethod, ...
                ["pchip", "makima", "spline"])} = "pchip"
    end

    redWeighting = spectralab.filters.statusM.red();
    greenWeighting = spectralab.filters.statusM.green();
    blueWeighting = spectralab.filters.statusM.blue();

    red = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        redWeighting, ...
        WeightingName="Status M Red", ...
        WarnAboveOne=false, ...
        Resample=options.Resample, ...
        RefinementFactor=options.RefinementFactor, ...
        InterpolationMethod=options.InterpolationMethod);

    green = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        greenWeighting, ...
        WeightingName="Status M Green", ...
        WarnAboveOne=false, ...
        Resample=options.Resample, ...
        RefinementFactor=options.RefinementFactor, ...
        InterpolationMethod=options.InterpolationMethod);

    blue = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        blueWeighting, ...
        WeightingName="Status M Blue", ...
        WarnAboveOne=false, ...
        Resample=options.Resample, ...
        RefinementFactor=options.RefinementFactor, ...
        InterpolationMethod=options.InterpolationMethod);

    densityRGB = [ ...
        red.Density, ...
        green.Density, ...
        blue.Density];

    transmittanceRGB = [ ...
        red.Transmittance, ...
        green.Transmittance, ...
        blue.Transmittance];

    if any(transmittanceRGB > 1)
        warning( ...
            "spectralab:analysis:statusMDensity:TransmittanceAboveOne", ...
            "One or more Status M transmittance values exceed 1. " + ...
            "Check the reference measurement, sample measurement, " + ...
            "instrument stability, and measurement geometry.");
    end

    result = struct( ...
        "Red", red, ...
        "Green", green, ...
        "Blue", blue, ...
        "DensityRGB", densityRGB, ...
        "TransmittanceRGB", transmittanceRGB, ...
        "Standard", "Status M", ...
        "Resampled", options.Resample, ...
        "RefinementFactor", options.RefinementFactor, ...
        "InterpolationMethod", options.InterpolationMethod);

end
