function result = statusADensity(reference, sample)
%STATUSADENSITY Calculate Status A red, green, and blue densities.
%
%   RESULT = spectralab.analysis.statusADensity(REFERENCE, SAMPLE)
%
%   calculates Status A RGB densities using the common weighted-density
%   engine. The same calculation logic is used for all three channels;
%   only the spectral weighting function changes.

    redWeighting = spectralab.filters.statusA.red();
    greenWeighting = spectralab.filters.statusA.green();
    blueWeighting = spectralab.filters.statusA.blue();

    red = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        redWeighting, ...
        WeightingName="Status A Red", ...
        WarnAboveOne=false);

    green = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        greenWeighting, ...
        WeightingName="Status A Green", ...
        WarnAboveOne=false);

    blue = spectralab.core.weightedDensity( ...
        reference, ...
        sample, ...
        blueWeighting, ...
        WeightingName="Status A Blue", ...
        WarnAboveOne=false);

    densityRGB = [ ...
        red.Density, ...
        green.Density, ...
        blue.Density];

    transmittanceRGB = [ ...
        red.Transmittance, ...
        green.Transmittance, ...
        blue.Transmittance];

    if any(transmittanceRGB > 1)
        warning( ...
            "spectralab:analysis:statusADensity:TransmittanceAboveOne", ...
            "One or more Status A transmittance values exceed 1. Check the reference measurement, sample measurement, instrument stability, and measurement geometry.");
    end

    result = struct( ...
        "Red", red, ...
        "Green", green, ...
        "Blue", blue, ...
        "DensityRGB", densityRGB, ...
        "TransmittanceRGB", transmittanceRGB, ...
        "Standard", "Status A");
end