function [session, conversion, outputFile, csvFile] = calculateColorimetry(sessionFile, options)
%CALCULATECOLORIMETRY Calculate ColorChecker XYZ and Lab into a new JSON.
%
% [SESSION, CONVERSION, OUTPUTFILE] = ...
%     spectralab.colorchecker.calculateColorimetry(SESSIONFILE)
% uses the bundled CIE standard illuminant D50 and CIE 1931 2 degree
% observer. Supply Illuminant=SPD to use another illuminant spectrum.
%
% The source session JSON and patch MAT archives remain unchanged. Every
% result is bound to the source archive UUID and content hash and records
% its illuminant and observer.

arguments
    sessionFile (1,1) string
    options.Illuminant (1,1) spectralab.core.Spectrum = ...
        spectralab.filters.cie.d50()
    options.Observer (1,1) string ...
        {mustBeMember(options.Observer, "CIE1931_2")} = "CIE1931_2"
    options.ExportCSV (1,1) logical = false
end

if isfolder(sessionFile)
    sessionFile = fullfile(sessionFile, "colorchecker_session.json");
end
session = spectralab.colorchecker.load(sessionFile);
measured = string({session.Patches.State}) == "measured";
if ~all(measured)
    error("SpectraLab:ColorChecker:SessionIncomplete", ...
        "Colorimetry requires a complete ColorChecker session (%d of %d patches measured).", ...
        nnz(measured), numel(measured));
end
patches = session.Patches(measured);
if isempty(patches)
    error("SpectraLab:ColorChecker:NoMeasuredPatches", ...
        "The ColorChecker session contains no measured patches.");
end

results = repmat(emptyResult(), numel(patches), 1);
sessionFolder = string(session.Context.SessionFolder);
for index = 1:numel(patches)
    patch = patches(index);
    archiveFile = string(patch.ArchiveFile);
    if ~isfile(archiveFile)
        archiveFile = fullfile(sessionFolder, archiveFile);
    end
    archive = spectralab.archive.load( ...
        archiveFile, Quiet=true, Validation="error");
    if string(archive.Identity.UUID) ~= string(patch.ArchiveUUID) || ...
            string(archive.Identity.ContentHash) ~= ...
                string(patch.ArchiveContentHash)
        error("SpectraLab:ColorChecker:PatchArchiveIdentityMismatch", ...
            "Patch %s does not match the archive recorded by the session.", ...
            patch.Coordinate);
    end
    dataset = spectralab.analysis.colorimetry( ...
        archiveFile, Illuminant=options.Illuminant, ...
        Observer=options.Observer);
    color = dataset.Samples(1).Colorimetry;
    results(index) = struct( ...
        "Coordinate", string(patch.Coordinate), ...
        "ArchiveFile", string(patch.ArchiveFile), ...
        "ArchiveUUID", string(patch.ArchiveUUID), ...
        "ArchiveContentHash", string(patch.ArchiveContentHash), ...
        "XYZ", color.XYZ, ...
        "Lab", color.Lab);
end

if isfield(session, "ColorimetryConversions")
    sequence = numel(session.ColorimetryConversions) + 1;
else
    sequence = 1;
end
conversion = struct( ...
    "Sequence", sequence, ...
    "Created", char(datetime("now", "TimeZone", "local"), ...
        "yyyy-MM-dd'T'HH:mm:ssXXX"), ...
    "CalculationVersion", "COL-001", ...
    "Method", "R(lambda) * illuminant SPD -> CIE 1931 XYZ -> CIELAB", ...
    "SourceSessionFile", string(sessionFile), ...
    "SourceSessionUUID", string(session.Identity.UUID), ...
    "Illuminant", struct( ...
        "Label", options.Illuminant.Label, ...
        "Unit", options.Illuminant.PowerUnit, ...
        "WavelengthMinimumNm", min(options.Illuminant.WavelengthNm), ...
        "WavelengthMaximumNm", max(options.Illuminant.WavelengthNm)), ...
    "Observer", options.Observer, ...
    "PatchCount", numel(results), ...
    "Results", results);
if isfield(session, "ColorimetryConversions")
    session.ColorimetryConversions(end+1,1) = conversion;
else
    session.ColorimetryConversions = conversion;
end
session.History(end+1,1) = string(datetime("now", ...
    "TimeZone", "local", "Format", "yyyy-MM-dd HH:mm:ss")) + ...
    "  Colorimetry conversion " + string(conversion.Sequence) + ...
    " added (" + options.Illuminant.Label + ", " + ...
    options.Observer + ").";

[outputFile, ~, expectedCsvFile] = ...
    spectralab.colorchecker.colorimetryOutputFiles( ...
    sessionFile, options.Illuminant, options.Observer);
writeDerivedJson(outputFile, session);
csvFile = "";
if options.ExportCSV
    csvFile = spectralab.colorchecker.exportColorimetryCsv( ...
        conversion, expectedCsvFile);
end
end

function result = emptyResult()
result = struct( ...
    "Coordinate", "", ...
    "ArchiveFile", "", ...
    "ArchiveUUID", "", ...
    "ArchiveContentHash", "", ...
    "XYZ", struct(), ...
    "Lab", struct());
end

function writeDerivedJson(outputFile, session)
if isfile(outputFile)
    error("SpectraLab:ColorChecker:ConvertedJsonAlreadyExists", ...
        "SpectraLab refuses to overwrite the converted JSON file:\n%s", ...
        outputFile);
end
temporary = outputFile + ".tmp-" + string(java.util.UUID.randomUUID);
fid = fopen(temporary, "w");
if fid < 0
    error("SpectraLab:ColorChecker:ConvertedJsonWriteFailed", ...
        "Could not create converted JSON file: %s", temporary);
end
try
    fprintf(fid, "%s\n", jsonencode(session, PrettyPrint=true));
    fclose(fid);
catch ME
    fclose(fid);
    if isfile(temporary), delete(temporary); end
    rethrow(ME)
end
[ok, message] = movefile(temporary, outputFile);
if ~ok
    error("SpectraLab:ColorChecker:ConvertedJsonWriteFailed", ...
        "Could not create converted JSON file:\n%s\n\n%s", ...
        outputFile, message);
end
end
