function artifact = createSpectralArtifact(sessionFile)
%CREATESPECTRALARTIFACT Bundle a complete ColorChecker session in one file.
arguments
    sessionFile (1,1) string
end
session = spectralab.colorchecker.load(sessionFile);
if any(string({session.Patches.State}) ~= "measured")
    error("SpectraLab:ColorChecker:SessionIncomplete", ...
        "A ColorChecker spectral artifact requires all patches to be measured.");
end
count = numel(session.Patches);
patchIDs = strings(count,1); sources = repmat(struct( ...
    "UUID","","ContentHash","","ArchiveFile",""),count,1);
wavelength = []; values = [];
for index = 1:count
    patch = session.Patches(index);
    archiveFile = string(patch.ArchiveFile);
    if ~isfile(archiveFile)
        archiveFile = fullfile(string(session.Context.SessionFolder),archiveFile);
    end
    archive = spectralab.archive.load(archiveFile,Quiet=true,Validation="error");
    if string(archive.Identity.UUID) ~= string(patch.ArchiveUUID) || ...
            string(archive.Identity.ContentHash) ~= string(patch.ArchiveContentHash)
        error("SpectraLab:ColorChecker:PatchArchiveIdentityMismatch", ...
            "Patch %s does not match its recorded source archive.",patch.Coordinate);
    end
    if index == 1
        wavelength = double(archive.Measurement.Wavelength(:));
        values = zeros(numel(wavelength),count);
    elseif ~isequal(wavelength,double(archive.Measurement.Wavelength(:)))
        error("SpectraLab:ColorChecker:WavelengthMismatch", ...
            "ColorChecker patch spectra must use one common wavelength grid.");
    end
    patchIDs(index) = string(patch.Coordinate);
    values(:,index) = double(archive.Measurement.Value(:));
    sources(index) = struct("UUID",string(archive.Identity.UUID), ...
        "ContentHash",string(archive.Identity.ContentHash), ...
        "ArchiveFile",string(patch.ArchiveFile));
end
[wavelength,values,contract] = ...
    spectralab.io.applyCamera41ExportContract(wavelength,values);
range=contract.WavelengthRangeNm;
effectiveRange=[wavelength(1) wavelength(end)];
payload = struct("Target",session.Definition, ...
    "PatchIDs",patchIDs,"WavelengthNm",wavelength, ...
    "Values",values,"Unit","1", ...
    "RequestedWavelengthRangeNm",range, ...
    "EffectiveWavelengthRangeNm",effectiveRange);
if isfield(session,"ColorimetryConversions") && ...
        ~isempty(session.ColorimetryConversions)
    payload.Colorimetry = session.ColorimetryConversions(end);
end
artifact = struct("Schema","spectralab.spectral-artifact", ...
    "SchemaVersion","1.0","Identity",struct(),"Origin","derived", ...
    "Kind","spectrum_set","Quantity","spectral_reflectance", ...
    "Payload",payload,"Provenance",struct( ...
        "SourceSessionFile",sessionFile, ...
        "SourceSessionUUID",string(session.Identity.UUID), ...
        "Sources",sources, ...
        "Camera41ExportContract",contract, ...
        "RequestedOutputWavelengthRangeNm",range, ...
        "EffectiveOutputWavelengthRangeNm",effectiveRange, ...
        "Output",struct("Type","SpectrumSet", ...
            "Cardinality",count,"Role","ReusableAnalysisInput")));
artifact.Identity = struct("UUID",string(java.util.UUID.randomUUID), ...
    "Created",datetime("now","TimeZone","UTC"), ...
    "ContentHash",spectralab.archive.contentHash(rmfield(artifact,"Identity")));
end
