function info=generateColorimetryReport(convertedJsonFile,options)
%GENERATECOLORIMETRYREPORT Create a base-MATLAB ColorChecker PDF report.
arguments
    convertedJsonFile (1,1) string
    options.OpenPDF (1,1) logical=false
    options.VerificationIlluminant=[]
end
if ~isfile(convertedJsonFile)
    error("SpectraLab:ColorChecker:ConvertedJsonNotFound", ...
        "Converted ColorChecker JSON not found: %s",convertedJsonFile);
end
session=spectralab.colorchecker.load(convertedJsonFile);
if ~isfield(session,"ColorimetryConversions") || isempty(session.ColorimetryConversions)
    error("SpectraLab:ColorChecker:ColorimetryConversionMissing", ...
        "The selected JSON contains no ColorChecker colorimetry conversion.");
end
conversion=session.ColorimetryConversions(end); results=conversion.Results;
verification=spectralab.colorchecker.verifyColorimetry(convertedJsonFile, ...
    Illuminant=options.VerificationIlluminant);
sessionFolder=string(fileparts(convertedJsonFile));
[qualitySummary,patchRows,integrityRows]=collectPatchProvenance(session,sessionFolder);
reportFolder=fullfile(sessionFolder,"report");
if ~isfolder(reportFolder), mkdir(reportFolder); end
[~,baseName]=fileparts(convertedJsonFile);
pdfFile=fullfile(reportFolder,string(baseName)+"_report.pdf");
if isfile(pdfFile)
    error("SpectraLab:ColorChecker:ColorimetryReportExists", ...
        "SpectraLab refuses to overwrite the ColorChecker report:\n%s",pdfFile);
end
targetName=targetValue(session,"Name");
if targetName=="-", targetName=string(session.Definition.Name); end
details=["Session UUID",string(session.Identity.UUID); ...
    "Session created",string(session.Identity.Created); ...
    "SpectraLab measurement version",string(session.Identity.Software); ...
    "Operator",valueOrDash(session.Context,"Operator"); ...
    "Project",valueOrDash(session.Context,"Project"); ...
    "Comment",valueOrDash(session.Context,"Comment"); ...
    "Official target model",targetValue(session,"Name"); ...
    "Target canonical ID",targetValue(session,"CanonicalID"); ...
    "Target definition SHA-256",valueOrDash(session.Definition,"TargetDefinitionHash"); ...
    "Measurement session name",valueOrDash(session.Definition,"Name"); ...
    "Physical chart ID",valueOrDash(session.Definition,"ChartID"); ...
    "Chart serial number",valueOrDash(session.Definition,"ChartSerialNumber"); ...
    "Chart manufactured",valueOrDash(session.Definition,"ChartManufacturedDate"); ...
    "Chart geometry",sprintf("%d rows x %d columns",session.Definition.Rows,session.Definition.Columns); ...
    "Source session",string(conversion.SourceSessionFile); ...
    "Calculation version",string(conversion.CalculationVersion); ...
    "Method",string(conversion.Method); ...
    "Illuminant",string(conversion.Illuminant.Label); ...
    "Observer",string(conversion.Observer); ...
    "Converted",string(conversion.Created); ...
    "Patch count",string(conversion.PatchCount)];
provenance=["Primary measurement",string(session.MeasurementDefinition.Quantity)+ ...
    " R(lambda), "+string(session.MeasurementDefinition.Unit); ...
    "Archive model",string(session.MeasurementDefinition.PrimaryData); ...
    "Instrument",qualitySummary.InstrumentName; ...
    "Instrument serial number",qualitySummary.InstrumentSerialNumber; ...
    "Driver",qualitySummary.InstrumentDriver; ...
    "Spectral resolution",qualitySummary.Resolution; ...
    "Calibration events",string(numel(session.Calibrations)); ...
    "Calibration method",qualitySummary.CalibrationMethod; ...
    "Calibration interval",string(session.CalibrationPolicy.IntervalMinutes)+" minutes"; ...
    "Session revisions",string(session.Identity.Revision)];
quality=["Patch archives expected",string(numel(session.Patches)); ...
    "Patch archives loaded",string(qualitySummary.LoadedCount); ...
    "Identity and hash references verified",yesNo(qualitySummary.TraceabilityVerified); ...
    "Archives marked valid",string(qualitySummary.ValidCount)+" of "+string(qualitySummary.LoadedCount); ...
    "Archives marked saturated",string(qualitySummary.SaturatedCount); ...
    "Archives with warnings",string(qualitySummary.WarningCount); ...
    "Archives with quality comments",string(qualitySummary.CommentCount); ...
    "Overall quality",qualitySummary.OverallStatus; ...
    "Colorimetry recalculation",sprintf("verified: %s; maximum difference XYZ %.3g, Lab %.3g", ...
    yesNo(verification.Verified),verification.MaximumXYZDifference,verification.MaximumLabDifference)];
resultRows=strings(numel(results),2);
for index=1:numel(results)
    r=results(index); resultRows(index,:)=[string(r.Coordinate), ...
        sprintf("XYZ %.2f %.2f %.2f; Lab %.2f %.2f %.2f", ...
        r.XYZ.X,r.XYZ.Y,r.XYZ.Z,r.Lab.L,r.Lab.a,r.Lab.b)];
end
sections=[section("Measurement and calculation",details,targetName); ...
    section("Measurement provenance",provenance,""); ...
    section("Quality summary",quality,""); ...
    section("Results",resultRows, ...
    "XYZ and CIELAB are derived from archived spectral reflectance factors R(lambda). Source archives remain unchanged."); ...
    section("Patch provenance and quality",patchRows,""); ...
    section("Archive integrity references",integrityRows,"")];
pdf=spectralab.report.internal.exportTabularPDF(pdfFile, ...
    "ColorChecker colorimetry",string(session.Identity.UUID),sections);
info=struct("PDFFile",pdfFile,"ConvertedJsonFile",convertedJsonFile, ...
    "PatchCount",numel(results),"ContainsPlot",false,"ContainsXYZ",true, ...
    "ContainsLab",true,"ContainsProvenance",true,"ContainsQuality",true, ...
    "MeasurementComment",valueOrDash(session.Context,"Comment"), ...
    "PDF",pdf);
if options.OpenPDF, open(char(pdfFile)); end
end

function s=section(title,rows,text), s=struct("Title",title,"Rows",rows,"Text",text); end

function [summary,patchRows,integrityRows]=collectPatchProvenance(session,sessionFolder)
patches=session.Patches; patchRows=strings(numel(patches),2); integrityRows=patchRows;
loaded=0; valid=0; saturated=0; warnings=0; comments=0; traceable=true;
instrumentName="-"; serial="-"; driver="-"; resolution="-";
for index=1:numel(patches)
    patch=patches(index); archiveFile=string(patch.ArchiveFile);
    if ~isfile(archiveFile), archiveFile=fullfile(sessionFolder,archiveFile); end
    archive=spectralab.archive.load(archiveFile,Quiet=true,Validation="error");
    loaded=loaded+1;
    identityOkay=string(archive.Identity.UUID)==string(patch.ArchiveUUID) && ...
        string(archive.Identity.ContentHash)==string(patch.ArchiveContentHash);
    traceable=traceable && identityOkay;
    isValid=logical(archive.Quality.Valid); isSaturated=logical(archive.Quality.Saturated);
    warning=string(archive.Quality.Warning); comment=string(archive.Quality.Comment);
    valid=valid+double(isValid); saturated=saturated+double(isSaturated);
    warnings=warnings+double(strlength(strtrim(warning))>0);
    comments=comments+double(strlength(strtrim(comment))>0);
    status=qualityStatus(isValid,isSaturated,warning,comment,identityOkay);
    patchRows(index,:)=[string(patch.Coordinate),string(patch.ArchiveFile)+ ...
        "; calibration "+string(patch.CalibrationSequence)+"; "+status];
    integrityRows(index,:)=[string(patch.Coordinate),"UUID "+ ...
        string(patch.ArchiveUUID)+"; SHA-256 "+string(patch.ArchiveContentHash)];
    if index==1
        instrumentName=valueOrDash(archive.Instrument,"Name");
        serial=valueOrDash(archive.Instrument,"SerialNumber");
        driver=valueOrDash(archive.Instrument,"Driver");
        if isfield(archive.Instrument,"HighResolution") && archive.Instrument.HighResolution
            resolution="high resolution";
        else, resolution="standard resolution"; end
    end
end
calibrationMethod="-";
if ~isempty(session.Calibrations)
    calibrationMethod=join(unique(string({session.Calibrations.Method}),"stable"),"; ");
end
overall=loaded==numel(patches) && traceable && valid==loaded && saturated==0 && warnings==0;
if overall, overallStatus="PASS - all patch archives valid and traceable";
else, overallStatus="REVIEW REQUIRED - see patch provenance table"; end
summary=struct("LoadedCount",loaded,"ValidCount",valid, ...
    "SaturatedCount",saturated,"WarningCount",warnings,"CommentCount",comments, ...
    "TraceabilityVerified",traceable,"OverallStatus",overallStatus, ...
    "InstrumentName",instrumentName,"InstrumentSerialNumber",serial, ...
    "InstrumentDriver",driver,"Resolution",resolution, ...
    "CalibrationMethod",calibrationMethod);
end

function value=qualityStatus(valid,saturated,warning,comment,traceable)
parts=strings(0,1); if valid,parts(end+1)="valid";else,parts(end+1)="invalid";end
if saturated,parts(end+1)="saturated";end
if ~traceable,parts(end+1)="identity/hash mismatch";end
if strlength(strtrim(warning))>0,parts(end+1)="warning: "+warning;end
if strlength(strtrim(comment))>0,parts(end+1)="comment: "+comment;end
value=join(parts,"; ");
end

function value=valueOrDash(container,field)
value="-"; if isstruct(container) && isfield(container,field)
    candidate=strtrim(string(container.(field)));
    if isscalar(candidate) && strlength(candidate)>0,value=candidate;end
end
end
function value=targetValue(session,field), value="-"; if isfield(session,"Definition") && isfield(session.Definition,"TargetDefinition"),value=valueOrDash(session.Definition.TargetDefinition,field);end, end
function value=yesNo(condition), if condition,value="yes";else,value="no";end, end
