function info=generateSessionReport(sessionFolder,options)
%GENERATESESSIONREPORT Document one ColorChecker acquisition using base MATLAB.
arguments
    sessionFolder (1,1) string
    options.OpenPDF (1,1) logical=false
end
manifestFile=fullfile(sessionFolder,"data","series_manifest.json");
if ~isfile(manifestFile)
    error("SpectraLab:ColorChecker:SessionManifestMissing", ...
        "ColorChecker session manifest not found:\n%s",manifestFile);
end
manifest=jsondecode(fileread(manifestFile));
reportFolder=fullfile(sessionFolder,"report");
if ~isfolder(reportFolder), mkdir(reportFolder); end
[~,sessionName]=fileparts(sessionFolder);
pdfFile=fullfile(reportFolder,string(sessionName)+"_session_report.pdf");
if isfile(pdfFile)
    error("SpectraLab:ColorChecker:SessionReportExists", ...
        "Session report already exists and will not be overwritten:\n%s",pdfFile);
end
measurement=["ColorChecker name",textValue(manifest,"chart_name",sessionName); ...
    "Manufactured/created",textValue(manifest,"chart_manufactured_date","-"); ...
    "Session folder",string(sessionName); ...
    "Operator",textValue(manifest,"operator","-"); ...
    "Project",textValue(manifest,"project","-"); ...
    "Comment",textValue(manifest,"comment","-"); ...
    "Manifest schema",textValue(manifest,"schema","-"); ...
    "Session state",upper(textValue(manifest,"state","unknown")); ...
    "Started",unixTime(manifest,"started_unix"); ...
    "Last update",unixTime(manifest,"updated_unix")];
resolution="Standard";
if logicalValue(manifest,"high_resolution",false), resolution="High resolution"; end
acquisition=["Instrument",textValue(manifest,"instrument_id","-"); ...
    "Spectral resolution",resolution; ...
    "Requested patches",string(numericValue(manifest,"requested_patch_count",0)); ...
    "Completed patches",string(numericValue(manifest,"completed_patch_count",0)); ...
    "Session message",textValue(manifest,"message","-")];
records=manifest.records; patchRows=strings(max(1,numel(records)),2);
archiveFolder=fullfile(sessionFolder,"archive");
for index=1:numel(records)
    coordinate=string(records(index).coordinate);
    archives=dir(fullfile(archiveFolder,coordinate+"_*.mat"));
    if isempty(archives), patchRows(index,:)=[coordinate,"MISSING"]; continue, end
    archive=spectralab.archive.load(fullfile(archives(1).folder,archives(1).name), ...
        Quiet=true,Validation="error");
    patchRows(index,:)=[coordinate,string(archives(1).name)+"; "+ ...
        displayDate(archive.Identity.Created)];
end
if isempty(records), patchRows(1,:)=["-","No patches"]; end
locations=["Session manifest",relativePath(manifestFile,sessionFolder); ...
    "Raw acquisition data","data/";"Patch archives","archive/"; ...
    "This report","report/"+string(sessionName)+"_session_report.pdf"];
sections=[section("Measurement",measurement,""); ...
    section("Acquisition",acquisition,""); ...
    section("Patch archive documentation",patchRows, ...
    "Acquisition and archive identity only. Complete UUID and SHA-256 identity remain in each archive."); ...
    section("File locations",locations,"")];
pdf=spectralab.report.internal.exportTabularPDF(pdfFile, ...
    "ColorChecker measurement session",string(sessionName),sections);
info=struct("PDFFile",pdfFile,"SessionFolder",sessionFolder, ...
    "PatchCount",numel(records),"ContainsPlot",false, ...
    "ContainsXYZ",false,"ContainsLab",false, ...
    "MeasurementComment",textValue(manifest,"comment","-"),"PDF",pdf);
if options.OpenPDF, open(char(pdfFile)); end
end

function s=section(title,rows,text), s=struct("Title",title,"Rows",rows,"Text",text); end
function v=textValue(s,f,d), if isfield(s,f),v=string(s.(f));else,v=string(d);end, if strlength(strtrim(v))==0,v=string(d);end, end
function v=numericValue(s,f,d), if isfield(s,f),v=double(s.(f));else,v=d;end, end
function v=logicalValue(s,f,d), if isfield(s,f),v=logical(s.(f));else,v=d;end, end
function v=unixTime(s,f), if ~isfield(s,f),v="-";return,end, v=string(datetime(double(s.(f)),"ConvertFrom","posixtime","TimeZone","local","Format","yyyy-MM-dd HH:mm:ss Z")); end
function v=displayDate(x), if isdatetime(x),v=string(x,"yyyy-MM-dd HH:mm:ss");else,v=string(x);end, end
function v=relativePath(path,root), v=erase(string(path),string(root)+filesep); end
