function series = readSpotreadSeries(folder)
%READSPOTREADSERIES Read a Python Spotread ColorChecker acquisition.
%
% SERIES = spectralab.colorchecker.readSpotreadSeries(FOLDER) reads
% series_manifest.json and converts every completed patch transcript into
% a standard SpectraLab Spectrum. Partial/cancelled sessions remain
% readable; only records already present in the manifest are returned.

arguments
    folder (1,1) string
end

manifestFile = fullfile(folder, "series_manifest.json");
if ~isfile(manifestFile)
    error("SpectraLab:ColorChecker:SeriesManifestMissing", ...
        "Spotread series manifest not found: %s", manifestFile);
end
manifest = jsondecode(fileread(manifestFile));
if ~isfield(manifest, "schema") || ...
        string(manifest.schema) ~= "spectralab.spotread-colorchecker-series.v1"
    error("SpectraLab:ColorChecker:UnsupportedSeriesManifest", ...
        "Unsupported Spotread ColorChecker series manifest.");
end
instrumentId = "";
if isfield(manifest, "instrument_id")
    instrumentId = string(manifest.instrument_id);
end
highResolution = false;
if isfield(manifest, "high_resolution")
    highResolution = logical(manifest.high_resolution);
end
chartName = "";
if isfield(manifest, "chart_name")
    chartName = string(manifest.chart_name);
end
chartManufacturedDate = "";
if isfield(manifest, "chart_manufactured_date")
    chartManufacturedDate = string(manifest.chart_manufactured_date);
end

records = manifest.records;
if isempty(records)
    patches = repmat(emptyPatch(), 0, 1);
else
    patches = repmat(emptyPatch(), numel(records), 1);
    for index = 1:numel(records)
        coordinate = upper(strtrim(string(records(index).coordinate)));
        rawFile = string(records(index).raw_file);
        if ~isfile(rawFile)
            rawFile = fullfile(folder, rawFile);
        end
        if ~isfile(rawFile)
            error("SpectraLab:ColorChecker:SeriesTranscriptMissing", ...
                "Transcript for patch %s was not found: %s", coordinate, rawFile);
        end
        raw = string(fileread(rawFile));
        [wavelength, value, parseInfo] = ...
            spectralab.drivers.spotread.Parser.parseSpectrum(raw);
        colorimetry = ...
            spectralab.drivers.spotread.Parser.parseColorimetry(raw);
        metadata = struct( ...
            "measurement_kind", "reflectance", ...
            "signal_quantity", "spectral reflectance factor", ...
            "backend", "ArgyllCMS spotread persistent ColorChecker series", ...
            "ColorCheckerCoordinate", coordinate, ...
            "ColorCheckerName", chartName, ...
            "ColorCheckerManufacturedDate", chartManufacturedDate, ...
            "raw_output", raw, ...
            "parse_info", parseInfo, ...
            "spotread_colorimetry", colorimetry, ...
            "colorimetry", colorimetry);
        spectrum = spectralab.core.Spectrum( ...
            wavelength, value, "ColorChecker_" + coordinate, ...
            struct("name", instrumentId, ...
                   "instrument_id", instrumentId, ...
                   "driver", "spectralab.drivers.SpotreadInstrument", ...
                   "backend", "ArgyllCMS spotread", ...
                   "high_resolution", highResolution), ...
            struct(), metadata, "percent");
        patches(index) = struct( ...
            "Index", double(records(index).index), ...
            "Coordinate", coordinate, ...
            "RawFile", rawFile, ...
            "RawOutput", raw, ...
            "Colorimetry", colorimetry, ...
            "Spectrum", spectrum);
    end
end

series = struct( ...
    "Folder", string(folder), ...
    "ManifestFile", string(manifestFile), ...
    "State", string(manifest.state), ...
    "RequestedPatchCount", double(manifest.requested_patch_count), ...
    "CompletedPatchCount", numel(patches), ...
    "Definition", struct( ...
        "Name", chartName, ...
        "ManufacturedDate", chartManufacturedDate), ...
    "Patches", patches, ...
    "Manifest", manifest);
end

function patch = emptyPatch()
patch = struct("Index", 0, "Coordinate", "", "RawFile", "", ...
    "RawOutput", "", "Colorimetry", struct(), "Spectrum", []);
end
