function definition = targetDefinition(identifier)
%TARGETDEFINITION Return one architecture-controlled chart definition.
%
%   DEFINITION = spectralab.colorchecker.targetDefinition( ...
%       "xrite-colorchecker-digital-sg-140")
%
% A target definition identifies the manufacturer's chart contract. It is
% deliberately separate from the identity, date or lot marking of one
% physical chart instance and from the user-selected measurement-session
% name.

arguments
    identifier (1,1) string
end

identifier = lower(strtrim(identifier));
switch identifier
    case {"xrite-colorchecker-digital-sg-140", ...
            "x-rite colorchecker digital sg"}
        definition = struct( ...
            "Schema", "spectralab.colorchecker-target.v1", ...
            "CanonicalID", "xrite-colorchecker-digital-sg-140", ...
            "Name", "X-Rite ColorChecker Digital SG", ...
            "Manufacturer", "X-Rite", ...
            "Model", "Digital ColorChecker SG", ...
            "Rows", 10, ...
            "Columns", 14, ...
            "PatchCount", 140, ...
            "CoordinateConvention", ...
                "Column letters increase left-to-right; row numbers increase top-to-bottom; A1 is upper left.", ...
            "MeasurementOrder", ...
                "row-major: A1, B1, ... then A2, B2, ...", ...
            "NominalSpecification", struct( ...
                "Authority", "X-Rite", ...
                "Dataset", "Digital ColorChecker SG nominal reference data", ...
                "Role", ...
                    "Defines the nominal manufacturing target; measured SpectraLab R(lambda) characterises the physical chart instance.", ...
                "ValuesEmbedded", false));
    otherwise
        error("SpectraLab:ColorChecker:UnknownTargetDefinition", ...
            "Unknown ColorChecker target definition: %s", identifier);
end
end
