%% Compare two spectra in one figure

fig = figure;
ax = axes(fig);

hold(ax, "on");

spectralab.plot.spectrum( ...
    a, ...
    Parent=ax, ...
    DisplayName="Spectrum A", ...
    ShowSummary=false);

spectralab.plot.spectrum( ...
    b, ...
    Parent=ax, ...
    LineStyle="--", ...
    DisplayName="Spectrum B", ...
    ShowSummary=false);

hold(ax, "off");

title(ax, "Comparison of two spectra");
legend(ax, "Location", "eastoutside", "Interpreter", "none");
