function info = generate_reference_cri_report(outputFolder)
%GENERATE_REFERENCE_CRI_REPORT Create the RP-017 visual reference PDF/PNG.
%
%   info = generate_reference_cri_report()
%   info = generate_reference_cri_report(outputFolder)
%
% The example uses deterministic synthetic spectrum data and realistic CRI
% result values. It exercises the complete report pipeline and is intended
% for visual design review, not scientific validation of the synthetic data.

arguments
    outputFolder (1,1) string = fullfile(pwd,"reference_report_output")
end

if ~isfolder(outputFolder), mkdir(outputFolder); end
pdfFile = fullfile(outputFolder,"SpectraLab_CRI_reference_report.pdf");
pngFile = fullfile(outputFolder,"SpectraLab_CRI_reference_figure.png");
existingFiles = strings(0,1);

if isfile(pdfFile)
    existingFiles(end+1,1) = pdfFile; %#ok<AGROW>
end

if isfile(pngFile)
    existingFiles(end+1,1) = pngFile; %#ok<AGROW>
end

if ~isempty(existingFiles)
    fileList = "  " + strjoin(existingFiles, newline + "  ");

    error("SpectraLab:Report:ReportFileAlreadyExists", ...
        "SpectraLab refused to overwrite existing report output file(s):" + ...
        newline + "%s" + newline + newline + ...
        "Delete the existing file(s) or choose another output folder.", ...
        fileList);
end

wavelengthNm = (380:10:730).';
power = 0.12 + ...
    0.55*exp(-0.5*((wavelengthNm-455)/24).^2) + ...
    0.92*exp(-0.5*((wavelengthNm-545)/46).^2) + ...
    0.48*exp(-0.5*((wavelengthNm-615)/34).^2);
spec = spectralab.core.Spectrum(wavelengthNm,power, ...
    "CRI reference spectrum",struct("Name","X-Rite i1Pro 2"), ...
    struct(),struct(),"relative");

archive = makeArchive();
definition = makeDefinition();
result = struct("CCT",5045.123,"Duv",0.004821987,"Ra",95.4321);
context = spectralab.report.internal.buildContext( ...
    "CRI_reference.mat",archive,definition,result,outputFolder, ...
    GenerationTime=datetime(2026,7,28,12,0,0));
context.Report.ReportId = "RPT-CRI-REFERENCE-001";

manifest = spectralab.report.internal.buildManifest(context);
document = spectralab.report.internal.buildDocumentModel(manifest);
renderContext = spectralab.report.internal.createRenderContext(context,manifest);
cleanup = onCleanup(@() spectralab.report.internal.releaseRenderContext(renderContext)); %#ok<NASGU>

spectralab.plot.spectrum(spec,Parent=renderContext.Graphics.Axes, ...
    Title="Measured spectral power distribution", ...
    Normalize=true,ShowSummary=false,ShowSpectralColorBar=true);

[renderContext,renderResults] = ...
    spectralab.report.internal.renderDocumentModel(document,context,renderContext);
[renderContext,layoutPlan] = ...
    spectralab.report.internal.layoutRenderResults(renderContext,renderResults);

pdfInfo = spectralab.report.internal.exportPDF(pdfFile,layoutPlan,renderContext);
pngInfo = spectralab.report.internal.exportPNG(pngFile,renderContext);

info = struct("PDFFile",pdfFile,"PNGFile",pngFile, ...
    "PDF",pdfInfo,"PNG",pngInfo,"Context",context, ...
    "Manifest",manifest,"LayoutPlan",layoutPlan);

fprintf("Reference report created:\n  %s\n  %s\n",pdfFile,pngFile);
fprintf("Review whether the PDF figure is the real spectrum or a placeholder.\n");
end

function archive = makeArchive()
archive = struct();
archive.Identity = struct("UUID","reference-cri-0001", ...
    "ContentHash","reference-content-hash-0001");
archive.Version = struct("Format","SLAB-MAT","Version","0.6");
archive.Measurement = struct("Name","CRI Reference Report", ...
    "Project","SpectraLab v0.8.0 visual review", ...
    "Sample","Synthetic LED spectrum", ...
    "Operator","Christer Törnkvist", ...
    "Date",datetime(2026,7,28,11,30,0));
archive.Metadata = struct();
archive.Instrument = struct("Name","X-Rite i1Pro 2");
archive.Quality = struct("Status","Reference demonstration");
end

function definition = makeDefinition()
definition = struct("AnalysisId","ANL-CRI", ...
    "Name","Color Rendering Index", ...
    "Method","CIE 13.3", ...
    "Standard","CIE 13.3", ...
    "DefinitionVersion","1", ...
    "HasFigure",true, ...
    "ResultFields",[field("CCT","CCT","K","%.0f"); ...
                    field("Duv","Duv","","%+.5f"); ...
                    field("Ra","Ra","","%.1f")], ...
    "FigureDefinition",struct("AspectRatio",3/2, ...
        "WidthFraction",0.82,"MaxHeight",260, ...
        "Caption","Measured spectral power distribution with qualitative visible-wavelength guide."));
end

function value = field(name,label,unit,format)
value = struct("Field",string(name),"Label",string(label), ...
    "Unit",string(unit),"Format",string(format));
end
