%% Validate CIE 1931 XYZ using an archived Spectrum

startup

[fileName, folderName] = uigetfile( ...
    "*.mat", ...
    "SpectraLab - Validate XYZ: select spectrum archive");

if isequal(fileName, 0)
    error("No archive file was selected.");
end

archivePath = fullfile(folderName, fileName);

archive = spectralab.archive.load(archivePath);
spec = spectralab.archive.restore(archive);

assert( ...
    isa(spec, "spectralab.core.Spectrum"), ...
    "The archive did not restore to a Spectrum.");

xyzResult = spectralab.analysis.xyz( ...
    spec, ...
    Normalization="Y100");

fprintf("CIE 1931 XYZ, Y100 normalization\n");
fprintf("X = %.6f\n", xyzResult.Result.X);
fprintf("Y = %.6f\n", xyzResult.Result.Y);
fprintf("Z = %.6f\n", xyzResult.Result.Z);

%% Figure 1 — Original spectrum

spectralab.plot.spectrum( ...
    spec, ...
    Title="Original spectrum", ...
    Color="k", ...
    LineWidth=1.5, ...
    ShowSummary=false);

%% Figure 2 — xBar response

spectralab.plot.filterResponse( ...
    xyzResult.XResponse, ...
    Title="CIE 1931 xBar weighted response", ...
    Color="r", ...
    LineWidth=1.5, ...
    DisplayName="xBar response");

%% Figure 3 — yBar response

spectralab.plot.filterResponse( ...
    xyzResult.YResponse, ...
    Title="CIE 1931 yBar weighted response", ...
    Color="g", ...
    LineWidth=1.5, ...
    DisplayName="yBar response");

%% Figure 4 — zBar response

spectralab.plot.filterResponse( ...
    xyzResult.ZResponse, ...
    Title="CIE 1931 zBar weighted response", ...
    Color="b", ...
    LineWidth=1.5, ...
    DisplayName="zBar response");

%% Figure 5 — Combined responses

fig = figure;
ax = axes(fig);

hold(ax, "on");

spectralab.plot.filterResponse( ...
    xyzResult.XResponse, ...
    Parent=ax, ...
    Title="", ...
    Color="r", ...
    LineWidth=1.5, ...
    DisplayName="xBar");

spectralab.plot.filterResponse( ...
    xyzResult.YResponse, ...
    Parent=ax, ...
    Title="", ...
    Color="g", ...
    LineWidth=1.5, ...
    DisplayName="yBar");

spectralab.plot.filterResponse( ...
    xyzResult.ZResponse, ...
    Parent=ax, ...
    Title="", ...
    Color="b", ...
    LineWidth=1.5, ...
    DisplayName="zBar");

hold(ax, "off");

title(ax, "CIE 1931 weighted spectral responses");
xlabel(ax, "Wavelength (nm)");
ylabel(ax, "Weighted spectral response");
legend(ax, "Location", "eastoutside", "Interpreter", "none");
grid(ax, "on");
box(ax, "on");
