function [referenceFile, sampleFile] = select_transmission_archives( ...
        initialArchiveFolder, operationLabel)
%SELECT_TRANSMISSION_ARCHIVES Select and confirm reference and sample files.

arguments
    initialArchiveFolder (1,1) string
    operationLabel (1,1) string = "transmission analysis"
end

referenceFile = "";
sampleFile = "";
initialArchiveFolder = analysis_archive_folder(initialArchiveFolder);

[referenceFileName, referencePath] = uigetfile( ...
    {"*.mat", "SpectraLab archives (*.mat)"}, ...
    "SpectraLab - " + operationLabel + ...
        ": select REFERENCE archive", ...
    initialArchiveFolder, ...
    "MultiSelect", "off");
if isequal(referenceFileName, 0)
    return
end

referencePath = analysis_archive_folder( ...
    initialArchiveFolder, string(referencePath));
referenceFile = string(fullfile(referencePath, referenceFileName));

referenceChoice = questdlg( ...
    sprintf([ ...
        'REFERENCE FILE\n\nFilename: %s\nFolder: %s\n\n' ...
        'This archive will be used as the reference spectrum.'], ...
        string(referenceFileName), referencePath), ...
    "SpectraLab - Confirm reference file", ...
    "Use as reference", ...
    "Cancel", ...
    "Use as reference");
if isempty(referenceChoice) || strcmp(referenceChoice, "Cancel")
    referenceFile = "";
    return
end

[sampleFileName, samplePath] = uigetfile( ...
    {"*.mat", "SpectraLab archives (*.mat)"}, ...
    "SpectraLab - " + operationLabel + ...
        ": select SAMPLE archive (reference: " + ...
        string(referenceFileName) + ")", ...
    referencePath, ...
    "MultiSelect", "off");
if isequal(sampleFileName, 0)
    referenceFile = "";
    return
end

samplePath = analysis_archive_folder(referencePath, string(samplePath));
sampleFile = string(fullfile(samplePath, sampleFileName));
if referenceFile == sampleFile
    error( ...
        "SpectraLab:Work:IdenticalArchives", ...
        "Reference and sample must be different archive files.");
end

inputChoice = questdlg( ...
    sprintf([ ...
        '%s\n\nREFERENCE FILE:\n%s\n\nSAMPLE FILE:\n%s\n\n' ...
        'Continue with these ordered inputs?'], ...
        upper(operationLabel), referenceFile, sampleFile), ...
    "SpectraLab - Confirm reference and sample", ...
    "Continue", ...
    "Cancel", ...
    "Continue");
if isempty(inputChoice) || strcmp(inputChoice, "Cancel")
    referenceFile = "";
    sampleFile = "";
end
end
