function result=verifyIdentity(options)
%VERIFYIDENTITY Verify that all release version identities agree.
arguments
    options.ExpectedVersion (1,1) string=""
    options.ExpectedTag (1,1) string=""
end
packageFolder=string(fileparts(mfilename("fullpath")));
projectRoot=fileparts(fileparts(fileparts(packageFolder)));
fileVersion=strtrim(string(fileread(fullfile(projectRoot,"VERSION"))));
runtimeVersion=string(spectralab.version());
assert(fileVersion==runtimeVersion, ...
    "SpectraLab:Release:VersionMismatch", ...
    "VERSION contains '%s' but spectralab.version reports '%s'.", ...
    fileVersion,runtimeVersion);
if options.ExpectedVersion~=""
    assert(fileVersion==options.ExpectedVersion, ...
        "SpectraLab:Release:UnexpectedVersion", ...
        "Expected version '%s' but the project reports '%s'.", ...
        options.ExpectedVersion,fileVersion);
end
expectedTag="v"+fileVersion;
if options.ExpectedTag~=""
    assert(options.ExpectedTag==expectedTag, ...
        "SpectraLab:Release:TagVersionMismatch", ...
        "Tag '%s' does not match project version '%s'. Expected '%s'.", ...
        options.ExpectedTag,fileVersion,expectedTag);
end
readme=string(fileread(fullfile(projectRoot,"README.md")));
assert(contains(readme,"Version: "+expectedTag), ...
    "SpectraLab:Release:ReadmeVersionMismatch", ...
    "README.md does not identify project version '%s'.",expectedTag);
exactTag="";
command=sprintf('git -C "%s" describe --tags --exact-match HEAD 2>/dev/null', ...
    projectRoot);
[status,output]=system(command);
if status==0
    exactTag=strtrim(string(output));
    assert(exactTag==expectedTag, ...
        "SpectraLab:Release:HeadTagVersionMismatch", ...
        "HEAD tag '%s' does not match project version '%s'.", ...
        exactTag,fileVersion);
end
result=struct("Status","PASS","Version",fileVersion, ...
    "ExpectedTag",expectedTag,"ExactHeadTag",exactTag);
fprintf("SpectraLab release identity: PASS (%s, %s)\n", ...
    fileVersion,expectedTag);
end
