function spec = d65()
%D65 Return the bundled official CIE standard illuminant D65 SPD.
%
% Source: CIE 2019, CIE_std_illum_D65.csv, DOI 10.25039/CIE.DS.hjfjmt59.

persistent cached
if isempty(cached)
    filename = fullfile(fileparts(mfilename("fullpath")), ...
        "CIE_std_illum_D65.csv");
    values = readmatrix(filename);
    if size(values, 2) ~= 2 || size(values, 1) ~= 531 || ...
            any(~isfinite(values), "all") || values(1,1) ~= 300 || ...
            values(end,1) ~= 830
        error("SpectraLab:CIE:D65DataInvalid", ...
            "Bundled CIE D65 data is invalid.");
    end
    cached = spectralab.core.Spectrum( ...
        values(:,1), values(:,2), "CIE standard illuminant D65", ...
        struct("Name", "CIE 2019", ...
            "DOI", "10.25039/CIE.DS.hjfjmt59"), ...
        struct(), struct(), "relative spectral power");
end
spec = cached;
end
