function contract = visibleLightContract()
%VISIBLELIGHTCONTRACT Canonical visible-light interval in SpectraLab.
%   Architecture-wide definition used wherever a bounded visible-light
%   domain is required. Bounds are inclusive.
contract = struct( ...
    "Schema", "spectralab.visible-light-contract", ...
    "SchemaVersion", "1.0", ...
    "Name", "Visible light", ...
    "WavelengthRangeNm", [400 730], ...
    "Bounds", "inclusive");
end
