% assign_colorchecker_target_definition
%
% Assign the official X-Rite ColorChecker Digital SG definition to a
% completed legacy SpectraLab session. The source JSON and every MAT archive
% remain unchanged. A separate, verified target-defined JSON is created.

scriptFolder = string(fileparts(mfilename("fullpath")));
workRoot = string(fileparts(scriptFolder));
[name, folder] = uigetfile( ...
    {"*.json", "ColorChecker measurement session JSON (*.json)"}, ...
    "SpectraLab - Select completed original or amended ColorChecker session", ...
    workRoot);
if isequal(name, 0)
    disp("ColorChecker target assignment cancelled. Nothing was saved.");
    return
end
sourceFile = fullfile(string(folder), string(name));
target = spectralab.colorchecker.targetDefinition( ...
    "xrite-colorchecker-digital-sg-140");

message = "Assign this official target definition?" + newline + newline + ...
    "Name: " + target.Name + newline + ...
    "Canonical ID: " + target.CanonicalID + newline + ...
    "Geometry: " + target.Columns + " columns × " + target.Rows + ...
    " rows (" + target.PatchCount + " patches)" + newline + newline + ...
    "Confirm only if this is the physical chart that was measured." + ...
    newline + newline + ...
    "The selected JSON and all MAT files will remain unchanged.";
choice = questdlg(message, ...
    "SpectraLab - Confirm ColorChecker target", ...
    "Assign definition", "Cancel", "Assign definition");
if isempty(choice) || choice == "Cancel"
    disp("ColorChecker target assignment cancelled. Nothing was saved.");
    return
end

[session, outputFile] = spectralab.colorchecker.assignTargetDefinition( ...
    sourceFile, target.CanonicalID);

message = "Controlled target definition assigned." + newline + newline + ...
    "Source JSON preserved:" + newline + sourceFile + newline + newline + ...
    "Target-defined JSON:" + newline + outputFile + newline + newline + ...
    "Verified patch archives: " + ...
        session.TargetDefinitionAssignment.VerifiedPatchCount + newline + ...
    "Measurement data changed: no" + newline + newline + ...
    "Next, run calculate_colorchecker_colorimetry and select the new JSON.";
uiwait(msgbox(message, ...
    "SpectraLab - Target definition assigned", "help", "modal"));

fprintf("Controlled ColorChecker target definition assigned:\n");
fprintf("  INPUT source JSON:     %s\n", sourceFile);
fprintf("  OUTPUT defined JSON:   %s\n", outputFile);
fprintf("  Target:                %s\n", target.Name);
fprintf("  Verified MAT archives: %d\n", ...
    session.TargetDefinitionAssignment.VerifiedPatchCount);
fprintf("  Measurement data changed: no\n");
fprintf("Next: run calculate_colorchecker_colorimetry and select the OUTPUT JSON.\n");
