function aligned = alignArchivePair(firstArchive, secondArchive, options)
%ALIGNARCHIVEPAIR Validate and align two archived spectra.

arguments
    firstArchive (1,1) struct
    secondArchive (1,1) struct
    options.Resample (1,1) logical = false
    options.RefinementFactor (1,1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.InterpolationMethod (1,1) string ...
        {mustBeMember(options.InterpolationMethod, ...
        ["pchip", "makima", "spline"])} = "pchip"
end

validateInput(firstArchive, "First");
validateInput(secondArchive, "Second");

firstWavelength = double(firstArchive.Measurement.Wavelength(:));
secondWavelength = double(secondArchive.Measurement.Wavelength(:));
firstValue = double(firstArchive.Measurement.Value(:));
secondValue = double(secondArchive.Measurement.Value(:));

firstUnit = string(firstArchive.Measurement.Unit);
secondUnit = string(secondArchive.Measurement.Unit);
if firstUnit ~= secondUnit
    error("SpectraLab:Analysis:UnitMismatch", ...
        "The two source archives must use the same measurement unit.");
end

if ~options.Resample
    if ~isequal(firstWavelength, secondWavelength)
        error("SpectraLab:Analysis:WavelengthMismatch", ...
            "Source wavelength grids differ. Set Resample=true to align them.");
    end
    wavelength = firstWavelength;
    alignedFirst = firstValue;
    alignedSecond = secondValue;
    alignment = "Exact";
else
    firstSpec = spectralab.core.Spectrum(firstWavelength, firstValue);
    secondSpec = spectralab.core.Spectrum(secondWavelength, secondValue);
    firstFine = spectralab.core.resampleSpectrum(firstSpec, ...
        RefinementFactor=options.RefinementFactor, ...
        Method=options.InterpolationMethod);
    secondFine = spectralab.core.resampleSpectrum(secondSpec, ...
        RefinementFactor=options.RefinementFactor, ...
        Method=options.InterpolationMethod);

    overlap = [max(firstFine.WavelengthNm(1), secondFine.WavelengthNm(1)), ...
        min(firstFine.WavelengthNm(end), secondFine.WavelengthNm(end))];
    if overlap(1) >= overlap(2)
        error("SpectraLab:Analysis:NoCommonWavelengthRange", ...
            "The source archives have no common wavelength range.");
    end

    wavelength = unique([ ...
        firstFine.WavelengthNm(firstFine.WavelengthNm >= overlap(1) & ...
            firstFine.WavelengthNm <= overlap(2)); ...
        secondFine.WavelengthNm(secondFine.WavelengthNm >= overlap(1) & ...
            secondFine.WavelengthNm <= overlap(2))]);
    alignedFirst = interp1(firstFine.WavelengthNm, firstFine.Power, ...
        wavelength, options.InterpolationMethod);
    alignedSecond = interp1(secondFine.WavelengthNm, secondFine.Power, ...
        wavelength, options.InterpolationMethod);
    alignment = "Interpolated";
end

aligned = struct( ...
    "WavelengthNm", wavelength(:), ...
    "FirstValue", alignedFirst(:), ...
    "SecondValue", alignedSecond(:), ...
    "Unit", firstUnit, ...
    "Alignment", alignment, ...
    "Resampled", options.Resample, ...
    "RefinementFactor", options.RefinementFactor, ...
    "InterpolationMethod", options.InterpolationMethod);
end

function validateInput(archive, role)
validation = spectralab.archive.validate(archive);
if ~validation.IsValid
    error("SpectraLab:Analysis:Invalid" + role + "Archive", ...
        "%s source archive is invalid:\n%s", role, ...
        strjoin(validation.Errors, newline));
end

value = double(archive.Measurement.Value(:));
if any(~isfinite(value))
    error("SpectraLab:Analysis:Invalid" + role + "Signal", ...
        "%s source spectrum must contain finite values.", role);
end
end
