function filter = yBar()
%YBAR Return the CIE 1931 2 degree CIE 1931 2 degree yBar weighting function.
%
%   filter = spectralab.filters.cie1931.yBar()

    data = loadData();

    filter = spectralab.core.SpectralFilter.fromTable( ...
        data(:,1), ...
        data(:,3), ...
        Name="CIE 1931 2 degree yBar", ...
        Unit="relative", ...
        Source="CIE 2019, DOI 10.25039/CIE.DS.xvudnb9b", ...
        Description="CIE 1931 2 degree y colour-matching function.");
end


function data = loadData()

    packageFolder = fileparts(fileparts(mfilename("fullpath")));
    filename = fullfile( ...
        packageFolder, ...
        "data", ...
        "CIE_xyz_1931_2deg.csv");

    if ~isfile(filename)
        error( ...
            "spectralab:filters:cie1931:MissingData", ...
            "Required CIE dataset was not found: %s", ...
            filename);
    end

    data = readmatrix(filename);

    if size(data,2) ~= 4 || size(data,1) < 2
        error( ...
            "spectralab:filters:cie1931:InvalidData", ...
            "The CIE dataset must contain wavelength, xBar, yBar, and zBar.");
    end
end
