function spec = restore(archive)
%RESTORE Restore a Spectrum object from a SpectraLab archive.
%
%   spec = spectralab.archive.restore(archive)

arguments
    archive (1,1) struct
end

spec = spectralab.core.Spectrum( ...
    archive.Measurement.Wavelength, ...
    archive.Measurement.Value, ...
    archive.Measurement.Name, ...
    archive.Instrument, ...
    struct(), ...
    struct(), ...
    archive.Measurement.Unit);

end