function [renderContext, result] = renderPageBreak( ...
        element, context, renderContext)
%RENDERPAGEBREAK Render one pageBreak document element.

[renderContext, result] = ...
    spectralab.report.internal.elementRenderers.renderElementCore( ...
        element, context, renderContext, "pageBreak");
end
