function [renderContext, result] = renderList( ...
        element, context, renderContext)
%RENDERLIST Render one list document element.

[renderContext, result] = ...
    spectralab.report.internal.elementRenderers.renderElementCore( ...
        element, context, renderContext, "list");
end
