function [renderContext, result] = renderHeading( ...
        element, context, renderContext)
%RENDERHEADING Measure and record one heading document element.

style = struct( ...
    "FontSize", 16, ...
    "LineHeight", 20, ...
    "SpaceAfter", 8, ...
    "AverageGlyphWidthFactor", 0.55);

[renderContext, result] = ...
    spectralab.report.internal.elementRenderers.renderMeasuredText( ...
        element, context, renderContext, "heading", style);
end
