function [renderContext, result] = renderCaption( ...
        element, context, renderContext)
%RENDERCAPTION Measure and record one figure-caption element.

if string(element.Role) ~= "primaryFigureCaption"
    [renderContext, result] = ...
        spectralab.report.internal.elementRenderers.renderElementCore( ...
            element, context, renderContext, "caption");
    return
end

renderContext = spectralab.report.internal.ensureLayoutState(renderContext);
model = spectralab.report.internal.buildFigureCaption(element.Content);
style = struct( ...
    "FontSize", 9, ...
    "LineHeight", 12, ...
    "SpaceAfter", 8, ...
    "AverageGlyphWidthFactor", 0.50);
height = spectralab.report.internal.estimateTextHeight( ...
    model.Text, style, renderContext.State.Layout.ContentWidth);

captionElement = element;
captionElement.Content = model;
[renderContext, ~] = ...
    spectralab.report.internal.elementRenderers.renderElementCore( ...
        captionElement, context, renderContext, "caption");
result = spectralab.report.internal.createRenderResult( ...
    element.Id, element.Type, height, false, strings(0,1));
end
