function filter = blue()
%BLUE Return the ISO Status A blue transmission weighting.
%
%   filter = spectralab.filters.statusA.blue()
%
%   Values are normalized linear spectral products derived from the
%   logarithmic documentary values in ANSI/ISO 5-3:1995, Table 3.

    [wavelengthNm, value] = statusAData("blue");

    filter = spectralab.core.SpectralFilter.fromTable( ...
        wavelengthNm, ...
        value, ...
        Name="ISO Status A Blue transmission", ...
        Unit="relative spectral product", ...
        Source="ANSI/ISO 5-3:1995, Table 3", ...
        Description="Normalized Status A blue transmission spectral product.");
end
