function filter = green()
%GREEN Return the ISO Status A green transmission weighting.
%
%   filter = spectralab.filters.statusA.green()
%
%   Values are normalized linear spectral products derived from the
%   logarithmic documentary values in ANSI/ISO 5-3:1995, Table 3.

    [wavelengthNm, value] = statusAData("green");

    filter = spectralab.core.SpectralFilter.fromTable( ...
        wavelengthNm, ...
        value, ...
        Name="ISO Status A Green transmission", ...
        Unit="relative spectral product", ...
        Source="ANSI/ISO 5-3:1995, Table 3", ...
        Description="Normalized Status A green transmission spectral product.");
end
