function filter = red()
%RED Return the ISO Status A red transmission weighting.
%
%   filter = spectralab.filters.statusA.red()
%
%   Values are normalized linear spectral products derived from the
%   logarithmic documentary values in ANSI/ISO 5-3:1995, Table 3.

    [wavelengthNm, value] = statusAData("red");

    filter = spectralab.core.SpectralFilter.fromTable( ...
        wavelengthNm, ...
        value, ...
        Name="ISO Status A Red transmission", ...
        Unit="relative spectral product", ...
        Source="ANSI/ISO 5-3:1995, Table 3", ...
        Description="Normalized Status A red transmission spectral product.");
end
