function panel = reflectanceColorimetryPanel(ax, archive)
%REFLECTANCECOLORIMETRYPANEL Add archived Spotread XYZ and Lab beside a plot.

arguments
    ax (1,1) matlab.graphics.axis.Axes
    archive (1,1) struct
end

if ~isfield(archive, "Measurement") || ...
        ~isfield(archive.Measurement, "Context") || ...
        ~isstruct(archive.Measurement.Context) || ...
        ~isfield(archive.Measurement.Context, ...
            "InstrumentReportedColorimetry")
    panel = gobjects(0);
    return
end
reported = archive.Measurement.Context.InstrumentReportedColorimetry;
if ~isstruct(reported) || ~isfield(reported, "available") || ...
        ~logical(reported.available) || ~isfield(reported, "xyz") || ...
        ~isfield(reported, "lab")
    panel = gobjects(0);
    return
end
xyz = double(reported.xyz(:));
lab = double(reported.lab(:));
if numel(xyz) ~= 3 || numel(lab) ~= 3 || any(~isfinite([xyz; lab]))
    panel = gobjects(0);
    return
end

profile = spectralab.report.internal.figureLayoutProfile();
fig = ancestor(ax, "figure");
ax.Units = "normalized";
ax.Position = profile.AxesWithSidebar;
panel = axes("Parent", fig, "Units", "normalized", ...
    "Position", profile.SidePanel, "Visible", "off", ...
    "Tag", "SpectraLabFigureInformationPanel", ...
    "HandleVisibility", "off");
text(panel, 0, 1, sprintf( ...
    "Instrument-reported control values\nXYZ: %.3f, %.3f, %.3f\nLab: %.3f, %.3f, %.3f", ...
    xyz(1), xyz(2), xyz(3), lab(1), lab(2), lab(3)), ...
    "Units", "normalized", "HorizontalAlignment", "left", ...
    "VerticalAlignment", "top", "BackgroundColor", "white", ...
    "EdgeColor", [0.8 0.8 0.8], "Margin", 6, "FontSize", 9, ...
    "Interpreter", "none", "Tag", "SpectraLabReflectanceColorimetry");
end
